### PR TITLE
Update PrivateDev pipeline to not run tests by default

### PR DESCRIPTION
**Pull request by jeffkl**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/2843

Regression? Last working version:

## Description

This disables the tests in the PrivateDev build by default, since they are now run by the [NuGet.Client CI](https://dev.azure.com/dnceng-public/public/_build?definitionId=289&_a=summary).  You can still manually run the pipeline and select the stages to run if desired.  I also left the stages on for the Official Build for now.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
Which CI is posting the checks now?

**Comment by jeffkl** [comment]
> Which CI is posting the checks now?

[NuGet.Client CI](https://dev.azure.com/dnceng-public/public/_build?definitionId=289&_a=summary)

image

I'm working on getting the individual stages/jobs to report their status, I've had to engage the .NET Core Eng Services team: https://github.com/dotnet/dnceng/issues/2925

**Comment by nkolev92** [comment]
So the plan is merge this....wait some time for everyone to rebase and enable that as one of the 2 required checks alongside the build from now PrivateDev?

**Review by nkolev92 — APPROVED** [review]

**Comment by jeffkl** [comment]
> So the plan is merge this....wait some time for everyone to rebase and enable that as one of the 2 required checks alongside the build from now PrivateDev?

NuGet.Client CI has been around for two weeks, I've made it required as of today.  If its blocking anyone, we can change things or force merge.  For users who have not rebased, the tests will still run in the two pipelines.

**Comment by nkolev92** [comment]
> > So the plan is merge this....wait some time for everyone to rebase and enable that as one of the 2 required checks alongside the build from now PrivateDev?
> 
> NuGet.Client CI has been around for two weeks, I've made it required as of today. If its blocking anyone, we can change things or force merge. For users who have not rebased, the tests will still run in the two pipelines.

Oh duh, I forgot about that. yeah, makes sense to enable it.

**Review by dtivel — APPROVED** [review]

**Pull request merged**
