### PR TITLE
Reverted async file io operations

### PR DESCRIPTION
**Pull request by alpaix**
Changed async file io writes to be sync to avoid performance issues.
Test fix.
Renamed methods to reflect the changes (removed async suffix where
applicable).

### CODE REVIEW

**Comment by alpaix** [comment]
//cc @yishaigalatzer @emgarten @deepakaravindr

**Comment by emgarten** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
:shipit:. 

Just 1 question to understand it better.
Would setting ConfigureAwait to false made it faster than using the sync methods?
Also,
do we know if this version is faster than the original version before converting file operations to async?

**Comment by emgarten** [comment]
I've merged this into dev

**Comment by alpaix** [comment]
@deepakaravindr I'm sure ConfigureAwait(false) wouldn't help in this case. To the best of my knowledge it helps avoiding deadlocks in console and UI applications with main thread. It hints the task scheduler to use thread pool for task execution.  In a case of nuget.exe main thread is already blocked on ExecuteCommandAsync().Wait() so that all tasks run on pool.

Compare to v3.3 I noted about 7% performance improvement on my desktop. Also customer confirmed it's about the same now.

**Comment by alpaix** [comment]
@emgarten Thanks for merging the PR!

**Comment by yishaigalatzer** [comment]
@alpaix actually it hints that you can hop a thread and not go back to the calling thread (rather than then main thread). So it could be beneficial here. Though I agree with what your decision here.

I think the issue in nuget.exe is that we might not actually have synchronization context on all the other threads?

**Pull request closed without merging**
