### PR TITLE
Don't reuse HttpRequestMessage objects

### LINKED ISSUE #8661: HttpRequestMessage gets reused multiple times which is not supported with the SocketHttpHandler
The [`SocketHttpHandler` does not support reusing HttpRequestMessages multiple times](https://github.com/dotnet/corefx/issues/25163). This can lead to issues with authentification if the user provides the wrong credentials the first time, because the `Authorization` header gets [added](https://github.com/dotnet/corefx/blob/eff9fbf446468ca411bf5e0475916f316eea7223/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs#L164-L174) by the `SocketHttpHandler` and is resend on the next try. In combination with some servers (e.g. the GitHub NuGet feed) this results in an loop where each time the same credentials are being passed in because this server does not send a `Www-Authenticate` header if an `Authorization` header is provided and so the [new credentials are never added](https://github.com/dotnet/corefx/blob/eff9fbf446468ca411bf5e0475916f316eea7223/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs#L242).

To prevent this issue it is currently possible to disable the `SocketHttpHandler` which I have done here https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/841

See also https://github.com/dotnet/corefx/issues/25163#issuecomment-538009706

### Sample Project

```c#
[Fact]
public async Task GitHubFeedTest()
{
    // uncomment this to fix the issue
    //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

    HttpHandlerResourceV3.CredentialService = new Lazy<ICredentialService>(() => new CredentialService(
        new AsyncLazy<IEnumerable<ICredentialProvider>>(
            () => Task.FromResult<IEnumerable<ICredentialProvider>>(new ICredentialProvider[] { new TestCredentialProvider()})
        ),
        nonInteractive: false,
        handlesDefaultCredentials: true
    ));
    // change `username` in this url to your user
    var source = Repository.Factory.GetCoreV3("https://nuget.pkg.github.com/username/index.json");
    var sourceProvider = await source.GetResourceAsync<PackageSearchResource>();

    await sourceProvider.SearchAsync("", new SearchFilter(false), 0, 10, NullLogger.Instance, CancellationToken.None);
}
private class TestCredentialProvider : ICredentialProvider
{
    public string Id => "test";
    public Task<CredentialResponse> GetAsync(Uri uri, IWebProxy proxy, CredentialRequestType type, string message, bool isRetry, bool nonInteractive, CancellationToken cancellationToken)
    {
        if (!isRetry)
        {
            return Task.FromResult(new CredentialResponse(new NetworkCredential("a", "b"))); // intentional wrong user and password
        }
        return Task.FromResult(new CredentialResponse(new NetworkCredential("username", "token"))); // change `username` and `token` to your github user and [token](https://github.com/settings/tokens) with package access
    }
}
```

### PR DESCRIPTION
**Pull request by campersau**
## Bug

Fixes: https://github.com/NuGet/Home/issues/8661
Regression: No

## Fix

Details: See issue details

## Testing/Validation

Tests Added: Yes
Validation:

### CODE REVIEW

**Comment by zivkan** [comment]
@campersau Sorry about the delay. Unfortunately the build is failing with your changes. There are 4 nuget.exe test failures on Windows (.NET Framework), and 14 nuget.exe test failures on Mac (Mono). Most of them (maybe all of them) are null reference exceptions.
[log_56_3123762.zip](https://github.com/NuGet/NuGet.Client/files/3730432/log_56_3123762.zip)
[log_142_3123762.zip](https://github.com/NuGet/NuGet.Client/files/3730433/log_142_3123762.zip)

**Comment by campersau** [comment]
Yes, the `HttpContent` also needs to be cloned for retries (or not being disposed by them). Currently I am only wrapping them because most of the `HttpContent` implementations can be reused multiple times.

**Comment by zivkan** [comment]
I think we can merge this as soon as the dev branch targets 5.5.

**Review by nkolev92 — APPROVED** [review]
LGTM. 

@zivkan you reviewed it last but no approval. Merge if/when it looks good.

**Review by zivkan — APPROVED** [review]

**Pull request merged**
