### PR TITLE
Add Tizen.Net TFM

### PR DESCRIPTION
**Pull request by WonyoungChoi**
Issue : https://github.com/NuGet/Home/issues/4175

- Identifier: Tizen (tizen)
- tizen3.x supports netstandard1.0 ~ netstandard1.6
- tizen4.x supports netstandard1.0 ~ netstandard1.7

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
Ping.
Sorry to bother you, but please review this PR.
This is very important thing for us. Because we want to release our packages with this "Tizen" TFM at the official release of Tizen.Net this year. And this TFM is needed to contribute our renderer implementation to Xamarin.Forms also.

**Review by emgarten — APPROVED** [review]
This looks correct to me. I like that the name is the same both in the long and short form like the modern frameworks. The compat mappings and tests look correct to me also. ✨

**Comment by rrelyea** [comment]
Looping in @UnniRavindranathan to clarify the right timeframe that we should consider merging this PR into NuGet.

**Comment by emgarten** [comment]
Merged into 4.1 and dev

**Pull request closed without merging**
