### PR TITLE
Depending on specific version of Nuget.Core and removed *

### PR DESCRIPTION
**Pull request by jainaashish**
Depending on specific version of Nuget.Core and removed *

Fix https://github.com/NuGet/Home/issues/2983

### CODE REVIEW

**Comment by jainaashish** [comment]
@joelverhagen @rrelyea @emgarten

**Comment by rrelyea** [comment]
lgtm

**Comment by joelverhagen** [comment]
:shipit:

**Comment by jainaashish** [comment]
Merged f8ccd36e0afb60f0beabebfada2857c73cb80dab

**Pull request closed without merging**
