### PR TITLE
Add the A/B experimentation constant for the Transitive Dependencies in PMUI feature

### LINKED ISSUE #10758: Enhance the experimentation infrastructure in NuGet code to support transitive dependencies

### PR DESCRIPTION
**Pull request by jebriede**
## Bug

Fixes: https://github.com/nuget/home/issues/10758

Regression? Last working version: N/A

## Description
Adding the experimentation constant that will be used as a flag for the A/B experiment for Transitive Dependencies in the PMUI. Commits that contribute to this feature can start using this flag to ensure the proper guard is in place for the treatment code versus control code.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
Adding a constant for the specific experiment. The experimentation infrastructure is covered with unit tests.
  - [x] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by dominoFire — APPROVED** [review]

**Review by nkolev92 — APPROVED** [review]
I imagine the usage will happen at a later point?

**Comment by jebriede** [comment]
> I imagine the usage will happen at a later point?

@nkolev92 yes, it will be used by other code contributing to this feature, including code in active PRs today.

**Review by jeffkl — APPROVED** [review]

**Review by martinrrm — APPROVED** [review]

**Comment by nkolev92** [comment]
@jebriede rebasing this might allow you to merge it. 

I tried reruning the build, but apparently a rebase is needed.

**Comment by dominoFire** [comment]
Using flag in this PR: https://github.com/NuGet/NuGet.Client/pull/4119

**Pull request closed without merging**
