### PR TITLE
dedupe runtime dependencies

### PR DESCRIPTION
**Pull request by analogrelay**
Fixes NuGet/Home#1964

Seemed like the quickest, easiest and least impactful way to accomplish this :)

/cc @davidfowl @yishaigalatzer @emgarten

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
LGTM, if @emgarten likes it I'm good

**Comment by analogrelay** [comment]
Cool. The quicker we get this in the better. It's the remaining un-workaroundable issue blocking dotnet/cli integration as far as I can tell.

**Comment by emgarten** [comment]
:shipit:

**Comment by emgarten** [comment]
Merged NuGet/NuGet.Client@36e3183f676ce46dbaa7ba3b4c7cde69f6ae210d

**Comment by davidfowl** [comment]
Ahhhhh those damn package redirects. Should probably add a test for this

**Pull request closed without merging**
