### PR TITLE
NuGet.VisualStudio no longer uses EmbedInteropTypes

### LINKED ISSUE #10892: Stop using EmbedInteropTypes for NuGet's VS extenbility packages/assemblies
The VS SDK for dev17 (VS 2022) has stopped using EmbedInteropTypes. One of their primary reasons is that is makes sharing components with VS for Mac problematic. This might not really be an issue for us, since we (NuGet client team) don't work on VS for Mac in any way, so our VS APIs might not be in VS for Mac.  But it would be good to align with design choices for VS, plus some VS (on windows) internal teams have reported issues to me which binding redirects would solve.

### PR DESCRIPTION
**Pull request by zivkan**
## Bug

Fixes: https://github.com/NuGet/Home/issues/10892

Regression? No

## Description

Following the example of Microsoft.VisualStudio.Sdk for VS 2022, change NuGet.VisualStudio to no longer embed NuGet.VisualStudio.dll's interop types.

Also set up binding redirect for NuGet.VisualStudio.dll, which will be needed once customers and partners use this updated package.

## PR Checklist

- [X] PR has a meaningful title
- [X] PR has a linked issue.
- [X] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [X] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [X] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
Should we do the same with the solution restore manager manager?
Any unitended consequences from having some deps with the embedded assembly vs ones without? 

This *will* cause an RPS regression btw, so we need to proactively address that.

**Comment by nkolev92** [comment]
Related issue here: https://github.com/NuGet/Home/issues/10868

**Review by nkolev92 — DISMISSED** [review]

**Review by nkolev92 — COMMENTED** [review]
Actually, don;'t you need the 2 assemblies in vsixinclude?

**Comment by zivkan** [comment]
> Actually, don;'t you need the 2 assemblies in vsixinclude?

`NuGet.VisualStudio.dll` was already in `.vsixinclude`.  I updated the PR to include `NuGet.SolutionRestoreManager.Interop.dll`.

Good catch!

**Review by nkolev92 — APPROVED** [review]

**Review by dominoFire — APPROVED** [review]

**Comment by zivkan** [comment]
Urgent issue was mitigated in VS. I'll work on this PR again once E2E tests are working.

**Pull request merged**
