### PR TITLE
Dev dominofire localunittests2

### PR DESCRIPTION
**Pull request by dominoFire**
Copy of https://github.com/NuGet/NuGet.Client/pull/2749 . Do not review or merge

### CODE REVIEW

**Comment by nkolev92** [comment]
If it's a copy should the original one be closed? 

I don't get the point of 2 PRs

**Comment by dominoFire** [comment]
> If it's a copy should the original one be closed?
> 
> I don't get the point of 2 PRs

To test what happens on the CI if I merge this PR to dev. I will delete this PR once the first one is merged.

**Comment by nkolev92** [comment]
Why can't you rerun the CI on the same build?

**Comment by dominoFire** [comment]
> Why can't you rerun the CI on the same build?

@nkolev92 Because I needed the changes already present in `dev` branch, merge with my actual branch and see what happens. The original PR is merged.

**Comment by nkolev92** [comment]
I am still not sure then. 

Why not just rebase?

You also don't need a PR to trigger the CI since you are pushing under NuGet.Client. 

Every dev-* will be picked up by the CI.

**Comment by dominoFire** [comment]
> I am still not sure then.
> 
> Why not just rebase?
> 
> You also don't need a PR to trigger the CI since you are pushing under NuGet.Client.
> 
> Every dev-* will be picked up by the CI.

My bad. I wasn't aware of `git rebase` on the dev-* branches. Next time, I will try that. For now, I will close this PR and delete the corresponding branch.

**Comment by nkolev92** [comment]
We learn something new every day :)

**Pull request closed without merging**
