### PR TITLE
Set shadowCopy to false for Apex tests

### LINKED ISSUE #8386: Test:  InstallAndUpdatePackageWithSourceParameterWarnsAsync is flaky
An APEX test is failing in multiple builds

https://devdiv.visualstudio.com/DevDiv/NuGet/_TestManagement/Runs?runId=7599252&_a=runCharts

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2886571

The 'Source' parameter is not respected for the transitive package management based project(s) TestProject. The enabled sources in your NuGet configuration will be used
Expected: True
Actual: False

### LINKED ISSUE #9410: Test: CreateNetCoreProject_AddProjectReference is flaky
There have been numerous CI failures on this test. Exception message:

> Expected True because TestProject2/1.0.0 should be installed in TestProject, but found False.

stack trace:
```text
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions.BeTrue(String because, Object[] becauseArgs)
   at NuGet.Tests.Apex.CommonUtility.AssertPackageInAssetsFile(VisualStudioHost visualStudio, ProjectTestExtension project, String packageName, String packageVersion, ILogger logger) in E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Utility\CommonUtility.cs:line 226
   at NuGet.Tests.Apex.NetCoreProjectTestCase.CreateNetCoreProject_AddProjectReference(ProjectTemplate projectTemplate) in E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetEndToEndTests\NetCoreProjectTestCase.cs:line 50
```

### LINKED ISSUE #9476: Test: UninstallFromPMCForPC_SucceedAsync is flaky
The test `NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync(projectTemplate: ClassLibrary)` has timed out on at least two builds: [1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3669401&view=logs&j=54d34e6c-10d1-5f6f-0d73-85c1fa19385b&t=2bc2bfed-4a11-5a5c-814b-223591eb3d53), [2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3672284&view=logs&j=54d34e6c-10d1-5f6f-0d73-85c1fa19385b&t=2bc2bfed-4a11-5a5c-814b-223591eb3d53)

Since it times out, the test results xml doesn't get generated, which means Azure DevOps test result analysis can't help us determine how often it's happening (the Apex tests job has timed out for multiple reasons in the past)

```
     NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync(projectTemplate: ClassLibrary) [STARTING]
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:05:04
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:10:04
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:15:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:20:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:25:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:30:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:35:05
Attempting to cancel the build...
##[error]The task has timed out.
```

### LINKED ISSUE #11308: Re-enable flaky Apex tests failing due to IPC errors
Since switching to new Visual Studio testing infrastructure, we're getting a high rate of tests failing with IPC errors:

> System.AggregateException : One or more errors occurred.
> ---- System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.

All these errors appear to be coming from two places in our code:

https://github.com/NuGet/NuGet.Client/blob/892375745964db627494305fd605496454b5ad0a/test/NuGet.Tests.Apex/NuGet.Tests.Apex/Utility/CommonUtility.cs#L451

https://github.com/NuGet/NuGet.Client/blob/892375745964db627494305fd605496454b5ad0a/test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/ApexTestContext.cs#L54

Interestingly though, it appears that a small number of tests are the ones that keep failing.

Below is an example stack trace reported in Azure DevOps' test results view:

```
----- Inner Stack Trace #1 (System.Runtime.Remoting.RemotingException) -----

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Test.Apex.VisualStudio.Solution.SolutionService.SaveAndClose()
   at NuGet.Tests.Apex.ApexTestContext.Dispose() in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Apex\ApexTestContext.cs:line 54
   at NuGet.Tests.Apex.AuthorSignedPackageTestCase.<UpdateUnsignedToSignedVersionFromPMCForPC_SucceedAsync>d__4.MoveNext() in D:\a\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\NuGetPackageSigningTests\AuthorSignedPackageTestCase.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace #2 (System.Runtime.Remoting.RemotingException) -----

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   at System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.
```

### PR DESCRIPTION
**Pull request by heng-liu**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/1299 
Fixes: https://github.com/NuGet/Home/issues/11308

The following might be fixed:
Fixes: https://github.com/NuGet/Home/issues/9410
Fixes: https://github.com/NuGet/Home/issues/8386
Fixes: https://github.com/NuGet/Home/issues/9476

Regression? Last working version:

## Description

- Set `shadowCopy` to false in test/NuGet.Tests.Apex/NuGet.Tests.Apex/xunit.runner.json 
- Enable 16 out of 18 disabled Apex tests.

Context:
IPC error in Apex tests have been bothering us for a while. When working on migrating Apex tests from Xunit to MSTest, I found  loggings in flaky MSTest and it related to https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/9736/Shadow-Copying-Assemblies. And it suggests setting `shadowCopy` to false in the Xunit configuration file. 
[shadowCopy](https://xunit.net/docs/configuration-files#shadowCopy):
`Set this to true to use shadow copying when running tests in separate App Domains; set to false to run tests without shadow copying. When running tests without App Domains, this value is ignored.`
I then tried to enable all 18 disabled Apex tests and run 10 builds in a row, none of them failed for IPC error.
Out of the 10 runs:
2 Apex tests which were disabled long time ago constantly fail for assertion errors, we might need to change the test.
2 runs timed out. 
Other apex tests are good.

We will still need to migrate to MSTest since Xunit test is not able to time out single test case, and MSTest has more info for Apex tests so it will be easier for diagnosing.
So in the long run, this is a temporary fix, but there is no harm if we have better Apex tests than what we have for now.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by zivkan — APPROVED** [review]
This is an amazing find, well done!  If the apex tests start becoming reliable again, it's going to make my monthly CI reliability investigations easier. Thank you!

**Comment by heng-liu** [comment]
//cc @aortiz-msft, shall we merge it to this release? Thanks!

**Review by jeffkl — APPROVED** [review]
🚀

**Review by nkolev92 — APPROVED** [review]
Looks great @heng-liu! Nice catch. 

Can you please make sure all the correct issues get closed when this gets merged?

Here's the few links that aren't included in the fixes statements. 


https://github.com/NuGet/Home/issues/9410
https://github.com/NuGet/Home/issues/8469
https://github.com/NuGet/Home/issues/8386
https://github.com/NuGet/Home/issues/9476

Note that in order for GH to auto close you need to add a `Fixes: https://github.com/NuGet/Home/issues/9476` statement on a new line for every issue.

**Comment by heng-liu** [comment]
Thanks @nkolev92 ! 
Those flaky tests passed in the latest 10 runs. I'll close them for now. But I'm not 100 % sure if the flakiness is fixed.
So, if they're flaky in the future runs, we can reopen them.

**Comment by nkolev92** [comment]
> Thanks @nkolev92 ! Those flaky tests passed in the latest 10 runs. I'll close them for now. But I'm not 100 % sure if the flakiness is fixed. So, if they're flaky in the future runs, we can reopen them.

fwiw, I think those had to be closed by this PR. 
Otherwise we'd have issues that are open and tests that are running. No one would ever close those issues, so it's the right thing :)

**Comment by heng-liu** [comment]
Sorry, there are still IPC errors in the latest run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8451561&view=results  :(

So I should be just lucky to have [10 runs](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8118&_a=summary&branchFilter=619252%2C619252%2C619252%2C619252%2C619252%2C619252%2C619252%2C619252%2C619252%2C619252%2C619252)  in a row without IPC error (only 2 tests constantly fail for assertion errors).

I'll keep working on migrating Apex from Xunit to MSTest.

**Pull request merged**
