### PR TITLE
Added draft contributing guidelines

### PR DESCRIPTION
**Pull request by csharpfritz**

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
We already have contribution guidelines in http://docs.nuget.org/contribute

Lets rationalize both of them first

**Comment by csharpfritz** [comment]
Looks like we need to clean up the contribute doc, as it contains a pointer
to the CI machine that doesn't have any public builds currently.

I'll consolidate, reference the doc.nuget.org item and update it
appropriately to indicate some of the requirements we would like to enforce.

Jeff

**Comment by emgarten** [comment]
@harikm86 would you take a look at this?

**Comment by harikmenon** [comment]
Yes, we will need to merge this into our docs instead of hosting it here. We can link it from the repo but the core documentation to should be there in nuget docs.

@karann-msft will own the contribution part of docs. We will try to get this done in the August mass update to docs.

@karann-msft : Can you copy the content across to nuget docs and figure out how to integrate this into our existing docs. Feel free to add an issue in producttracking to track this work. Lets atleast copy the content and close the PR on NuGet.Client asap

**Comment by yishaigalatzer** [comment]
Do not close. Contribution guide should be in the repo

Get Outlook for Androidhttps://aka.ms/ghei36

On Tue, Jun 21, 2016 at 11:35 PM -0700, "Harikrishna Menon" <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, we will need to merge this into our docs instead of hosting it here. We can link it from the repo but the core documentation to should be there in nuget docs.

@karann-mstfhttps://github.com/karann-mstf will own the contribution part of docs. We will try to get this done in the August mass update to docs.

@karann-mstfhttps://github.com/karann-mstf : Can you copy the content across to nuget docs and figure out how to integrate this into our existing docs. Feel free to add an issue in producttracking to track this work. Lets atleast copy the content and close the PR on NuGet.Client asap

##

**Comment by harikmenon** [comment]
Then lets find a single place to document this. We can do it per repo or have it link from repo to the docs. Lets not duplicate information in 2 different places. I'm okay with either but not with duplicating it in 2 places.

**Pull request closed without merging**
