### PR TITLE
Unroll LINQ usage to trim some allocations in AddMSBuildAssets

### LINKED ISSUE #13223: Unroll LINQ usage to trim some allocations in AddMSBuildAssets

### PR DESCRIPTION
**Pull request by Erarndt**
## Bug

Fixes: https://github.com/NuGet/Home/issues/13223

Regression? Last working version:

## Description

Unrolls some LINQ usage to avoid allocation overhead.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by aortiz-msft** [comment]
@Erarndt - Could we please get some microbenchmarking to understand any perf gains with this commit? This is a requirement for all changes done to improve performance.

**Review by aortiz-msft — CHANGES_REQUESTED** [review]
Needs perf benchmark as stated before.

**Review by nkolev92 — COMMENTED** [review]
Change looks good. 

I think given that the linked issue is not directly related to the change here, I think it'd be save to just assume we need a new issue for these PRs.

**Comment by davkean** [comment]
@Erarndt Can you post the PerfView results blaming these allocations?

@aortiz-msft Unrolling LINQ is a well-known pattern that we've applied 1000s of times in this and other code bases. Micro-benchmarking a change like this adds a overhead to the contribution of these fixes and slows down the work. I think benchmarking should be saved for larger/riskier changes and not patterns we just know from experience are faster. 

We've also contributed similar fixes in this codebase without micro-benchmarks.

**Review by nkolev92 — APPROVED** [review]

**Comment by aortiz-msft** [comment]
> Unrolling LINQ is a well-known pattern that we've applied 1000s of times in this and other code bases. Micro-benchmarking a change like this adds a overhead to the contribution of these fixes and slows down the work. I think benchmarking should be saved for larger/riskier changes and not patterns we just know from experience are faster.

Makes sense. Sorry, I didn't realize I had marked my comment as blocking.

**Review by aortiz-msft — APPROVED** [review]

**Review by jebriede — APPROVED** [review]
LGTM 🚀

**Pull request merged**
