### PR TITLE
Remove unnecessary source-build patch

### LINKED ISSUE #3149: [VMR] nuget-client build fails on case-preserving filesystems (Mac, Windows)
On Linux, `NuGet.config` and `NuGet.Config` are different files. Both can exist in the same folder, and attempts to read the "wrong" file will result in a file not found error. As a result, we have a patch in the NuGet repo, `eng/source-build-patches/0001-Rename-NuGet.Config-to-NuGet.config-to-account-for-a.patch` authored by @crummel, to reconcile a bad casing assumption. However, on Windows and Mac, this patch fails to apply with `git apply` as those two filenames are considered equivalent. This breaks the build on non-Linux.

We either need a way to separate out source build patches by OS applicability (e.g. `eng/source-build-patches/$(TargetOS)/`), or need to eliminate the patch.

### PR DESCRIPTION
**Pull request by MichaelSimons**
## Bug

Fixes: https://github.com/dotnet/source-build/issues/3149

Regression? Last working version: N/A

## Description

This source-build patch is no longer necessary as it was a workaround for an arcade issue that has since been addressed - https://github.com/dotnet/arcade/pull/7549

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@nkolev92 - This is needed for .NET 8.0, will change made in the `dev` branch flow into .NET 8.0?  TIA

**Comment by nkolev92** [comment]
> @nkolev92 - This is needed for .NET 8.0, will change made in the `dev` branch flow into .NET 8.0? TIA

Yep, dev is still targeting NET8.0. 

cc @aortiz-msft to add a `Merge this release` label. This is just infrastructure.

**Review by nkolev92 — APPROVED** [review]

**Comment by nkolev92** [comment]
The source build leg failed, https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8423365&view=logs&j=cb98efd6-7062-56ef-f642-0176540bbe0a, is that expected @MichaelSimons

**Comment by MichaelSimons** [comment]
> The source build leg failed, https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8423365&view=logs&j=cb98efd6-7062-56ef-f642-0176540bbe0a, is that expected @MichaelSimons

No it wasn't intentional.  Looks like I needed to update the arcade version as well as it is old and missing the fix I referenced earlier.  Will open another PR.

**Pull request merged**
