### PR TITLE
Get SDK resolver interactivity level from SdkResolverContext

### PR DESCRIPTION
**Pull request by jeffkl**
Add an extension method that uses reflection to read the new property

### CODE REVIEW

**Comment by jeffkl** [comment]
Dependent on https://github.com/Microsoft/msbuild/pull/3621

I do not have a 15.9 Microsoft.Build.Framework yet, so I just rev'd the project to show the full extent of the change.

**Comment by jeffkl** [comment]
@rohit21agrawal this won't build until I've pushed a 15.9 package of MSBuild containing the new property.

**Comment by jeffkl** [comment]
Okay I've updated to use our preview package, please review

**Comment by jeffkl** [comment]
Another option would be to use reflection so I don't need to update the target framework and use a preview version of our package.

**Comment by jainaashish** [comment]
Not sure what's the ask of this change and which VS branch is this targeting? Is this already approved for 15.9? Do we also need this for dev16? And who'd make sure to remove `dotnet-msbuild` feed and move to a stable `Microsoft.Build.Framework` package?

**Comment by jeffkl** [comment]
At the moment the credential plug-in will not prompt for login because we've hard coded the call to `SetupDefaultCredentialService` with `nonInteractive: true`.  In 15.9, I added some logic in MSBuild to detect the interactivity level that the user specified and piped that through to the SDK resolver.   

To take the change, I either need to compile against a newer version of the `Microsoft.Build.Framework` package which is the reason we need to use our other package feed.  Another option would be to just use reflection.  That would not require me to use a newer package or alternative feed.  I'm open to either one.

Yes this can get approved for 15.9 and the MSBuild change is already in.

**Comment by jeffkl** [comment]
@jainaashish I've changed this to use reflection instead so its not touching as much.  Please let me know when this can get into 15.9 as we need it ASAP to continue testing the authenticated feed scenarios

**Review by AndyGerlicher — APPROVED** [review]

**Review by jainaashish — APPROVED** [review]
LGTM

**Comment by jainaashish** [comment]
as I said on another thread, we first need to merge it to dev and then release-4.9.0-preview2. 

Once we've substantial changes to be inserted into 15.9, we'll start with our insertion process (hopefully tomorrow or day after).

**Comment by jeffkl** [comment]
Thanks, please merge when the CI completes

**Comment by jainaashish** [comment]
Test signing failed for the last build. CI Build triggered again

**Comment by jainaashish** [comment]
Merged into 4.9.0 with 814cc676cc3d779257063f02c8ab61c0ab7e2c1f

**Comment by nkolev92** [comment]
What's the Visual Studio default? 
Would a user need to set this interactive switch in the project to get it to prompt in VS?

**Comment by jeffkl** [comment]
The default is non-interactive.  In Visual Studio, we're using a different credential provider at the moment.  In dev16, the only way to set this property will be through a command-line argument to ensure its only set in a console window.

**Pull request merged**
