### PR TITLE
FileAndForget replacement which logs same fault event for every failure.

### LINKED ISSUE #9812: FileAndForget posts a new event for every point of usage
## Details about Problem

For fire-and-forget asynchronous code, we are currently using VSTelemetryHelpers.FireAndForget helper to log any failures from detached async code. This method is implements so that there is a specific event for every point of failure.

For GDPR categorization and ease of investigating those failures, it may be useful to always post same event, and carry additional context information in description and exception stack trace.

### PR DESCRIPTION
**Pull request by srdjanjovcic**
## Bug

Fixes: https://github.com/NuGet/Home/issues/9812
Regression: No

## Fix

Details: Implement a new extension method for JoinableTask, PostOnFailure, which will always post same-named fault event.

## Testing/Validation

Tests Added: No.
Reason for not adding tests: Hard to test for exceptional circumstances here.
Validation: Pending.

### CODE REVIEW

**Comment by zivkan** [comment]
A while ago I created a helper utility to emit telemetry in exception handlers that we don't expect to ever throw. Can we change it to also use `TelemetryService.DefaultSession.PostFault` with the same event name?

https://github.com/NuGet/NuGet.Client/blob/ce6d944538b1b587d87daa4163b8934069360d23/src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/TelemetryUtility.cs#L30

**Comment by srdjanjovcic** [comment]
@zivkan Definitely... Exceptions should be posted as faults... You get Watson sampling as a bonus.

**Comment by srdjanjovcic** [comment]
I replaced EmitException with PostFailure. However, there is open question whether PostFault will collect inner exceptions, as EmitException does... Let me inquire about it.

**Review by zivkan — APPROVED** [review]
> However, there is open question whether PostFault will collect inner exceptions, as EmitException does.

Don't spent more than an hour. So far it's only for a codepath that I expect will never be hit. If I'm wrong, we might not even need inner exceptions. If we do need inner exception information, then we can improve it at that time. Or as you said, it may trigger watson, so we might get memory dumps anyway.

**Pull request merged**
