### PR TITLE
Release 4.7.2

### PR DESCRIPTION
**Pull request by dslzuha**
## Bug

Fixes: Link_to_issue  
Regression: Yes/No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Details_about_the_fix  

## Testing/Validation

Tests Added: Yes/No  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Comment by dslzuha** [comment]
Trying to use

**Comment by nkolev92** [comment]
@dslzuha Can you explain what are you trying to do here?

**Comment by zivkan** [comment]
regardless of the intention, there's no valid reason to merge an old release branch into dev, so I'm closing this.

@dslzuha if you're trying to learn how to use GitHub, you can do it in your own repositories without affecting other people. Please be careful when creating issues or pull requests on other people's repositories. thanks.

**Comment by rrelyea** [comment]
You seem to be opening a number of PRs in our repo without significant changes. Perhaps you are learning to use GitHub and did not intend to send them to us. Please be aware that other people may be working in repos you do not own, so if you are testing, we suggest you create your own repo and follow steps similar to this: https://guides.github.com/activities/hello-world/

If you are hoping to contribute to nuget.client repro, please make sure to read https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md guidelines and start with step 1 (open an issue), not step 5 (open a PR).

**Pull request closed without merging**
