### PR TITLE
Fix for NuGet/Home/issues/1888

### PR DESCRIPTION
**Pull request by mfaulkinbury**
- added MP project kind as supported project
- handled request for missing TargetFrameworkMoniker
- uses  default project system (VSMSBuildNuGetProjectSystem)

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
@mfaulkinbury is this does all you need it to do, than I'm fine with it. But my guess is that you will have a hard time building packages that suit your needs. I'll be happy to be wrong of course.

CC @emgarten

**Comment by mfaulkinbury** [comment]
@yishaigalatzer 

To clarify, this change opens up the ability to _consume_ packages from an MP project using both the Package Manager Console and the NuGet Package Manager GUI (which currently errors with an "Unsupported Project" message).

I am using existing tooling to build packages, which suffices for now.

CC @emgarten

**Comment by mfaulkinbury** [comment]
@emgarten Can you provide any guidance on this PR?  I don't mind doing additional work if I'm way off track, but I'm reluctant to spend more time before receiving feedback on this.  Thanks.

CC @yishaigalatzer

**Comment by emgarten** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
@emgarten go ahead and merge

**Comment by emgarten** [comment]
@mfaulkinbury would you rebase this against the dev branch?

**Comment by mfaulkinbury** [comment]
@emgarten  done.  let me know if you see any issues.

**Comment by emgarten** [comment]
Merged with NuGet/NuGet.Client@8cf1964392c2f436e2885730bdb0ad89416a2b9b

**Pull request closed without merging**
