### PR TITLE
warning when language mode is not full language

### PR DESCRIPTION
**Pull request by zhili1208**
https://github.com/NuGet/Home/issues/3326

### CODE REVIEW

**Comment by alpaix** [comment]
Do we need the same warning message before running install script?

> Can NuGet warn during package install if that's set?

**Comment by emgarten** [comment]
:bell: @zhili1208 can you please merge or close this PR if it is no longer needed?

**Comment by mishra14** [comment]
🔔 @zhili1208

**Comment by zhili1208** [comment]
this PR is not valid in current code, close it

**Pull request closed without merging**
