### PR TITLE
Remove unnecessary allocs for PackageIdentity

### LINKED ISSUE #11401: PackageSearchMetadata allocates PackageIdentity on every access to the identity property.
https://github.com/NuGet/NuGet.Client/blame/dev/src/NuGet.Core/NuGet.Protocol/Model/PackageSearchMetadata.cs#L47
image

### PR DESCRIPTION
**Pull request by erdembayar**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11401

Regression? Last working version:

## Description
Scenario: VS PMUI switch between `Browse` to `Update` tab observed with PerfView trace.

Currently for internal large project `PackageIdentity` object is causing up to 61% (**8.6GB**) allocation.
image

Here we're fixing the issue by caching calculated package identity instead of re-allocating/re-calculating every time it's requested.
After this fix it'll reduce to less than **0.1%** or **almost nothing** for all solutions I tested.

image

Since it was largest item in alloc after this fix, total allocation and GC collection pause reduced too.
**Before**:
image

**After**: Total allocation reduced about **7GB-8GB** and GC pause reduced by **1 sec**.
image

Here're more perfview measurement result before and after this change with other solutions.

Solution  | Before % | Before size | After % | After
-- | -- | -- | -- | --
Internal Large   project | 61.5 | 8.7GB | 0.1 | 5MB
Orchard | 7.3 | 40MB | 0 | 0.4MB
OrchardCore | 0.9 | 25MB | Too little, doesn't show up anymore
Orleans | 4.5 | 35MB | Too little, doesn't show up anymore
NuGet.Client | 0.7 | 126MB | Too little, doesn't show up anymore

Thank you @davkean @nkolev92 @zivkan for perfview guidance.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]

**Review by zivkan — APPROVED** [review]
>Currently for internal large project PackageIdentity object is causing up to 61% (8.6GB) allocation
> After this fix it'll reduce to less than 0.1% or almost nothing for all solutions I tested.

Goodness me, that's a big improvement!

**Comment by nkolev92** [comment]
I love that you've captured numbers. 

It's not clear what the scenario is to the average reader (I think it's solution PM UI open right?)

**Comment by erdembayar** [comment]
> I love that you've captured numbers.
> 
> It's not clear what the scenario is to the average reader (I think it's solution PM UI open right?)

Yes, it's PMUI switch between tabs (`Browse` to `Update`) scenario.

**Comment by davkean** [comment]
@erdembayar Nice!

**Pull request merged**
