### PR TITLE
Update the license list

### LINKED ISSUE #8544: Update the license list

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/8544
Regression: No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Updating the license list. 

//cc @rrelyea if we're doing a 5.3 insertion, we should consider this change. It's extremely safe :) 

## Testing/Validation

Tests Added: No  
Reason for not adding tests:  Tests already exist :) 
Validation:

### CODE REVIEW

**Review by zivkan — APPROVED** [review]

**Review by zkat — APPROVED** [review]

**Comment by loic-sharma** [comment]
@joelverhagen I believe you have to run [this script](https://github.com/NuGet/NuGet.Licenses/blob/master/src/NuGet.Licenses/license-text-extractor.ps1) and then redeploy the license service. Maybe we should document this process...

**Comment by joelverhagen** [comment]
As mentioned by @agr offline:

> licenses.nuget.org (and nuget.org accepts) only has OSI and FSF approved licenses.

Looks like it is not:

image

(source: https://spdx.org/licenses/)

**Comment by joelverhagen** [comment]
Oh, but aside from `Parity-6.0.0` and others it looks like `BSD-3-Clause-LBNL` is now OSI approved so maybe we should run this process anyway.

**Comment by rrelyea** [comment]
what is the coordination process of client changes and server changes? do we deploy to server once client has shipped? etc...

**Pull request merged**
