### PR TITLE
Errors/Warrnings: Improve NU1605 downgrade warning message

### PR DESCRIPTION
**Pull request by zhili1208**
provide better solution message to user based on user's action

Current error message for NU1605 and NU1107:
NU1605:
Detected package downgrade: 'PackageB' from 4.0.0 to 3.5.0. Reference the package directly from the project to select a different version.
  Project -> 'PackageA' 3.5.0 -> 'PackageB' 3.5.0
  Project -> 'PackageC' 4.0.0 -> 'PackageD' 4.0.0 -> 'PackageB' 4.0.0

NU1107: 

Version conflict detected for 'PackageA'. Reference the package directly from the project to resolve this issue.
  'PackageB' 3.5.0 -> 'PackageA' (= 3.5.0)
  'PackageC' 4.0.0 -> 'PackageA' (= 4.0.0)

With this change:

NU1605: 
Restore is the same.
Install/Update : 

Case 1: the project has a bad package which causes downgrade.

Detected package downgrade: 'PackageB' from 4.0.0 to 3.5.0. Dependency graph of Package 'PackageA' contains package 'PackageB' version conflict which causes downgrade, please contact package author to fix it.

 Project -> 'PackageA' 3.5.0 -> 'PackageB' 3.5.0
 Project -> 'PackageA' 3.5.0 -> 'PackageD' 4.0.0 -> 'PackageB' 4.0.0

Case 2: user try to install one packageA which require higher version of packageB, and lower version of package B is already installed from project.
Detected package downgrade: 'PackageB' from 4.0.0 to 3.5.0. The package 'PackageA' requires version '4.0.0' of 'PackageB', please uninstall package 'PackageB' or upgrade package 'PackageB' to version '4.0.0'.

Project -> 'PackageB' 3.5.0 
Project -> 'PackageA' 4.0.0 -> 'PackageD' 4.0.0 -> 'PackageB' 4.0.0

Case 3: user try to install a lower version of packageB, but one installed packageA require higher version.

Detected package downgrade: 'PackageB' from 4.0.0 to 3.5.0. The version '4.0.0' of package 'PackageB' is already installed through transitive dependency of package 'PackageA', no need to install package 'PackageB'.
Project -> 'PackageB' 3.5.0 
Project -> 'PackageA' 4.0.0 -> 'PackageD' 4.0.0 -> 'PackageB' 4.0.0

Case 4: user do update all, all pacakges are updating, two package conflict with each other.
Detected package downgrade: 'PackageB' from 4.0.0 to 3.5.0. Package 'B' causes dependency package of the Package 'A' downgrade, Install/Reference the  version '4.0.0' of package 'B' to the project 'project' to fix it.
Project -> 'PackageB' 3.5.0 
Project -> 'PackageA' 4.0.0 -> 'PackageD' 4.0.0 -> 'PackageB' 4.0.0

 
NU1107:
Version conflict detected for 'PackageA'. Install/reference 'PackageA 4.0.0' directly to project 'Project' to resolve this issue. 
Project -> 'PackageB' 3.5.0 -> 'PackageA' (= 3.5.0)
Project -> 'PackageC' 4.0.0 -> 'PackageA' (= 4.0.0)

### CODE REVIEW

**Review by jainaashish — CHANGES_REQUESTED** [review]
Before I can start with the code review, please provide the explanation of the change in PR description. What is the existing behavior and what has changed? and samples or example values of those changed.

**Comment by jainaashish** [comment]
Can you please update it as per our offline discussion?

**Comment by zhili1208** [comment]
created another PR https://github.com/NuGet/NuGet.Client/pull/2348 which is the solution per discussion with @jainaashish

**Comment by PatoBeltran** [comment]
@zhili1208 given that you opened https://github.com/NuGet/NuGet.Client/pull/2348, should we close this PR?

**Comment by nkolev92** [comment]
Closing as it's replaced by https://github.com/NuGet/NuGet.Client/pull/2348

**Pull request closed without merging**
