### PR TITLE
CentralPackageVersions_PackageVersionToPackageSpec

### LINKED ISSUE #8909: [Centrally managing NuGet packages and versions] MsBuild targets necessary to flow the CPVM information from Directory.Packages.props  to NuGet internals
The data from Directory.Packages.props will need to be converted in a dgspec. This task is for the changes needed for this path.

### PR DESCRIPTION
**Pull request by cristinamanum**
## Issue

Fixes: https://github.com/NuGet/Home/issues/8909
Regression:No  
  

## Fix
Added support for flowing the PackageVersion data to the packageSpec   

## Testing/Validation

Tests Added: Yes  
Reason for not adding tests:  
Validation:  Unit test and manual testing

### CODE REVIEW

**Review by nkolev92 — COMMENTED** [review]
In general you are missing the static graph codepaths from the work that @jeffkl did. 
Another question, should this work go to a feature branch?

**Comment by cristinamanum** [comment]
> In general you are missing the static graph codepaths from the work that @jeffkl did.
> Another question, should this work go to a feature branch?

Correct, the @jeffkl change was checked in yesterday. I will need to update the PR to consider those code paths. 
Second questions: I would prefer to not be in a feature branch but rather have small PRs in the dev branch.

**Comment by nkolev92** [comment]
>  I would prefer to not be in a feature branch but rather have small PRs in the dev branch.

I understand that, but I'd want us to be mindful about codepaths that might be active. 
Specifically, this PR will likely not be an issue cause there'll be no PackageVersions to be read, but any resolver changes probably will affect things. 

Let's discuss with @aortiz-msft & @NuGet/nuget-client

**Comment by cristinamanum** [comment]
Close this PR as a new PR (https://github.com/NuGet/NuGet.Client/pull/3198) targeting a feature branch was created.

**Pull request closed without merging**
