### PR TITLE
Show Vulnerable label in versions combobox

### LINKED ISSUE #11127: [Feature]: Show which package versions are vulnerable in the VS PMUI package details pane version dropdown
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

**Feature**

Surface which versions of a package have a vulnerability in the package details pane version dropdown like we do with deprecated versions.

**Design**

* When a version only has vulnerabilities, the string should say "(Vulnerable)"
* When a version has a vulnerability and is deprecated, the string should say "(Vulnerable, Deprecated)"
* The string should be surfaced next to vulnerable versions in all project level PMUI tabs including the Browse, Installed, and Updates tabs
* The string should be surfaced next to vulnerable versions in all solution level PMUI tabs including the Browse, Installed, Updates, and Consolidate tabs

image

Existing behavior for deprecated versions:
image

### Additional Context and Details

Successful release of this feature will require a fix to https://github.com/NuGet/Home/issues/11129 to ensure both vulnerability and deprecation strings are correctly shown in the Browse tab.

### PR DESCRIPTION
**Pull request by martinrrm**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11127

Regression? Last working version:

## Description

Added a label to the versions combobox to show when a package is Vulnerable or Vulnerable and deprecated. (Deprecated label already exists).

image

image

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception - Adding tests was getting too complicated and I think this is a simple UI change that can be validated manually.
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by donnie-msft** [comment]
@martinrrm could you try shrinking the details pane to its min size and let us know how's the wrapping? PLOC testing would be ideal, including with minimum supported screen resolution. You can be the first to try my [PLOC testing guide](https://github.com/NuGet/Client.Engineering/blob/main/docs/localization-ploc.md) (you're welcome :D)

Also, I imagine this string works fine but please test with AccessibilityInsights and Narrator to ensure 'Vulnerable' and 'Vulnerable, Deprecated' are announced appropriately.

**Comment by martinrrm** [comment]
Tested Narrator and AccessibilityInsights, both passed 🎉

**Comment by martinrrm** [comment]
image
 PLOC seems to be working

**Review by donnie-msft — APPROVED** [review]
Thanks for doing the PLOC & A11y testing. 
It'd be great if a separate PR could add tests to `DetailControlModelTests` to hit some edge cases. Ideally that would happen in 17.7 Preview 2 or 3.

**Review by jeffkl — APPROVED** [review]

**Review by jebriede — APPROVED** [review]
This is great! LGTM.

**Comment by martinrrm** [comment]
@donnie-msft Added Accessibility Insights results 
image

**Pull request merged**
