### PR TITLE
Unpin VS version used for testing

### PR DESCRIPTION
**Pull request by zivkan**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/2320

Regression? no

## Description

Let NuGet test against the latest build of VS, which is what NuGet is being inserted into.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

**Comment by donnie-msft** [comment]
@zivkan is there a reason https://github.com/NuGet/Client.Engineering/issues/2320 was created separately from https://github.com/NuGet/Client.Engineering/issues/2291 ? Perhaps the SDK change can't be reverted?
The description doesn't mention the reason why this can be reverted. Were the agents updated? Please add the details so when we revisit a similar issue in the future there's more context on the problem/solution. Thanks

**Review by kartheekp-ms — APPROVED** [review]

**Comment by jeffkl** [comment]
@donnie-msft https://github.com/NuGet/Client.Engineering/issues/2291 tracks using 17.6 on our build agents where we are running restore for our code base.  This change only affects which version of Visual Studio is installed on DartLab machines which we have control over.  The version installed on hosted build agents where we run our build is not currently under our control unfortunately...

**Review by jeffkl — APPROVED** [review]

**Comment by jeffkl** [comment]
@NuGet/nuget-client I'd like to merge this as its unblocks our CI.  Any objections?

**Comment by zivkan** [comment]
@donnie-msft in addition to what Jeff wrote, our CI has been blocked for multiple days because of the DartLab VS setup issue. But the .NET 8 SDK pinning isn't causing pipeline failures. I want to get the team (and my own PRs) unblocked.

**Comment by donnie-msft** [comment]
@zivkan & @jeffkl  Ok, so we agree this partially reverts my change tracked by 2291 (PR: https://github.com/NuGet/NuGet.Client/pull/5169). 

Can we add the "why" context for why we needed to unpin VS at this particular moment - what was the trigger? Just something informal and light can be a huge help the next time this happens: like "DartLab started failing [because of some VS Setup issue] / [and we don't know why] / [shortly after updating their images] / [other?]" and ["So this prompted us to move back to main VS "] / ["so 17.5 no longer works due to Setup issues"] in the description of this PR. 

I get that you wrote this PR because CI was "blocked", I just think it's more valuable to explain what is causing it to be blocked for future reference (and for those of us still unclear today).

**Pull request merged**
