### PR TITLE
Use System.Security.Crptography.Algorithms

### PR DESCRIPTION
**Pull request by pranavkm**
cc @ericstj \ @davidfowl

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
@pranavkm we have changed a bunch since (moved to netstandard), can you redo

**Comment by pranavkm** [comment]
Updated

**Comment by emgarten** [comment]
:shipit:

**Comment by emgarten** [comment]
@pranavkm would you merge this?

**Comment by emgarten** [comment]
NuGet/NuGet.Client@6e99ad12d0bf14a9e52111c784c5718aedca497d

**Pull request closed without merging**
