### PR TITLE
Remove references to codeplex in nuspec and update licenses.

### PR DESCRIPTION
**Pull request by yishaigalatzer**
TODO: Add nuspec and update project.json to include license and project urls to all packages https://github.com/NuGet/Home/issues/1886

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
CC @emgarten @deepakaravindr @RanjiniM

**Comment by yishaigalatzer** [comment]
ping, small easy review

**Comment by xavierdecoster** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
@yishaigalatzer Can you also fix this file: https://github.com/NuGet/NuGet.Client/blob/3b278f487bd99460a4c41386214fc1f246552907/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/ProjectFactoryTest.cs#L18?

**Comment by deepakaravindr** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
Merged through https://github.com/NuGet/NuGet.Client/commit/dac7fc827514d3b4adf53adc719f124efd5e8fa3

**Pull request closed without merging**
