### PR TITLE
add error message when packagespec is null

### PR DESCRIPTION
**Pull request by rohit21agrawal**
Fixes: https://github.com/NuGet/Home/issues/3741

CC: @emgarten @joelverhagen @alpaix

### CODE REVIEW

**Review by emgarten — CHANGES_REQUESTED** [review]
This error could occur during install or update also. The message should be more generic. 

The null checks look correct.

**Review by alpaix — APPROVED** [review]

**Comment by rohit21agrawal** [comment]
any suggestions on the message here?
@rrelyea @alpaix @joelverhagen @emgarten

**Comment by alpaix** [comment]
Whether and where an user is going to see this error?

**Comment by rohit21agrawal** [comment]
anytime during restore/install/uninstall/update - if a project returns a null pacakge spec, this error will be thrown

**Comment by alpaix** [comment]
I think project should raise generic "project not loaded error". For slightly cleaner implementation I'd suggest adding smth. like `PackageSpecProvider` that'd provide the data and throw correct exception in all cases. Thoughts?

**Review by emgarten — APPROVED** [review]

**Pull request merged**
