### PR TITLE
Fix source-build CI regression

### PR DESCRIPTION
**Pull request by MichaelSimons**
## Bug

Fixes: https://github.com/NuGet/NuGet.Client/pull/5414#issuecomment-1728636229

Regression? Yes

## Description
This fixes a regression in the source-build CI leg introduced by https://github.com/NuGet/NuGet.Client/pull/5414

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by MichaelSimons** [comment]
cc @nkolev92

**Review by jeffkl — DISMISSED** [review]

**Comment by nkolev92** [comment]
There's still some failures: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8431271&view=logs&j=cb98efd6-7062-56ef-f642-0176540bbe0a&t=d42c45d2-f6c8-5ae2-d854-abf6f8d78853. 

We should probably add the source-build status to the github checks.

**Comment by zivkan** [comment]
I created a PR to report Source Build job status to GitHub Checks: https://github.com/NuGet/NuGet.Client/pull/5422

I'm happy for someone to merge it before the normal 24 hour wait period. If that's done, then this branch can rebase to the latest dev branch, and get the benefit of having the job's result visible in the "some checks were not successful" list.

**Comment by MichaelSimons** [comment]
> There's still some failures: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8431271&view=logs&j=cb98efd6-7062-56ef-f642-0176540bbe0a&t=d42c45d2-f6c8-5ae2-d854-abf6f8d78853.

I pushed an attempted fix.  I cannot reproduce this locally so it is difficult to test.

> We should probably add the source-build status to the github checks.

That would be nice.

**Review by jeffkl — APPROVED** [review]

**Pull request merged**
