### PR TITLE
Add dotnet5.6 with net462, UAP, DNXCore50

### PR DESCRIPTION
**Pull request by ericstj**
UAP can now support the latest generation.  Additionally .NET desktop 4.6.1 is at RC and unlikely to accept any more API changes so we need to allocate a new generation for .NET 4.6.2.

Fixes https://github.com/NuGet/Home/issues/1709

/cc @anurse @yishaigalatzer @emgarten

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
We will look at this for 3.4

**Comment by ericstj** [comment]
When will that be?  We're hitting this today with API changes that are being made in CoreFx.  I can unblock the dev work with a private build, but we won't be able to consume the packages until we have this.  Just trying to understand if I need to put a hack in place or if I can wait for this to merge.

**Comment by yishaigalatzer** [comment]
Should be able to merge next week

**Comment by davidfowl** [comment]
I see we're remapping dnxcore50 here as well. We need to start on that mapping file ASAP.

/cc @anurse

**Comment by clairernovotny** [comment]
Silly question, but why is this on dotnet 5.x; when will this all switch to `netstandard` so we can get on with some sanity ;) ?

**Comment by yishaigalatzer** [comment]
I believe this was done before netstandard was concieved

**Comment by ericstj** [comment]
Yep, and we still need this merged.  We'll need to keep both dotnet and netstandard around for a little while until everything is moved over.

@yishaigalatzer now that you have a 3.4 branch can you merge this so that we can unblock work in corefx?

**Comment by yishaigalatzer** [comment]
I don't yet. monday

**Comment by ericstj** [comment]
How about now?

**Comment by yishaigalatzer** [comment]
I think now is fine @emgarten can you take this as soon as your desk is clean?

**Comment by emgarten** [comment]
NuGet/NuGet.Client@a15e8ff0c6de85eb8da995672ce4bb1751fc141d

**Comment by ericstj** [comment]
Thanks!

**Pull request closed without merging**
