### PR TITLE
Improve the minimal logging across all the commands

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug
Fixes: https://github.com/NuGet/Home/issues/4695
Regression: No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: Basic pass improving the min logging across the product. 

When restoring with min logs, there is only 1 line of logs in the average case. 

[minimalLogs.txt](https://github.com/NuGet/NuGet.Client/files/2713852/minimalLogs.txt)
[normalLogs.txt](https://github.com/NuGet/NuGet.Client/files/2713853/normalLogs.txt)
[beforeChangeMinLogs.txt](https://github.com/NuGet/NuGet.Client/files/2713854/beforeChangeMinLogs.txt)
[beforeChangeNormalLogs.txt](https://github.com/NuGet/NuGet.Client/files/2713855/beforeChangeNormalLogs.txt)

/cc @rrelyea 
@wli3

## Testing/Validation
Tests Added: Not yet. Will add some basic ones asserting the line number count.
Reason for not adding tests: 
Validation done:  Manual

### CODE REVIEW

**Review by dtivel — APPROVED** [review]
We have no test coverage affected by this change?

**Comment by nkolev92** [comment]
@dtivel 
Surprisingly nothing. 

I will add some tests asserting this once we get confirmation from customers in the issue about the details of the change.

**Review by jainaashish — APPROVED** [review]

**Comment by anangaur** [comment]
I see full path for all the project files mentioned. Can these be made relative paths? This will cut down on the text and make it more readable. For example
Replace this
```
Restore completed in 1.63 sec for Restore completed in 1.63 sec for F:\Code\NuGet\NuGet.Client\src\NuGet.Clients\NuGet.SolutionRestoreManager.Interop\NuGet.SolutionRestoreManager.Interop.csproj.
  Restore completed in 5.46 sec for F:\Code\NuGet\NuGet.Client\src\NuGet.Clients\NuGet.CommandLine\NuGet.CommandLine.csproj.
  Restore completed in 5.46 sec for F:\Code\NuGet\NuGet.Client\src\NuGet.Clients\NuGet.MSSigning.Extensions\NuGet.MSSigning.Extensions.csproj.
  Restore completed in 6.43 sec for F:\Code\NuGet\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.Common\NuGet.VisualStudio.Common.csproj.
  Restore completed in 12.14 sec for F:\Code\NuGet\NuGet.Client\src\NuGet.Clients\NuGet.Console\NuGet.Console.csproj.
```

with:
```
Restore completed in 1.63 sec for src\NuGet.Clients\NuGet.SolutionRestoreManager.Interop\NuGet.SolutionRestoreManager.Interop.csproj.
  Restore completed in 5.46 sec for src\NuGet.Clients\NuGet.CommandLine\NuGet.CommandLine.csproj.
  Restore completed in 5.46 sec for src\NuGet.Clients\NuGet.MSSigning.Extensions\NuGet.MSSigning.Extensions.csproj.
  Restore completed in 6.43 sec for src\NuGet.Clients\NuGet.VisualStudio.Common\NuGet.VisualStudio.Common.csproj.
  Restore completed in 12.14 sec for src\NuGet.Clients\NuGet.Console\NuGet.Console.csproj.
  Restore completed in 12.16 sec for src\NuGet.Clients\NuGet.PackageManagement.PowerShellCmdlets\NuGet.PackageManagement.PowerShellCmdlets.csproj.
  Restore completed in 184.5 ms for src\NuGet.Clients\NuGet.VisualStudio.Implementation\NuGet.VisualStudio.Implementation.csproj.
```

**Comment by nkolev92** [comment]
Relative to what though? We don't really keep relative paths throughout our code, so it would quite an involved change. We also have loads of scenarios where we write out paths, would we change those too?
What about when you are restoring just a project? 

I think the idea is to minimize the line count more than making the message shorter.

**Comment by anangaur** [comment]
Relative to where the command was run. Just a thought though. Otherwise looks good. I would like to do another scrub of messaging we aspire for all these modes - but lets keep that effort for later.

**Comment by nkolev92** [comment]
@anangaur 
I created an issue because we already mentioned this a few times :) 
https://github.com/NuGet/Home/issues/7679

Adjust the priority if needed. 

We need to bring it up with @rrelyea if that's something we want to address soon.

**Pull request merged**
