### PR TITLE
Change default symbol package to snupkg

### LINKED ISSUE #7815: Make snupkgs the default symbol package format for .NET 5
The default symbol package format is currently `symbols.nupkg`. We should consider if we can make `snupkg` the default for .NET 5. This would be a breaking change. See also: https://github.com/NuGet/Home/issues/7892

/cc @karann-msft @rrelyea

### PR DESCRIPTION
**Pull request by zivkan**
## Bug

Fixes: NuGet/Home#7815
Regression: No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Change default symbols package format to snupkg

## Testing/Validation

Tests Added: Yes
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Comment by loic-sharma** [comment]
Will this affect 2.1 and 2.2 .NET SDKs? See @nkolev92's comment: https://github.com/NuGet/Home/issues/7815#issuecomment-472602748

**Comment by nkolev92** [comment]
What if the debug type is not portable? 

NuGet.org's symbol server only supports portable pdbs.

**Comment by zivkan** [comment]
NuGet 5.3 will not be inserted into .NET Core SDK 2.1 or 2.2. The insertion branches are defined in `build/config.props` with the properties `CliTargetBranches`, `SdkTargetBranches` and `ToolsetTargetBranches`, which are currently pointing to master, which we probably have to update, as some of those repos have already been updated to make master target .NET 5.0. Anyway, we're only inserting into .NET Core 3.0 now.

**Comment by zivkan** [comment]
Blocked on #3014, then need to wait at least one major release.

**Pull request closed without merging**
