### PR TITLE
Cleanup unused packages from Directory.Packages.props

### PR DESCRIPTION
**Pull request by nkolev92**
# Bug

Fixes: Engineering issue

A recent thread prompted me to write a quick script to find unused PackageVersion. 
I also noticed a bunch of packages that just aren't used despite the reference existing.

## PR Checklist

- [x] Meaningful title, helpful description and a linked NuGet/Home issue
- [x] Added tests
- [x] Link to an issue or pull request to update docs if this PR changes settings, environment variables, new feature, etc.

### CODE REVIEW

**Review by jeffkl — DISMISSED** [review]

**Review by Nigusu-Allehu — DISMISSED** [review]

**Review by donnie-msft — DISMISSED** [review]
Awesome! Do you feel comfortable adding the tool to Entropy?

**Comment by nkolev92** [comment]
> Awesome! Do you feel comfortable adding the tool to Entropy?

I think calling it a tool does a lot of heavy lifting here :D 
It's a script that string matches.
I run dotnet list package to generate a file and then just did a search for each PackageVersion item on that file.

**Review by zivkan — APPROVED** [review]

**Review by kartheekp-ms — APPROVED** [review]
> I run dotnet list package to generate a file and then just did a search for each PackageVersion item on that file.

Great change. I think customers would be benefited by this type of tool/script because being aware of unused package references might help them maintain accurate SBOM.

**Comment by zivkan** [comment]
> Great change. I think customers would be benefited by this type of tool/script because being aware of unused package references might help them maintain accurate SBOM.

A Directory.Packages.props file typically contains PackageVersion items for every package used across the entire repo, but individual projects typically only use a subset of those packages. A SBOM that is based on (unused) PackageVersion items is just flawed.

**Pull request merged**
