### PR TITLE
show available package sources before Install, Restore or Update

### PR DESCRIPTION
**Pull request by xavierdecoster**
https://github.com/NuGet/Home/issues/1487

/cc @emgarten

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
:shipit: Please hold off on merging until we open up the branch for new bug fixes, and squash/rebase before merging

**Comment by emgarten** [comment]
Does this work when -Source is passed in?

**Comment by xavierdecoster** [comment]
@emgarten yes

https://github.com/NuGet/NuGet.Client/pull/8/files#diff-cfc8d23f56e864bb8cd4ddacfb9db3c4R214
https://github.com/NuGet/NuGet.Client/pull/8/files#diff-93806d26959393be604ff551638276beR113

**Comment by xavierdecoster** [comment]
@emgarten can you please give it a test pass if you feel I'm missing a scenario + squirrel if all is well? :) 

Also, guess I need to reopen against NuGet.Client.Merge branch?

**Comment by emgarten** [comment]
:shipit:

**Pull request merged**
