### PR TITLE
Remove NuGet.Core.dll references from ProjectFactory

### PR DESCRIPTION
**Pull request by toddm**
This takes out the last NuGet.Core.dll references from the pack command.

This change pulls the usings out of the class, but that makes NuGet.\* references take precedence over the ones from the usings.  That required specifying the namespace for a number of classes so that the duplicately named ones from NuGet.Core.dll were not used.

@emgarten @joelverhagen

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
I would suggest moving projectfactory out of the nuget.commandline project instead, put it in a project that has no nuget.core.dll reference

**Comment by toddm** [comment]
Right.  I should have thought of that.  Thanks.

**Comment by toddm** [comment]
After following up with Justin for advice, I'm not sure there is a project where it could be moved. ProjectFactory uses classes that aren't available XPlat to use MSBuild and load csproj project files, so it has to stay in NuGet.Clients.sln.  The NuGet.CommandLine project is the only project in NuGet.Clients.sln that seems like an appropriate home for it.

**Comment by yishaigalatzer** [comment]
We need to move all out logic out of nuget.exe even if it means build another library. Also note that msbuild is coming to xplat very soon, so we can't use that as a reason

**Comment by emgarten** [comment]
These initial changes look good to me

**Comment by emgarten** [comment]
@toddm  Is this change going in?

**Comment by toddm** [comment]
I haven't had time to take this change further and at this point I probably won't.  I could put it in as is or leave it for you or someone else to work on later.  What do you think?

**Comment by toddm** [comment]
Merging it as is.  ProjectFactory hasn't been moved to NuGet.Core.sln yet but I don't have time to do that right now.

**Pull request merged**
