### PR TITLE
Fix the concurrency issue in handling transitive central package versions

### LINKED ISSUE #10598: CPVM - Concurrency issues in the graph walking algorithm
## Details about Problem

I would like to report that the https://github.com/NuGet/NuGet.Client/pull/3493/files#diff-7457360b2ac43e8123a03561b1b5e2ca1832954941f84e44086365d26f22e5faR457-R4673 introduced some concurrency issues.

The code in question uses `ConcurrentDictionary` but it does it incorrectly.
As the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.addorupdate?view=net-5.0) says the `addValueFactory` can be called multiple times when the `AddOrUpdate` is called simultaneously on different threads. In consequence the `_toBeProcessedTransitiveCentralPackageVersions.Enqueue(centralPackageVersionDependecy);` can be called multiple times for the same name of dependency.

Also the documentation says that `updateValueFactory` is called outside of the locking mechanism of `ConcurrentDictionary` thus extra locking mechanism would be needed to make it thread safe.

## Repro steps and/or sample project

https://github.com/NuGet/NuGet.Client/compare/dev...marcin-krystianc:marcink-20210224-ConcurrencyIssue

### PR DESCRIPTION
**Pull request by marcin-krystianc**
## Bug

Fixes: https://github.com/NuGet/Home/issues/10598

Regression? - introduced by https://github.com/NuGet/NuGet.Client/pull/3493

## Description
As the initial report describes, the `ConcurrentDictionary` class was used incorrectly so it was possible that the `_toBeProcessedTransitiveCentralPackageVersions.Enqueue(centralPackageVersionDependecy)` was called multiple times for the same name of dependency.
By switching to regular `Dictionary` and using simple locking mechanism this bug is eliminated. 

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] Automated tests added (With changes to the `DependencyProvider` the `CentralTransitiveDependency_IsNotRejected_If_NotAllParentsAreRejected` would fail without changes to the `TransitiveCentralPackageVersions`).

- **Documentation**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
Nice catch. 

However, this is not a currently exercised codepath due to https://github.com/NuGet/NuGet.Client/pull/3719/.

I am willing to accept this change at this point because the motivation is sound and nothing bad stands out.

**Comment by nkolev92** [comment]
btw, please fill out the template checkboxes :)

**Comment by marcin-krystianc** [comment]
> However, this is not a currently exercised codepath due to #3719.

I believe there is an intent to bring the transitive pinning back (see https://github.com/NuGet/Home/issues/10389).

> btw, please fill out the template checkboxes :)

Done. It was a useful exercise because it motivated me to find a good way of enabling concurrency tests of the graph walking algorithm.

**Comment by marcin-krystianc** [comment]
There were some failing status checks on the `7aa4e82`  commit. I've run the `build.ps1` script locally and all the tests passed, so I've updated the branch to get fresh CI run.

**Review by erdembayar — APPROVED** [review]

**Comment by nkolev92** [comment]
Thanks for the contribution @marcin-krystianc!

**Pull request merged**
