### PR TITLE
Replacing Foreach with For loop to avoid GetEnumerator() api

### PR DESCRIPTION
**Pull request by jainaashish**
~500mb of memory was allocated for Enumerator[NuGet.DependencyResolver.GraphNode`1[NuGet.DependencyResolver.RemoteResolveResult]] and the main issue here is GetEnumerator() since this code path is inside 3 layers nested while/foreach loop so it tries to load it for 100s of 1000 times which results in this memory allocation. Ideal solution is remove GetEnumerator calls through replacing ForEach with For loops which will iterate based on index instead of getting iterator through Enumerator.

Fixes https://github.com/NuGet/Home/issues/4667

@rrelyea @DoRonMotter

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]

**Review by zhili1208 — APPROVED** [review]

**Comment by mishra14** [comment]
@jainaashish : How much improvement are we getting with this change?

**Comment by jainaashish** [comment]
@mishra14 As i mentioned in the PR description, memory allocation will be reduced by 500MB in that specific customer repro which was allocated due to GetEnumerator()...

**Comment by mishra14** [comment]
@jainaashish : I see i thought the original allocation was 500 megs, but I didnt realize that you managed to reduce all 500 megs there! 🎉 🚢

**Review by mishra14 — APPROVED** [review]

**Review by emgarten — APPROVED** [review]
🏇 🚀

**Pull request merged**
