### PR TITLE
fixed https://github.com/NuGet/Home/issues/1284

### PR DESCRIPTION
**Pull request by zhili1208**
https://github.com/NuGet/Home/issues/1284
fix install issue, just create the file and add it to project, no need to create it in TFS

### CODE REVIEW

**Comment by emgarten** [comment]
Is this handled automatically by Visual Studio 2015? Or why isn't this needed anymore?

**Comment by zhili1208** [comment]
Yes, this will be handled automatically by VS, this code add file to TFS twice and get TFS error

**Comment by emgarten** [comment]
Looks fine to me, I think @deepakaravindr should take a look, he implemented a lot of this originally.

**Comment by yishaigalatzer** [comment]
can you take over this one @skofman1 ? validate and merge

**Pull request closed without merging**
