### PR TITLE
Changed english resource MsbuildPathNotExist to correctly describe th…

### LINKED ISSUE #12461: Confusing error message for -MSBuildPath argument in the English resource file of the Nuget.CommandLine client.
### NuGet Product Used

NuGet.exe

### Product Version

nuget.exe v.6.4.0.123

### Worked before?

_No response_

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Description:
When the -MsBuildPath doesn't exist the command line returns an error saying that the directory "doesn't not exist". Which is confusing since the error stems from a Directory.Exists() == false check. 

Reproduce:
1. Execute the restore command and specify an non-existent path in the -MSBuildPath argument

Expected:
A well formed sentence explaining that the path does not exists

Actual:
The sentence returned contains the double negative "doesn't not exist"

### Verbose Logs

```shell
nuget.exe restore testProject.sln -MsBuildPath 'c:\some_non_existent_path'
Using Msbuild from 'c:\some_non_existent_path'
MSBuildPath : c:\some_non_existent_path doesn't not exist.
```

### PR DESCRIPTION
**Pull request by atamagaii**
## Bug

Fixes: https://github.com/NuGet/Home/issues/12461

Regression? Last working version: Not a regression. This bug has been in place since the initial commit (6ca09885f073106514d93d109bf7ecc2887d1588) of the MsBuildPath option for the restore command.

## Description

The code returns an error message when 'Directory.Exists(msbuildPath)' is false. I updated the message to reflect what is happening during that check by changing...
'doesn't not exist'
to
'does not exist'

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [x] Documentation PR or issue filled
  - https://github.com/NuGet/Home/issues/12461
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by atamagaii** [comment]
@dotnet-policy-service agree

**Review by erdembayar — DISMISSED** [review]

**Review by nkolev92 — DISMISSED** [review]

**Comment by kartheekp-ms** [comment]
Thank you for the contribution.

Couple of tests are failing because of string mismatch between expected and actual. Please fix the string mismatch error and push the new commit so that we can rerun CI?

https://github.com/NuGet/NuGet.Client/blob/f49ca00e27297fe7b4b82a2557d5b0caad907a06/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetRestoreCommandTest.cs#L597

https://github.com/NuGet/NuGet.Client/blob/f49ca00e27297fe7b4b82a2557d5b0caad907a06/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs#L4377

**Review by jeffkl — DISMISSED** [review]

**Comment by jeffkl** [comment]
I've pushed a commit to update the unit tests

**Review by jeffkl — DISMISSED** [review]
Thank you for the contribution!

**Comment by nkolev92** [comment]
@jeffkl there are still some test failures

**Comment by atamagaii** [comment]
There were a couple extra spaces that I needed to remove that I forgot to check in.

**Review by jeffkl — APPROVED** [review]

**Review by zivkan — APPROVED** [review]

**Pull request merged**
