### PR TITLE
Update VSSDK from 15.1 to 15.9

### PR DESCRIPTION
**Pull request by PatoBeltran**
## Bug
Fixes: Prerequisite of https://github.com/NuGet/Home/issues/2345

## Fix
Details: Updating the VSSDK package from 15.1 to 15.9 and making sure everything behaves the same way.

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
you can merge it for now
and fix it later if/when the SDK team reaches out with more information on what/how it changed.
Just verify that VSIX post and pre sdk change are the same

**Comment by PatoBeltran** [comment]
@nkolev92 the only difference in content is that after this change `Lucene.Net.pdb` is included in the VSIX.

**Comment by PatoBeltran** [comment]
@nkolev92 updated the PR to exclude pdb from source items, therefore the content in the vsix after this PR is exactly the same as the one before.

**Comment by nkolev92** [comment]
Yeah, looks good. 

pdbs don't belong in the VSIX.

**Pull request merged**
