### PR TITLE
Rename packageNamespaces to packageSourceMapping, namespace to package and id to pattern

### LINKED ISSUE #11205: [DCR]: Rename packageNamespaces feature to packageSourceMapping
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### Current Behavior

Namespaces configuration currently can be configured as follows

``` xml
<packageNamespaces>
    <packageSource key="nuget.org">
      <namespace id="*" />
    </packageSource>
    <packageSource key="contoso.com">
      <namespace id="Contoso.*" />
    </packageSource>
</packageNamespaces>
```

### Desired Behavior

Namespaces configuration should be as follows.

1. Rename `packageNamespaces` to `packageSourceMapping`
2. Rename `namespace` to `package`
3. Rename `id` to `pattern`

```xml
<packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <packageSource key="contoso.com">
      <package pattern="Contoso.*" />
    </packageSource>
</packageSourceMapping>
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kartheekp-ms**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11205

Regression? Last working version:

## Description

Namespaces configuration currently can be configured as follows

``` xml
<packageNamespaces>
    <packageSource key="nuget.org">
      <namespace id="*" />
    </packageSource>
    <packageSource key="contoso.com">
      <namespace id="Contoso.*" />
    </packageSource>
</packageNamespaces>
```

Namespaces configuration should be as follows.

1. Rename `packageNamespaces` to `packageSourceMapping`
2. Rename `namespace` to `package`
3. Rename `id` to `pattern`

```xml
<packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <packageSource key="contoso.com">
      <package pattern="Contoso.*" />
    </packageSource>
</packageSourceMapping>
```

**NOTE** - I made required changes to the product code to accept new settings. There are so many types and variables in the source code where `Namespaces`  word has been used. I will create follow-up PRs soon by renaming them, but those changes won't impact product functionality.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] Automated tests added - Relying on the existing tests.
  
- **Documentation**
  
  - [x] Documentation PR or issue filled - https://github.com/nuget/client.engineering/issues/1031

### CODE REVIEW

**Comment by nkolev92** [comment]
We're still having discussions, I'm trying to change `package prefix` to `package value`, so something like:

`PackageSourceMapping -> source = key -> package value` or `PackageSourceMapping -> packageSource = key -> package value`

**Comment by nkolev92** [comment]
We're going with:
`PackageSourceMapping -> packageSource = key -> package pattern`


can you please update that? Thanks.

**Review by nkolev92 — APPROVED** [review]
LGTM. 

Let's create an issue for renaming the types. 

I'm not worried if the type naming doesn't make it in P4.

**Comment by kartheekp-ms** [comment]
I did a quick test by following below steps before merging this PR.

1. Install a local build NuGet.Tools VSIX from PR branch in VS.
2. Updated configuration to reflect latest changes in the dogfooding branch https://github.com/NuGet/NuGet.Client/tree/dev-kartheekp-ms-dogfood-namespaces
3. Opened solution from dogfooding branch https://github.com/NuGet/NuGet.Client/tree/dev-kartheekp-ms-dogfood-namespaces branch in VS.
4. VS restored successfully.

**Pull request merged**
