### PR TITLE
Revert: Improve MSBuild SDK resolver by parsing global.json with System.Runtime.Serialization.Json #3157

### LINKED ISSUE #9098: Nuget SDK resolver no longer handles global.json files with comments
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
MSBuild 16.5.0-preview-20059-01+86d9494e4

NuGet version (x.x.x.xxx):
Whichever binaries ship with MSBuild 16.5.0-preview-20059-01+86d9494e4

OS version (i.e. win10 v1607 (14393.321)): N/A

Worked before? If so, with which NuGet version: Yes. Looks like a regression due to NuGet/NuGet.Client#3157

## Detailed repro steps so we can see the same problem

1. Add a global.json with the following content:
```
{
  // Defines version of MSBuild project SDKs to use
  // https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017#how-project-sdks-are-resolved
  "msbuild-sdks": {
    "Microsoft.Build.Traversal": "2.0.19",
  }
}
```

2. Add a project:
```
<Project Sdk="Microsoft.Build.Traversal" />
```

3. msbuild

This error shows, indicating the Nuget SDK resolver did not find the SDK:
```
<project file> : error : C:\Program Files\dotnet\sdk\3.1.200-preview-014883\Sdks\Microsoft.Build.Traversal\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
```

Removing the comments in global.json fixes the issues.

This worked with older versions of the NuGet SDK resolver.

### PR DESCRIPTION
**Pull request by jeffkl**
## Bug

Fixes: https://github.com/NuGet/Home/issues/9098
Regression: Yes
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Reverted https://github.com/NuGet/NuGet.Client/pull/3157 and added unit tests to make sure this doesn't regress again.

## Testing/Validation

Tests Added: Yes
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Review by dtivel — APPROVED** [review]
Thanks for adding tests.  That's great.

Don't forget to update the PR title to accurately reflect the PR's intent.

**Review by nkolev92 — APPROVED** [review]
You can consider keeping your test environment changes :)
Specifically your tests could still be using NuGet's infra.

**Comment by jeffkl** [comment]
> You can consider keeping your test environment changes

I will send a follow up PR to remove the TestEnvironment class as a separate commit to expedite getting this in the next build.

**Comment by nkolev92** [comment]
Sounds good. 
Feel free to merge when green, but Monday is also fine afaik.

**Pull request merged**
