### PR TITLE
Remove unused writeLockFile field \ property

### PR DESCRIPTION
**Pull request by pranavkm**
Rename RestoreGraph to RestoreTargetGraph to match type name

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @joelverhagen \ @emgarten

**Comment by pranavkm** [comment]
Our build's failed a couple of times with the lock file being locked by another process. But it looks like it's coming from `dotnet build` and not restore:

```
Project AntiforgerySample (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling AntiforgerySample for .NETCoreApp,Version=v1.0
log  : Writing lock file to disk. Path: \a6e561eeb4ed13a7\Diagnostics\samples\DatabaseErrorPageSample\project.lock.json
log  : Writing lock file to disk. Path: \a6e561eeb4ed13a7\Diagnostics\src\Microsoft.AspNetCore.Diagnostics.Abstractions\project.lock.json
The process cannot access the file '\a6e561eeb4ed13a7\.packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-preview2-21053\netcoreapp1.0\project.lock.json' because it is being used by another process.
\dotnet\dotnet.exe compile-csc @\Antiforgery\samples\AntiforgerySample\obj\Release\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
```

In the meanwhile I ran into some potential cleanup work.

**Comment by emgarten** [comment]
Thanks @pranavkm! I'll merge this :shipit:

**Comment by rrelyea** [comment]
Can you please create an issue and link it with the commit. We're trying to avoid commits without issues describing the reason for the work.

**Comment by emgarten** [comment]
Fixes https://github.com/NuGet/Home/issues/3243

**Pull request closed without merging**
