### PR TITLE
Remove nugetrecommendpkgs check and allow package manager to show packages when recommender is disabled.

### PR DESCRIPTION
**Pull request by birgithi**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/1750

The relevant internal issues:

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576672
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1527078
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1547720

Regression? Last working version:
No

## Description

Removed check for nugetrecommendpkgs flight. 
Allow Package Manager to continue when the package recommender is not found.
## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 
Tested manually

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by erdembayar — DISMISSED** [review]

**Comment by nkolev92** [comment]
@aortiz-msft 
Do we want to make the recommender the default experience or do we need a feature flag?

**Comment by nkolev92** [comment]
@birgithi ~I've edited the description to only include the `delete the experiment` issue as there's other work that'd be fixing the other 2 issues.~

I have also kicked off another CI run after resolving the conflict. 
I will merge once the CI passes.

**Review by nkolev92 — APPROVED** [review]

**Comment by nkolev92** [comment]
Actually after reviewing the change it does the fix the `recommender breaks the PM UI` https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1527078, so I added the issues back.

**Comment by nkolev92** [comment]
There's side work to mark the recommender not removable from VS.

I think the try/catch to ensure that the PM UI is not impacted by failures is ok.

**Review by donnie-msft — APPROVED** [review]

**Pull request merged**
