### PR TITLE
Fix broken logo image

### LINKED ISSUE #11390: Fix broken NuGet logo image
NuGet logo on NuGet.Client repo is broken.

### PR DESCRIPTION
**Pull request by mairaw**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11390

Regression? Last working version:

## Description
NuGet logo on NuGet.Client repo is broken.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

**Comment by erdembayar** [comment]
@mairaw 
Please create tracking issue at NuGet/Home and fill out template.
image

**Comment by mairaw** [comment]
@erdembayar can you do this part? Not sure how to answer some of those required questions for this simple fix.

**Comment by nkolev92** [comment]
The changes are technically described in the PR. 
I've checked the last 2 boxes about the tests. 

I think we're just missing an issue.

it's our policy that every commit has a respective issue.

**Comment by mairaw** [comment]
Sure @nkolev92 but the issue template has some required fields that are not applicable to this simple change and I don't know how to fill that out. Should you have a N/A for this question or do I just pick a random one?
image

**Comment by nkolev92** [comment]
Seems like @erdembayar handled it and created an issue. 

Using the blank template is ok for issues that are not necessarily related to anything already listed.

**Review by nkolev92 — APPROVED** [review]

**Pull request merged**
