### PR TITLE
Add support for adding projects concurrently in DependencyGraphSpec using synchronization lock

### LINKED ISSUE #9002: DependencyGraphSpec should support adding projects concurrently
## Details about Problem

The [DependencyGraphSpec](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs) object uses a standard collection object as a backing collection.  This makes it impossible to use it in a parallel loop or multiple threads.  It should use a concurrent collection instead.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Any

NuGet version (x.x.x.xxx): Any

dotnet.exe --version (if appropriate): any

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.
2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

### PR DESCRIPTION
**Pull request by erdembayar**
## Bug

Fixes: [Nuget/Home#9002](https://github.com/NuGet/Home/issues/9002)

Regression: No  

## Fix

Details: 
The [DependencyGraphSpec ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L241) object uses a standard collection object as a backing collection. This makes it impossible to use it in a parallel loop or multiple threads. It should use a concurrent collection instead. 
I have 2 competing idea for this task.
Here is 1st one which uses synchronization lock.
There are no native framework concurrent SortedSet nor concurrent SortedDictionary, I just decided to wrap with lock object for simplicity.
Of course I can use actual concurrent dictionary for this purpose, but we need to sort by key before consume. I have separate [PR#3593 ](https://github.com/NuGet/NuGet.Client/pull/3593) for that idea.
Compare with other one this one is more simple to understand.

## Testing/Validation

Tests Added: No  
Reason for not adding tests:  There are already many unit tests covering this code paths.
Validation:  Manual testing.

### CODE REVIEW

**Comment by erdembayar** [comment]
Code reviews please? @zivkan  @nkolev92 @dtivel

**Comment by nkolev92** [comment]
I think https://github.com/NuGet/NuGet.Client/pull/3593 is better than this approach.

**Comment by erdembayar** [comment]
> I think #3593 is better than this approach.

Thank you for your input.

**Comment by erdembayar** [comment]
I reopened this PR due to other PR had more issues.

**Comment by zivkan** [comment]
So, this PR looks a lot like it's moving the syncronisation lock out of the static graph restorer and putting in here (well, except this PR forgot to remove it from the static graph restorer). To me, this raises a few questions:

* Is the only goal to move the lock out of static graph into the DGSpec class?
  * if so, this is going to make all other restores slower, since they need to get locks for circumstances that will never need it

* If we're planning on making other restores do PackageSpec creation in parallel, we can either:
  * copy the static graph restore pattern and have each of them lock around the add methods. No changes to the DGSpec class needed.
  * go down the immutable data type route that I mentioned in the other PR.
  * do this change
    * if we want to eventually do the immutable data type option, is there much benefit to this change, given that static graph implemented its own locking in about 5 lines of code?

I don't have an opinion on these questions yet, I need more time to think. On one hand this implementation looks just about complete. On the other hand, since it's regarding parallel programming, I need to have a good hard think about all the potential multi-threaded timing bugs that might be possible, as part of the PR review. If VS restore, msbuild restore, etc, all do like static graph restore and use their own lock, it's much easier to make a guess about whether or not there's a potential multi-threaded timing design bug.

**Comment by nkolev92** [comment]
> If we're planning on making other restores do PackageSpec creation in parallel, we can either:

We want to parallelize VS next, that's Erick's next issue/PR https://github.com/NuGet/Home/issues/9200. 

Another approach would be to create a threadsafe list of PackageSpec + restore at creation time and keep the dg spec implementation as is.

**Comment by erdembayar** [comment]
> > If we're planning on making other restores do PackageSpec creation in parallel, we can either:
> 
> We want to parallelize VS next, that's Erick's next issue/PR [NuGet/Home#9200](https://github.com/NuGet/Home/issues/9200).
> 
> Another approach would be to create a threadsafe list of PackageSpec + restore at creation time and keep the dg spec implementation as is.



> So, this PR looks a lot like it's moving the syncronisation lock out of the static graph restorer and putting in here (well, except this PR forgot to remove it from the static graph restorer). To me, this raises a few questions:
> 
> * Is the only goal to move the lock out of static graph into the DGSpec class?
>   
>   * if so, this is going to make all other restores slower, since they need to get locks for circumstances that will never need it
> * If we're planning on making other restores do PackageSpec creation in parallel, we can either:
>   
>   * copy the static graph restore pattern and have each of them lock around the add methods. No changes to the DGSpec class needed.
>   * go down the immutable data type route that I mentioned in the other PR.
>   * do this change
>     
>     * if we want to eventually do the immutable data type option, is there much benefit to this change, given that static graph implemented its own locking in about 5 lines of code?
> 
> I don't have an opinion on these questions yet, I need more time to think. On one hand this implementation looks just about complete. On the other hand, since it's regarding parallel programming, I need to have a good hard think about all the potential multi-threaded timing bugs that might be possible, as part of the PR review. If VS restore, msbuild restore, etc, all do like static graph restore and use their own lock, it's much easier to make a guess about whether or not there's a potential multi-threaded timing design bug.


> > If we're planning on making other restores do PackageSpec creation in parallel, we can either:
> 
> We want to parallelize VS next, that's Erick's next issue/PR [NuGet/Home#9200](https://github.com/NuGet/Home/issues/9200).
> 
> Another approach would be to create a threadsafe list of PackageSpec + restore at creation time and keep the dg spec implementation as is.

Yes, next follow is [#PR3605](https://github.com/NuGet/NuGet.Client/pull/3605) which is using TPL for parallelization. 
@zivkan Give us your thought.

**Comment by zivkan** [comment]
Here's my understanding:

|Approach|DGSpec/PackageSpec classes|call site|
|----|----|----|
|Make DGSpec (& PackageSpec?) properly thread-safe.| Basically what this PR is doing. PR author and reviewers need to ensure no multi-threading timing issues exist, and all future modifications to this class have to keep the same promise.| Callers can call `AddProject` and `AddRestore` without concern, even in parallel code.|
|Maintain generic .NET convention that instance methods are not thread-safe.| No changes to DGSpec or PackageSpec classes.| Multiple approaches are possible (see below), but it will be the caller's responsibility to not call instance methods in parallel. Any code that does can potentially break.|
|Make DGSpec (& PackageSpec?) immutable or read-only.| Needs changes to the API + implementation. | Multiple approaches are possible (see below). But the API will not allow for incorrect usage.|

In the cases where the caller is responsible for synchronizing their parallel usage, there are multiple options. At a high level:

#### Lock the DGSpec instance

MSBuildStaticGraphRestore already implements this, and it's only 3 lines longer than if the DGSpec was thread-safe:

```cs
lock (dgSpec)
{
  dgSpec.AddProject(project);
}
```

#### Use a concurrent collection

Uses more lines of code than above. If adding to the collection is faster than DGSpec's `AddProject` or `AddReference`, then there will be less thread blocked due to the lock.

```cs
var concurrentBag = new ConcurrentBag<PackageSpec>();

Parallel.ForEach(projects,
    project =>
    {
      var projectSpec = GetPackageSpec(project);
      concurrentBag.Add(projectSpec);
    });

foreach (var projectSpec in concurrentBag)
{
  dgSpec.AddProject(projectSpec);
}
```

#### Parallel PackageSpec tasks, single-threaded task completion

Run methods that return `Task<PackageSpec>` in parallel, but this parallel work does not call the dgSpec directly. Instead, after the `Task` completes, something else, that runs single-threaded, can call the DGSpec.

Using TPL Dataflow would look something like this:

```cs
var projectToPackageSpecBlock = new TransformBlock<Project, PackageSpec>(...); // max concurrency > 1
var addToDGSpecBlock = new ActionBlock<PackageSpec>( projectSpec => dgSpec.AddProject(projectSpec, ...); // max concurrency == 1
var link = projectToPackageSpecBlock.LinkTo(addToDGSpecBlock);
```

or rolling our own scheduling implementation:

```cs
var tasks = new List<Task<PackageSpec>>();

foreach (var project in Projects)
{
  tasks.Add(GetPackageSpecFromProject(project));
}

while (tasks.Count > 0)
{
  var finishedTask = await Task.WhenAny(tasks);
  tasks.Remove(finishedTask);
  dgSpec.AddProject(finishedTask.Result);
}
```

----

Immutable types and functional programming is trendy, so it sounds cool and fun, but will take the longest time to implement, plus will require public API changes (but for very good reason). 

This PR seems to make DGSpec thead-safe, but I didn't take a careful look at all the methods yet, meaning it's expensive to code-review because to do it right, we need to consider thread-safety. If the rest of our codebase makes assumptions that this class is thread-safe, it means all future changes to this class must also be thread-safe, so it adds ongoing technical debt to make sure we don't accidentally introduce bugs. Maybe that's acceptable.

But some of the options for making the call-site responsible for thread-safety is easy to review and the MSBuildStaticGraphRestore pattern is only 3 extra lines per call-site. If we wanted to use one of the other patterns (anything that returns `Task<PackageSpec>`), we might be able to write a generic, reusable method. Something like `public Task<DGSpec> CreateDGSpecFromProjectsInParallel<T>(IEnumerable<T> projects, Func<T, PackageSpec> delegate)`, but I think this will be easier to review the first time, and have lower risk and cost in case of modifications in the future, than the make-DGSpec-thread-safe option.

Therefore, I'd suggest that this PR isn't needed. What do others think?

**Comment by erdembayar** [comment]
@zivkan I am ok with abandoning this PR. 
I added 3 lines of locks in https://github.com/NuGet/NuGet.Client/pull/3605
I still get performance improvement so I'm good with this approach.
Please check.

**Comment by erdembayar** [comment]
> @zivkan I am ok with abandoning this PR.
> I added 3 lines of locks in #3605
> I still get performance improvement so I'm good with this approach.
> Please check.

@nkolev92  Please give your input.

**Comment by nkolev92** [comment]
Sounds good to me. 
Thank you both @zivkan @erdembayar

**Comment by erdembayar** [comment]
We're going to add 3 lines of sync lock wherever needed and not going to merge this PR.

**Pull request closed without merging**
