### PR TITLE
Add two test cases for Web Site Projects

### PR DESCRIPTION
**Pull request by v-luzh**
## Description
**Add two test cases：**
1.InstallPackageToWebSiteFromUI: Install particular package to C# ASP Web Site Project from PM UI.
2.UpdateWebSitePackageFromUI: Update package for C# ASP Web Site Project in PM UI.

- Updated the "...\build\tests.dev17.vsconfig" to install Web Site Projects for testing.
- We created a bulk of C# ASP Web Site Projects with Theory.
- The test cases were added into the end of the ...\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetUITestCase.cs file.

## PR Checklist

- [x] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
- [x] Automated tests added
1.InstallPackageToWebSiteFromUI
2.UpdateWebSitePackageFromUI

### CODE REVIEW

**Comment by nkolev92** [comment]
Restarting the build as the last build was affected by CI issues.

**Comment by v-luzh** [comment]
Hi @nkolev92, thanks for helping to restart. 6.4.0.662 still failed at "cannot find project 'WebSite/WebSiteWCF'" as below.

##[error]RunMessage : [xUnit.net 00:01:34.05] NuGet.Tests.Apex.NuGetUITestCase.InstallPackageToWebSiteFromUI(**projectTemplate: WebSite**, projectName: "WebSite", targetFramework: V48, packageName: "Log4Net.Async", packageVersion: "2.0.3") [FAIL] 
RunMessage : [xUnit.net 00:01:34.05] Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the '**WebApplication46.zip**' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.8'. 

##[error]RunMessage : [xUnit.net 00:01:51.37] NuGet.Tests.Apex.NuGetUITestCase.InstallPackageToWebSiteFromUI(projectTemplate: **WebSiteWCF**, projectName: "WebSiteWCF", targetFramework: V48, packageName: "log4net.Ext.Json", packageVersion: "2.0.9.1") [FAIL] 
RunMessage : [xUnit.net 00:01:51.37] Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the '**WebWCFService.zip**' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.8'. 

However, actually we can find theses templates in the WebSite template-list when writing the cases as below. Don't know why they cannot be found when running the test.
image

**Comment by nkolev92** [comment]
At compile time all test cases are available. 

At runtime, the needed components need to be installed.
Are the tests passing locally for you?

It seems to like you're adding the installation component. 

The easiest would be to install VS with the config that's checked and then see if the tests pass locally then. 

cc @NuGet/nuget-client in case anyone has a better idea.

**Comment by v-luzh** [comment]
Hi @nkolev92, yes, I update the ...\tests.dev17.vsconfig in this PR, and seems it works as below. These workloads should belong to AdditionalWebProjectTemplates marked green.
image

The build failing root cause seems the project creations between running automation and creating manually **do not** match. Maybe we should close this PR, rebase our local branch, try the template in above WebSite template list one by one and submit another PR. But we don't know if the rest template works. In our new automation test cases, only the "WebSiteEmpty" and "WebSiteDynamicDateEntityFramework" can be created successfully, and the corresponding case passed.

**Pull request closed without merging**
