### PR TITLE
Remove unneeded allocations parsing assets file

### LINKED ISSUE #11648: Remove unneeded allocations when parsing assets file

### PR DESCRIPTION
**Pull request by davkean**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11648

Regression? Last working version:

## Description

Remove unneeded allocations parsing assets file

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception - No functional changes.
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]

**Comment by nkolev92** [comment]
If you name your branch `dev-*`, something like `dev-davkean-removeUnneededAllocations` it will auto trigger the build.

**Review by erdembayar — APPROVED** [review]

**Review by kartheekp-ms — APPROVED** [review]
I found another code path where a similar fix can be applied. The fix is to replace the `line no:712` with `return new List<IAssetsLogMessage>(0); ` and replace `line no: 715` with `var items = new List<IAssetsLogMessage>(json.Count);`

https://github.com/NuGet/NuGet.Client/blob/b76bf48337114102098d31c80271589feb0d28eb/src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs#L708-L725

**Review by jeffkl — APPROVED** [review]

**Comment by jeffkl** [comment]
I restarted the failing test job

**Comment by davkean** [comment]
@[kartheekp-ms](https://github.com/kartheekp-ms) I fixed that one too.

**Pull request merged**
