### PR TITLE
Move NuGet.Core credential adapters to NuGet.CommandLine and cut ties in VSIX

### PR DESCRIPTION
**Pull request by joelverhagen**
🔪 `NuGet.Core` 🔪 

Fixes https://github.com/NuGet/Home/issues/3671.
1. Moved NuGet.Core credential adapters to `NuGet.CommandLine` since it's the only consumer.
2. Removed VSIX code that depends on NuGet.Core.

Next step is https://github.com/NuGet/Home/issues/3645.

I ran the CI as well as manually verified:
1. basic auth
2. VSTS authentication
3. Reading NuGet.Config
4. Writing NuGet.Config
5. PMC authentication

/cc @zhili1208 @emgarten @alpaix @pspill

### CODE REVIEW

**Comment by emgarten** [comment]
Yay! :shipit: 🎉 🎈 🎉

**Comment by joelverhagen** [comment]
Any other thoughts on validation? This PR was easy... TOO easy 👻. The code in the VSIX seems to be dead...

**Comment by emgarten** [comment]
@joelverhagen I'm not sure on validation. I know I tried to do this same thing previously and it wasn't this easy. Maybe the recent credential provider change improved things.

**Review by alpaix — APPROVED** [review]
👏

**Pull request merged**
