### PR TITLE
Fix NuGet/Home#3093

### PR DESCRIPTION
**Pull request by AndreyAkinshin**

### CODE REVIEW

**Comment by joelverhagen** [comment]
Linking related issue: https://github.com/NuGet/Home/issues/3093

**Comment by rrelyea** [comment]
Let's discuss the need for this (or not) in the issue: https://github.com/NuGet/Home/issues/3093

**Comment by emgarten** [comment]
This could use Directory.EnumerateFiles(..).Any() instead of Directory.GetFiles, getting the full list isn't needed as you pointed out.

Catching access exceptions will actually give worse performance here in some scenarios. After the initial check the restore will discover the complete set of project.json and during that check access exceptions are not ignored, so this will take longer to hit the same failure point. For scenarios where there are zero project.json files this change would continue searching where as the current code exits on the first error.

Access exceptions cannot be completely ignored since it will make it difficult to track down problems. Example: A folder has a sub folder that restore cannot access with a project.json and project.lock.json file. Restore will run without failing or restoring this, then when a build that does have access to the folder occurs it will build using the old lock file, potentially without errors. However the build output could be missing the latest version of dependency packages since restore didn't run. The user would only know there is a problem if they manually checked the build output or hit runtime issues.

**Comment by AndreyAkinshin** [comment]
> This could use Directory.EnumerateFiles(..).Any()

Done. Now it also uses `Directory.EnumerateDirectories` instead of `Directory.GetDirectories`.

> Access exceptions cannot be completely ignored

I agree. However, `nuget.exe` shouldn't throw an incomprehensible exception, it should print a user-friendly message like _"Unfortunately, we don't have an access to the directory <FullPathToDirectory>, bla, bla, bla..."_

What do you think?

**Comment by emgarten** [comment]
> nuget.exe shouldn't throw an incomprehensible exception, it should print a user-friendly message

Absolutely. Have you tried without `-verbosity detailed`? It should show just the exception message, or are you saying that is also unfriendly?

**Comment by AndreyAkinshin** [comment]
Ok, I run `nuget restore` from the home directory. The result:

```
Access to the path 'c:\Users\akinshin\AppData\Local\Application Data' is denied.
```

Here I don't have an idea why it should affect restore. I suggest to add one more sentence like "There is no project.json in the root folder, so, we try to find it in subfolders".

I can also remove try-catch block from my PR (but keep the "lazy" approach because we don't need check all the files in subtree). Will it be ok?

**Comment by emgarten** [comment]
> I can also remove try-catch block from my PR (but keep the "lazy" approach because we don't need check all the files in subtree). Will it be ok?

That would be great. You could catch the unauthorized exception and wrap the error message with another string as you are suggesting, I think that would be helpful. It's just catching and ignoring the exception that is an issue.

**Comment by AndreyAkinshin** [comment]
Done.
@emgarten, please, review.

**Comment by emgarten** [comment]
@AndreyAkinshin you rock! :smile: Thanks for the PR, I'll get this merged

**Comment by rrelyea** [comment]
Not sure why my earlier email reply did not show up here....

Can you make that something like:
No solution, project file or project.json file find in current direction. Searching for project.json files in subfolders

**Comment by AndreyAkinshin** [comment]
@rrelyea, now we have the following two messages (the second one is mine):

``` xml
  <data name="Error_UnableToLocateRestoreTarget" xml:space="preserve">
     <value>The folder '{0}' does not contain an msbuild solution, packages.config, or project.json file to restore.</value>
   </data>
  <data name="Error_UnableToLocateRestoreTarget_Because" xml:space="preserve">
    <value>Failed to find an msbuild solution, packages.config, or project.json file in the folder '{0}' because {1}</value>
  </data>
```

Which message do you want to update?

**Comment by rrelyea** [comment]
My response was to the message where you referred to the following message:
"There is no project.json in the root folder, so, we try to find it in subfolders"
Perhaps I misunderstood, but I thought that the message I provide above covered that, plus the root folder. As long as @emgarten is happy with the error messages, I'll be ok.

**Comment by AndreyAkinshin** [comment]
>  referred to the following message

After this message, I have found a more consistent way to report about the situation. If we will print "No solution ...", it should be applied in all similar places (probably someone else should do it because I don't how to do it right way).

**Comment by emgarten** [comment]
Merged with NuGet/nuget.client@895c82b366d72d2484f49559801d41e004d1d7f1 for 3.5.0 RTM

Thanks for the PR @AndreyAkinshin!

**Pull request closed without merging**
