### PR TITLE
Change branding to 5.3 preview 2

### LINKED ISSUE #8293: Change dev branch target to preview 2

### PR DESCRIPTION
**Pull request by zivkan**
## Bug

Fixes: NuGet/Home#8293

### CODE REVIEW

**Review by nkolev92 — COMMENTED** [review]
Mind fixing up the CLI/SDK/Toolset branches? 

5.3 will only go into 3.0.

**Comment by zivkan** [comment]
I forgot you told us about that. It almost makes up for adding a 4th repo :)

**Comment by nkolev92** [comment]
yeah the 4th repo thing....if you are up for it, you can automation for it lol.

**Comment by nkolev92** [comment]
@zivkan 
This should be ok to merge now, since we have a preview 1 branch.

**Pull request merged**
