### PR TITLE
Ignore NU1603 warning when lock file is enabled

### LINKED ISSUE #7529: When restoring with lock file, NU1603 warning shouldn't be raised.
We're trying to adopt Locked package files in SDK 2.1.500, and were trying it out which revealed an issue. When we restore using `--locked-mode` (as if by CI), a lot of packages cannot be found, shown in messages like `warning NU1603: System.Globalization 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.`

In this case, I would expect that the same warnings during a regular restore would be present during a `--locked-mode` restore -- in this case, a regular restore has no issues while a locked restore has "hundreds" of these.

#### We're also seeing errors

In our larger solution, we're seeing errors as well, such as the below. This may be related to the fact that we're using GitVersion, so maybe the version on a project changes after the lock file is created.. ?.. That's another issue though.

```
C:\Our-SDK\Evidence\ProjectA\ProjectA.csproj : error NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Please disable RestoreLockedMode MSBuild property or pass explicit --force-evaluate flag to run restore to update the lock file. [C:\Our-SDK\Our-SDK.sln]
```

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Dotnet.exe used for restore, new project, etc.

NuGet version (x.x.x.xxx): `N/A`

dotnet.exe --version (if appropriate): `2.1.500`

OS version (i.e. win10 v1607 (14393.321)): `Win10 10.0.17134`

Worked before? If so, with which NuGet version: `N/A -- new feature in 2.1.500`

## Detailed repro steps so we can see the same problem

1. Create new console project, `dotnet new console`
2. Add a few packages, `dotnet add package Microsoft.EntityFrameworkCore`
3. Restore and create locked file, `dotnet restore --use-lock-file`
4. Restore using locked mode, `dotnet restore --locked-mode`

Now you should see warnings like:

```
warning NU1603: NETStandard.Library 2.0.3 depends on Microsoft.NETCore.Platforms (>= 1.1.0) but Microsoft.NETCore.Platforms 1.1.0 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.

warning NU1603: System.Globalization 4.0.11 depends on Microsoft.NETCore.Targets (>= 1.0.1) but Microsoft.NETCore.Targets 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Targets 2.1.0 was resolved.
```

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

`dotnet restore --locked-mode --verbosity diag` => [dotnet.log](https://github.com/NuGet/Home/files/2599940/dotnet.log)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

[bb.zip](https://github.com/NuGet/Home/files/2599943/bb.zip)

### PR DESCRIPTION
**Pull request by jainaashish**
## Bug

Fixes: https://github.com/NuGet/Home/issues/7529 
Regression: No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: With lock file resolution, we always resolve to exact version irrespective of the requested versions at multiple levels, which started raising unnecessary `NU1603` warnings. This PR fixes it and ignores NU1603 when running with lock file enabled. This will not impact the regular restore where lock file is not enabled and continue to raise `NU1603` as and when needed. 

## Testing/Validation

Tests Added: Yes  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Review by zivkan — APPROVED** [review]

**Review by nkolev92 — APPROVED** [review]
LGTM. 

We'll listen for feedback on this if it becomes a problem :)

**Comment by Lizzy-Gallagher** [comment]
This had been a major pain point for us, so we are excited to see this go out. Do you have any estimate on when or in what version this change will be released?

@nkolev92 @zivkan @jainaashish

**Comment by nkolev92** [comment]
@LizzyBradley It will be in Preview 4/RC. 

https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-preview

The release notes will be updated soon. 

@karann-msft @anangaur @rrelyea will have more details on that.

**Comment by anangaur** [comment]
https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-preview#summary-whats-new-in-nuget-50-preview-4

image

**Pull request merged**
