### PR TITLE
Add or Updates Copyright, ProjectUrl and LicenseUrl to NuGet.Core project.json files

### PR DESCRIPTION
**Pull request by deepakaravindr**
Updates files with old ProjectUrl to have the new ProjectUrl.
Add files with projectUrl if not present.
Same with license urls and copyright information.

@yishaigalatzer @rrelyea @emgarten  @alpaix

### CODE REVIEW

**Comment by alpaix** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
I have to run a full build on my machine once... Doing that now

**Comment by deepakaravindr** [comment]
Build including tests ran successfully on my machine.
Note that this change cannot be cherry picked into release-3.4.0 branch as-is, since, the versions on this PR and the dev branch is 3.5.0-*.

Will need to do a separate PR, Leaving https://github.com/NuGet/Home/issues/1886 open for that

**Comment by rrelyea** [comment]
:shipit:

**Pull request merged**
