### PR TITLE
Porting id fallback fix from dnx

### PR DESCRIPTION
**Pull request by emgarten**
Porting https://github.com/aspnet/dnx/pull/2938 to NuGet.Client.

//cc @yishaigalatzer @davidfowl @pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by emgarten** [comment]
Merged into NuGet.Client.Merge

**Comment by MeniZalzman** [comment]
:shipit:

**Comment by MeniZalzman** [comment]
Merged 
https://github.com/NuGet/NuGet.Client/commit/1b0fbbcbac2ba3e39d4f424a751c30c2498d0519

**Pull request closed without merging**
