### PR TITLE
Set warnings as errors build flag for all client projects

### PR DESCRIPTION
**Pull request by drewgillies**
Now that we have no build warnings in client, let's seal the deal.
@joelverhagen @alpaix @emgarten

### CODE REVIEW

**Comment by joelverhagen** [comment]
How did we pick this set of 5 projects?

**Comment by drewgillies** [comment]
The flags were already set in the others. Wait a bit though--I'm about to push some test projects with added flags too. Will advise.

**Comment by joelverhagen** [comment]
Are the downgrade warnings during package restore on your radar as well? Not necessarily your responsibility, but I realized this could be another source of warnings.

**Comment by drewgillies** [comment]
I haven't looked at them. Are they in core build? This is just about client build warnings.

**Comment by joelverhagen** [comment]
We do a restore for client projects right now, and the restore is quiet by default, so we don't see _any_ output, e.g. in the build output

<pre>
[08:57:08 +0]   [BEGIN] Building NuGet.Clients projects - VS14 dependencies
[08:57:08 +0]   Restoring packages @"C:\src\git\github.com\NuGet\NuGet.Client"
<b>[08:57:08 +0]   C:\src\git\github.com\NuGet\NuGet.Client\.nuget\nuget.exe restore C:\src\git\github.com\NuGet\NuGet.Client\NuGet.Clients.sln -MSBuildVersion 14 -verbosity quiet</b>
[08:57:16 +8]   C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe C:\src\git\github.com\NuGet\NuGet.Client\NuGet.Clients.sln /p:Configuration=debug;ReleaseLabel=zlocal;BuildNumber=10475 /verbosity:minimal
</pre>

**Comment by drewgillies** [comment]
Okay, @joelverhagen --I went with the common.props approach.

**Comment by joelverhagen** [comment]
:shipit:

**Pull request merged**
