### PR TITLE
Added capability for unsupported frameworks to fall back to a supported framework.

### PR DESCRIPTION
**Pull request by tylerohlsen**
Updated framework validation to inspect fallback frameworks

https://github.com/NuGet/Home/issues/5460

### CODE REVIEW

**Comment by emgarten** [comment]
@tylerohlsen thanks for the PR. 

A few questions on the original issue. Why is the framework parsed as unsupported? I'm not sure what ignoring a bad framework and allowing it if the fallbacks are valid is the right approach here.

Does `.NETFramework,Version=v3.5,Profile=Unity Full v3.5` fail to parse because it is using the long form? Or is it due to the spaces in the profile?

**Comment by tylerohlsen** [comment]
@emgarten thanks for the review.  

I had assumed the framework didn't parse since it is from a plugin and not a "known" framework.  The long form does seem to parse correctly, but the short form does not parse because of the spaces.  In my app, if I change the spaces to pluses in the short or long form, the NuGet exception goes away and NuGet commands succeed but it fails to compile.  So I really do need the spaces. 

I see the spot in NuGet code where NuGetFramework.Parse has a whitelist of valid characters.  Can I change my PR to instead just add space to that whitelist?

**Comment by tylerohlsen** [comment]
To clarify, I get the error when my app has either the long form or short form.  I'm not sure why the long form fails because NuGetFramework.Parse succeeds on the long form.  Maybe there's a Parse and then a ToString which converts to short form and then a second Parse that fails?

Also, would it be better to have NuGetFramework.Parse throw on a failure instead of continue with null / "unsupported"?

**Comment by emgarten** [comment]
> Also, would it be better to have NuGetFramework.Parse throw on a failure instead of continue with null / "unsupported"?

It is expected that NuGet will encounter frameworks it doesn't understand from future packages, so this can't cause a failure.

> I see the spot in NuGet code where NuGetFramework.Parse has a whitelist of valid characters. Can I change my PR to instead just add space to that whitelist?

I think this would cause problems in other areas.

Try using this project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net35</TargetFramework>
        <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
        <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
        <TargetFrameworkProfile>Unity Full v3.5</TargetFrameworkProfile>
        <PackageTargetFallback>$(PackageTargetFallback);net35</PackageTargetFallback>
        <FrameworkPathOverride>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Unity Full v3.5</FrameworkPathOverride>
    </PropertyGroup> 
    
    <ItemGroup>
        <PackageReference Include="NLog" Version="4.4.9" />
    </ItemGroup>
</Project>
```

`TargetFramework` is used more as an alias by the actual project system, the profile will be found from `TargetFrameworkProfile`

**Comment by tylerohlsen** [comment]
I'm not finding a combination that works.  Note: In all of these tests, I kept the rest of the above csproj unchanged and only changed the `<TargetFramework>` node (unless otherwise specified).
***
**Test 1**  
```xml
<TargetFramework>.NETFramework,Version=v3.5,Profile=Unity Full v3.5</TargetFramework>
```
`dotnet restore` - success
`dotnet add package NLog -v 4.4.10` - fail: ``` Invalid target framework 'unsupported' ```
`dotnet build` - success
***
**Test 2**  
```diff
<TargetFramework>.NETFramework,Version=v3.5,Profile=Unity Full v3.5</TargetFramework>
- <PackageTargetFallback>$(PackageTargetFallback);net35</PackageTargetFallback>
```
`dotnet restore` - fail: Package NLog 4.4.10 is not compatible with net35-unity full v3.5
`dotnet add package NLog -v 4.4.10` - fail: ``` Invalid target framework 'unsupported' ```
`dotnet build` - fail
```
warning MSB3256: No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated.
error CS0246: The type or namespace name 'NLog' could not be found
```
***
**Test 3**  
```xml
<TargetFramework>net35-unity full v3.5</TargetFramework>
```
`dotnet restore` - fail: ``` Invalid target framework 'unsupported' ```
`dotnet add package NLog -v 4.4.10` - fail: ``` Invalid target framework 'unsupported' ```
`dotnet build` - success
***
**Test 4**  
```xml
<TargetFramework>net35</TargetFramework>
```
`dotnet restore` - success
`dotnet add package NLog -v 4.4.10` - success
`dotnet build` - fail
```
warning MSB3256: No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated.
error CS0246: The type or namespace name 'NLog' could not be found
```
***
- Test 1 shows the issue I originally reported with `dotnet add package` failing because of the spaces in the profile name.
- Test 1 and Test 2 show that PackageTargetFallback is _helping_.  Without PackageTargetFallback `dotnet restore` fails.
- Test 3 shows that the short name also fails with `dotnet restore` because of the spaces in the profile name.
- Test 4, as you suggested, does succeed with both `dotnet restore` and `dotnet add package`, but fails to compile.

**Comment by tylerohlsen** [comment]
>> Also, would it be better to have NuGetFramework.Parse throw on a failure instead of continue with null / "unsupported"?  

> It is expected that NuGet will encounter frameworks it doesn't understand from future packages, so this can't cause a failure.  

But as it is now, NuGetFramework.Parse returns an 'unsupported' framework and later the validation step throws anyway.  So it is causing failures, just at a later stage.  And the validation step throws without knowing what the original TF moniker was to give a coherent message.

That is, unless it were to not throw on the validation step if there is a supported fallback framework ;)

**Comment by tylerohlsen** [comment]
@emgarten any further suggestions?

Sounds like both approaches to fix this issue are not desirable to the codebase (allow spaces in profile name -and- allow 'unsupported' frameworks to fallback to a supported framework).  Any other ideas for a different workaround / fix?

**Comment by emgarten** [comment]
@tylerohlsen the fix for https://github.com/NuGet/Home/issues/5154 may solve this issue. NuGet would read the framework from the moniker properties instead. It might be difficult to make that fix. 

Have you tried adding PackageReferences to a classic csproj instead of a NETCore SDK project? Is there any reason you are trying this with NETCore SDK? Is it officially supported there?

**Comment by tylerohlsen** [comment]
I've greatly simplified my example for this issue.  My actual project multitargets and depends on other projects that also multitarget.  Going back to the classic csproj is not really an option for me at this point.

**Comment by tylerohlsen** [comment]
That issue does sound like it has potential to solve my problem.  I see it has been open for a few months, has no assignee, and is in a milestone with no due date.  Know if there will be any movement soon?

**Comment by emgarten** [comment]
> Know if there will be any movement soon?

Possibly for NuGet 4.5.0

**Comment by emgarten** [comment]
I'm going to close this PR since we have determined this isn't the right fix. Let's continue the discussion in https://github.com/NuGet/Home/issues/5460

I've also moved https://github.com/NuGet/Home/issues/5154 so that it will be considered for an earlier release

**Pull request closed without merging**
