### PR TITLE
Fix corefx package versions

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
This resolves issues where NuGet would resolve RC3 packages instead of RC2. Also removes `runtime`\* references.

cc @emgarten

**Comment by emgarten** [comment]
:shipit:

**Comment by pranavkm** [comment]
@yishaigalatzer, would this be something we can get in to to the 3.5 It means the lineups for CLI would be correct and we can remove `imports` from CLI \ Aspnet. I can prepare a change against the 3.5 branch if that's ok.

**Comment by emgarten** [comment]
This would fix https://github.com/NuGet/Home/issues/2191

**Comment by yishaigalatzer** [comment]
Sounds good to me

**Comment by pranavkm** [comment]
Updated (this is merging release-3.5.0-beta into dev)

**Pull request closed without merging**
