### PR TITLE
Update to Newtonsoft.Json 9.0.1 and remove imports

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
We could wait until Json.Net has RTM builds available. @Eilon knows when that would be available.

**Comment by yishaigalatzer** [comment]
The RTM builds have to go online for us to take them. Is there a reason to take this faster than that? I'd like to avoid depending on pre-RTM bits for RTM products.

**Comment by Eilon** [comment]
RTM bits will be available next week.

**Comment by pranavkm** [comment]
:up: :date:

**Pull request closed without merging**
