### PR TITLE
build.ps1 enhancements

### PR DESCRIPTION
**Pull request by pranavkm**
Switch to v3 endpoints for dnu restore
Use -Filter instead of looking for xproj extension

### CODE REVIEW

**Comment by MeniZalzman** [comment]
:watch: Is beta 7 support v3?

**Comment by pranavkm** [comment]
Yup. Support for api v3 has been around for a couple of releases now.

**Comment by emgarten** [comment]
We should merge this into dev
:shipit:

**Comment by deepakaravindr** [comment]
:+1: :shipit:

**Pull request closed without merging**
