### PR TITLE
Add all other existing Apex test cases to the apex daily pipeline

### PR DESCRIPTION
**Pull request by SueSu01**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/2778

Regression? Last working version:

## Description

Add all other existing Apex test cases to the new daily pipeline to see if they can run stable.
## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
To me this looks like we're duplicating all the tests. 

Why do we need that?

**Comment by SueSu01** [comment]
> To me this looks like we're duplicating all the tests.
> 
> Why do we need that?

NuGet test team plan to add all tests to apex daily pipeline. If you just want to keep these tests in the official pipeline, I will close this PR. Thanks.

**Comment by nkolev92** [comment]
> > To me this looks like we're duplicating all the tests.
> > Why do we need that?
> 
> NuGet test team plan to add all tests to apex daily pipeline. If you just want to keep these tests in the official pipeline, I will close this PR. Thanks.

I think running them on the daily pipeline could be ok, but this introduces risk of duplication. 
Any test change would need to be made in 2 files.

If you want to have them everywhere, I'd just compile the files into the other dll.

**Comment by SueSu01** [comment]
> > > To me this looks like we're duplicating all the tests.
> > > Why do we need that?
> > 
> > 
> > NuGet test team plan to add all tests to apex daily pipeline. If you just want to keep these tests in the official pipeline, I will close this PR. Thanks.
> 
> I think running them on the daily pipeline could be ok, but this introduces risk of duplication. Any test change would need to be made in 2 files.
> 
> If you want to have them everywhere, I'd just compile the files into the other dll.

Thanks for your suggestion. I will try to add _NuGet.Tests.Apex.dll_ to _NuGet.Tests.Apex.Daily.runsettings_.

**Pull request closed without merging**
