### PR TITLE
Make NuGet.CommandLine.Test run in parallel

### PR DESCRIPTION
**Pull request by heng-liu**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/518

Regression? Last working version:

## Description
1. Isolate the following tests:
```
RestoreCommand_FromPackagesConfigFileFailed
RestoreCommand_NoFeedAvailable
InstallCommand_FromPackagesConfigFile_SpecifyingRelativeSolutionDir
SourcesCommandTest_AddSource
SourcesCommandTest_AddWithUserNamePassword
SourcesCommandTest_AddWithUserNamePasswordInClearText
TestVerbosityQuiet_DoesNotShowInfoMessages
Sources_WhenAddingSource_GotAdded
Sources_WhenAddingSourceWithCredentials_CredentialsWereAddedAndEncrypted
Sources_WhenAddingSourceWithCredentialsInClearText_CredentialsWereAddedAndNotEncrypted
TestVerbosityQuiet_DoesNotShowInfoMessages
```
2.Change the Mutex to adapt tests running concurrently (This is done by @kartheekp-ms )
3.Make `NuGet.CommandLine.Test` run in parallel (`<UseParallelXunit>true</UseParallelXunit>` and delete it's own `xunit.runner.json`)
4.Delete [NotThreadSafeResourceCollection.cs](https://github.com/NuGet/NuGet.Client/blob/dev/test/TestUtilities/Test.Utility/NotThreadSafeResourceCollection.cs) from TestUtilities and add it to each test assembly which has tests need to run in sequential. As "[Important note: Fixtures can be shared across assemblies, but collection definitions must be in the same assembly as the test that uses them.](https://xunit.net/docs/shared-context#collection-fixture)" (Thanks to @kartheekp-ms 's help on investigating this!)

Additional tests:
Run `NuGet.CommandLine.Test` locally on mac for 40 times (with max threads = 8), 1 test from 1 round failed for timing out waiting for Mutex.
Since on CI the max threads will be much less (usually 3), it should be no worse than running locally.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
Nicely done!
🥇

**Review by zivkan — APPROVED** [review]
Great work!

**Comment by aortiz-msft** [comment]
He @heng-liu - Could we please add measurements for the before and after the change?

**Comment by heng-liu** [comment]
Here is the comparison before and after this change:

**Before**:

|Build link |                                                                                               Tests_On_Mac |   Functional_Tests_On_Windows IsDesktop|
|--|--|--|
|[6.0.0.108](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4857549&view=results)    |1h9m7s |  1h17m16s|
|[6.0.0.107](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4854168&view=results)    |1h7m47s | 1h15m44s|
|[6.0.0.106](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4852800&view=results)    |1h10m46s | 1h18m49s|
|[6.0.0.104](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4848386&view=results)    |1h8m9s   |1h15m27s|
|[6.0.0.103](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4845559&view=results)    |1h11m8s  |1h14m14s|
|[6.0.0.102](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4842618&view=results)    |1h21m20s |1h12m59s|
|[6.0.0.101](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4839220&view=results)    |1h7m39s  |1h13m28s|
|[6.0.0.100](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4838101&view=results)    |1h8m9s   |1h17m56s|
|[6.0.0.99](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4837869&view=results)     |1h10m28s |1h17m39s|
|[6.0.0.97](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4836777&view=results)     |1h7m46s  |1h15m36s|
|[6.0.0.96](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4836599&view=results)     |1h9m32s  |1h14m56s| 
|**Average**| 70m6s| 75m48s|

**After**:

|Build link |                                                                                               Tests_On_Mac |   Functional_Tests_On_Windows IsDesktop|
|--|--|--|
|[6.0.0.122](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4875050&view=results)  |  51m3s  |  1h1m34s|
|[6.0.0.121](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4874593&view=results)  |  56m3s  |  59m49s|
|[6.0.0.120](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4874489&view=results)  |  51m8s  | 59m3s|
|[6.0.0.119](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4874315&view=results)  |  50m38s |  1h1m31s|
|[6.0.0.118](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4874227&view=results)  |  53m27s |  58m38s|
|[6.0.0.117](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4870396&view=results)  |  54m37s |  59m32s|
|[6.0.0.116](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4869335&view=results)  |  57m33s |  59m11s|
|[6.0.0.115](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4864816&view=results)  |  48m33s |  58m54s|
|[6.0.0.114](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4864621&view=results)  |  50m52s |  1h3m|
|[6.0.0.113](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4864373&view=results)  |  54m1s   | 1h6m8s|
|[6.0.0.112](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4863745&view=results)  |  51m1s   | 58m44s|
|[6.0.0.111](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4862137&view=results)  |  53m23s |  1h0m25s|
|[6.0.0.109](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4857746&view=results)  |  53m1s   | 59m48s|
|**Average**| 52m42s| 60m29s|

So the build time improvement for Tests_On_Mac is **17m24s**, and for Functional_Tests_On_Windows IsDesktop, it's **15m19s**.

**Pull request merged**
