### PR TITLE
Improve build error reporting

### PR DESCRIPTION
**Pull request by dtivel**
Report useful call stack information for a build error.

Fixes NuGet/Home#3482.

### CODE REVIEW

**Comment by mishra14** [comment]
@dtivel : Tag people in PRs to improve visibility and response time.

//cc: @joelverhagen @jainaashish @alpaix @rohit21agrawal @drewgil @zhili1208

**Comment by mishra14** [comment]
Looks good to me.

**Comment by joelverhagen** [comment]
:shipit:

**Review by alpaix — APPROVED** [review]

**Comment by dtivel** [comment]
Abandoning this PR because:
1.  The relevant error reporting was [removed by a later commit](https://github.com/NuGet/NuGet.Client/pull/879/files#diff-f0e02e42e53ec40f5d3b8bed031ad09eL89).
2.  Useful stack information is now reported with latest build changes.

**Pull request closed without merging**
