### PR TITLE
Adding SVG to the list of support Icon format

### PR DESCRIPTION
**Pull request by tebeco**
## Enhancement
This PR intend to bring up the discussion about SVG on the table to see if it could be a thing or not
I see a lots of question on Twitter, Slack, Discord about the "how to use vectorial image well known standard (like SVG) for icon rather that only png, jpeg, jpg"
As I would have understood 10 years ago, is there still limitation today that could block this feature to move forward ?

## Testing/Validation

Tests Added: No (Not yet)
Reason for not adding tests: Bringing the discussion to the table before starting to work on it
Validation:

### CODE REVIEW

**Comment by zivkan** [comment]
@tebeco The reason that we don't support SVG is because Package Manager in Visual Studio uses WPF, which doesn't support SVG. UWP does support SVG natively, so theoretically XAML Islands might be an option on Windows 10 (not sure about Windows 8), but we still have non-trivial numbers of people using Visual Studio 2019 on Windows 7, hence UWP isn't an option.

I can bring this up with the team, but I really don't think we can accept this until we can easily support this image format in Visual Studio's Package Manager UI.

**Comment by tebeco** [comment]
i guessed so, so i'm trying to see if that support could land to have something supporting SVG or just render SVG to BMP 

As suggested here:
https://twitter.com/mkristensen/status/1330208068123189252

that would be an amazing step forward even if it's just SVG to BMP in a first release right ?

Also as a library author, it feel weird to hit a limitation that comes from a special panel of Visual Studio.
I mean, what comes to my mind first is probably nuget.org, and it look very weird that the visual studio UI is the part limiting the "evolution" of the authoring part of nuget package.

**Comment by zivkan** [comment]
I had a chat with a PM for NuGet, and we agree that it doesn't make sense to take this change at this time. We care about the overall experience, not just early adopters, and at the moment the vast majority (very roughly, 10x) of search requests come from Visual Studio, compared to the website. Therefore, a package author using a SVG icon will at best only have a small percentage of package consumers see the icon, which doesn't seem very beneficial, and would surprise many package authors who don't know about the limitation.

I searched NuGet/Home for issues mentioning SVg, reopened the closest match, closed another as a duplicate of it, and encouraged people in another issue to upvote this one: https://github.com/NuGet/Home/issues/2519

I've love SVG to become the defacto icon format, but enabling package authors to use it when most customers won't be able to see it won't give a good experience. I don't know if adding PM UI SVG support to this PR is enough, or if we'd want to first add PM UI support, wait a release or two, so a significant number of customers are using a version of VS that supports it, and then unblock pack. Therefore I propose we close this PR and reopen, or recreate it, after PM UI can display SVG (plus we have a chance to talk to the VS for Mac team, and maybe JetBrains, to give them an opportunity to add support before we're likely to start seeing packages on nuget.org with SVG icons).

**Comment by ZacharyPatten** [comment]
I just want to mention one topic: It has become common for GIT repos to use `* text=auto` in the `.gitattributes`, and `.svg` is text of course (not binary like the file types supported by nuget icons currently). So requiring binary file formats (in repos that might otherwise have no binary files), is a bit of a pain.

**Comment by augustoproiete** [comment]
@zivkan Just an idea (which goes beyond this PR):

#### Phase 1 (initial svg support)
- Allow package authors to add an `.svg` icon  in addition to `.png`, `.jpg`, or `.jpeg` to the NuGet package
    - Visual Studio (and other UI clients) can continue to use the regular icon inside the package as it is today
    - This would require a new element in the NuGet spec e.g. `<packageVectorIcon />` (which would open the door for supporting other formats in the future such as `.eps`, `.ai`, etc.)
- Update the NuGet Gallery to use the `.svg` if one is available, fallback to one of the other icons
- It's the responsibility of the package author to provide both `.svg` and `.png` and ensure they match
- (Optional) Add validation to ensure they provided a `.png`, `.jpg`, or `.jpeg` in case they provided an `.svg`

#### Phase 2 (maybe, or just skip to phase 3)
- Update the NuGet Gallery to automatically generate a `.png` 128x128 from the `.svg` after upload
    - So that package authors don't have to worry about `.png`, `.jpg`, or `.jpeg` anymore. Just the `.svg`, which as @ZacharyPatten mentioned, is source control-friendly 

#### Phase 3 (PM UI updates)
- Let Visual Studio update their UI to support `.svg` at their own pace
- Let JetBrains update their UI to support `.svg` at their own pace
- Let VS for Mac update their UI to support `.svg`  at their own pace

#### Phase 4 (maybe one day, once major IDEs and UI clients understand `packageVectorIcon`)
- Deprecate `.png`, `.jpg`, and `.jpeg` in NuGet pack
- Stop generating `.png` from the `.svg` in the NuGet Gallery

**Comment by tebeco** [comment]
That would be lovely to move on something like this yes

(moved reply to https://github.com/NuGet/Home/issues/2519#issuecomment-733078599)

**Comment by JonDouglas** [comment]
As mentioned on discord, it sounds like the most appropriate step to move this forward with community contributions is for somebody on this thread to create a proposed design:

https://github.com/NuGet/NuGet.Client/blob/dev/docs/design-review-guide.md#design-rules

& PR that against https://github.com/NuGet/Home/tree/dev/designs

A great candidate for a phased approach is @augustoproiete proposal in https://github.com/NuGet/NuGet.Client/pull/3773#issuecomment-732506565 which I believe will put us one step closer to SVG support without having to completely block on progress because we can't commit to VS PMUI SVG support quite yet. We can review the design PR & help outline what work will need to happen for each phase for the community as `up-for-grabs`.

**Comment by zivkan** [comment]
Closing this PR as per my previous comment, and Jon's comment. Once we have a design spec that plans how SVG icon experience will work, we can consider enabling pack to allow SVG icons.

**Comment by adamralph** [comment]
Do I understand correctly that the NuGet team is not going to initiate any work on this, and instead rely only on external contributions?

**Comment by zivkan** [comment]
We prioritize our efforts on a number of factors, and SVG icons don't make the cut at this time.

**Pull request closed without merging**
