### PR TITLE
Add serviceable attribute.

### PR DESCRIPTION
**Pull request by TimBarham**
See NuGet/Home#2779

### CODE REVIEW

**Comment by TimBarham** [comment]
Additional changes still to come (descriptions for some assemblies, and `CommitHash`).

**Comment by joelverhagen** [comment]
Is `AssemblyMetadata` not available in `net40-client`?

**Comment by TimBarham** [comment]
Right. It was introduced in 4.6.

**Comment by joelverhagen** [comment]
:shipit:

**Pull request merged**
