### PR TITLE
Fix mono trust validation for the plugins

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug
Fixes: https://github.com/NuGet/Home/issues/7222
Regression: No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: 

The issue here was that some of the APIs weren’t available on Mono. I reworked it with the mono recommended APIs, and the authentication verification works. 
Now it works, but it’s not successful. The reason for that is that the Microsoft Root CA is not trusted by default on Linux and Mac. 

The options are: 
1. Require that all plugin authors timestamp their authenticode signed assemblies with a CA like Digicert.
2. Just disable it on Mono. 

This PR currently contains option number 2.
The first commit is option number 1 however, so can easily amend to whatever decision we make, 

//cc @rrelyea 

## Testing/Validation
Tests Added: No  
Reason for not adding tests:  Not testable automatically.
Validation done:  Manual

### CODE REVIEW

**Comment by dtretyakov** [comment]
@rrelyea, could you please take a look at the fix?

**Comment by nkolev92** [comment]
@dtretyakov 
We're discussing this internally.

**Comment by nkolev92** [comment]
Discussed with @rrelyea  and Doron. 

Short term, we'll disable it.

**Review by PatoBeltran — APPROVED** [review]

**Comment by nkolev92** [comment]
Merged to 4.9.0-preview4 https://github.com/NuGet/NuGet.Client/commit/d737e2e05f2c4c673da988626c64374693d12bc1

**Pull request merged**
