### PR TITLE
Split Silverlight tests into separate test file (to allow easy exclusion or isolated runs)

### PR DESCRIPTION
**Pull request by joelverhagen**
/cc @alpaix @drewgil 

It seems the test hang has to do with msbuild crashing sometimes when creating a Silverlight project. Investigation is on-going.

### CODE REVIEW

**Comment by drewgillies** [comment]
:shipit:

**Comment by alpaix** [comment]
What does it give us moving two tests to other file?

**Comment by joelverhagen** [comment]
@alpaix, the `Run-Test` PowerShell command accepts `-File` and `-Exclude` arguments, which allow you to have a separate test run that only handles the Silverlight tests (and allows a VS restart in between). This is a workaround for the VS crash.

**Comment by alpaix** [comment]
:ok: thanks for the explanation.
:shipit:

**Pull request merged**
