### PR TITLE
Update NuGet Packages

### PR DESCRIPTION
**Pull request by SiliconA-Z**
## Bug

Fixes:
Many of these packages are years old, and should be updated since a lot has changed since then.
Regression? Last working version:

## PR Checklist

- [X] PR has a meaningful title
- [ ] PR has a linked issue.
- [X] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by erdembayar** [comment]
@AtariDreams 
Please fill out the PR template and checklist. Please check at other PRs.

**Review by zivkan — CHANGES_REQUESTED** [review]
Thanks for taking the time to make a contribution!

If you look at the changes in your PR, you'll see the changes are not simply changing version numbers, but adding `PackageReference` items into the project files. We use a home-grown "central package versions" implementation, with all package versions defined in `build/packages.targets`, where version numbers should be changed. I think at some point we also had an MSBuild target that would fail the build (or fail restore) if any `PackageReference` in a csproj contains a version, but I'm not sure if it still works, or maybe it only works on the command line, not VS.

**Comment by erdembayar** [comment]
Please make your changes in https://github.com/NuGet/NuGet.Client/blob/dev/build/packages.targets file.
You need to make update like [this PR](https://github.com/NuGet/NuGet.Client/pull/4247/files).

**Comment by SiliconA-Z** [comment]
Done @erdembayar

**Comment by erdembayar** [comment]
@AtariDreams 
CI build failed, it's complaining about ` Error NU1102: Unable to find package System.Security.Cryptography.Cng with version (>= 6.0.1)`. I don't see version `6.0.1` here: https://www.nuget.org/packages/System.Security.Cryptography.Cng
Latest version I can see is https://www.nuget.org/packages/System.Security.Cryptography.Cng/6.0.0-preview.4.21253.7 but it's not stable version, probably just leave as it's now.

**Comment by SiliconA-Z** [comment]
https://www.nuget.org/packages/System.Security.Cryptography.Pkcs/ exists, but yeah

**Comment by SiliconA-Z** [comment]
Fixed! @erdembayar

**Comment by erdembayar** [comment]
> Fixed! @erdembayar Erick Yondon FTE

Please rebase with dev and please make sure this code compiles on your local, there's compilation error.

**Comment by SiliconA-Z** [comment]
@erdembayar done!

**Comment by erdembayar** [comment]
> @erdembayar done!

Did you make sure code compiles on your local with your change?

I still see many compilation errors.

```
##[error]CSC(0,0): Error CA9998: FxCopAnalyzers package has been deprecated in favor of 'Microsoft.CodeAnalysis.NetAnalyzers', that ships with the .NET SDK. Please refer to https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers to migrate to .NET analyzers.
##[error]CSC(0,0): Error CA9998: FxCopAnalyzers package has been deprecated in favor of 'Microsoft.CodeAnalysis.NetAnalyzers', that ships with the .NET SDK. Please refer to https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers to migrate to .NET analyzers.
```

```
##[error]src\NuGet.Core\NuGet.Frameworks\NuGetFrameworkFactory.cs(52,26): Error CA1310: The behavior of 'string.IndexOf(string)' could vary based on the current user's locale settings. Replace this call in 'NuGet.Frameworks.NuGetFramework.Parse(string, NuGet.Frameworks.IFrameworkNameProvider)' with a call to 'string.IndexOf(string, System.StringComparison)'.
##[error]src\NuGet.Core\NuGet.Versioning\FloatRange.cs(283,62): Error CA1310: The behavior of 'string.EndsWith(string)' could vary based on the current user's locale settings. Replace this call in 'NuGet.Versioning.FloatRange.TryParse(string, out NuGet.Versioning.FloatRange)' with a call to 'string.EndsWith(string, System.StringComparison)'.
```

**Comment by erdembayar** [comment]
Team triage: Thank you for your contribution, we have parallel effort, so close this one favor of CPM effort.

**Pull request closed without merging**
