### PR TITLE
Run init.ps1 scripts for restored packages

### PR DESCRIPTION
**Pull request by DavidVivash**
Relates to issue #1292 (https://github.com/NuGet/Home/issues/1292).
PackageRestoredEvent is subscribed to, init scripts are run in the order the packages are restored, not sure if that'll be an issue.

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
Can you please describe the purpose of the change? Also note that we cannot take it for 3.4 (as we are done with oss scanning) and it will have to wait for 3.5

**Comment by DavidVivash** [comment]
The issue linked to (https://github.com/NuGet/Home/issues/1292) describes the problem - in brief, init.ps1 is currently only being called for each package when the powershell host is first initialised, when a solution is first opened, or when a package is first installed. 

With this change, the init.ps1 script will also be called when a NuGet package restore occurs, for each of the restored packages.

**Comment by yishaigalatzer** [comment]
Thanks! We will hold on to your changes until we start taking work for 3.5. In the meantime this change requires a functional test and a review

**Comment by DavidVivash** [comment]
I've added a functional test to the PackageRestore test scripts, but... it doesn't work.  The reason is that running init scripts needs the powershell pipeline to be free, but when we're running the test, it's already using the pipeline. So I'm not sure how a functional test on this is going to work.

There are functional tests in ServicesTest.ps1 which look like they run init scripts, but they only run init scripts as part of a package install; there aren't any tests I can see which get around the problem of the powershell pipeline being busy.

Also, I noticed the RestorePackage tests are currently being ignored from the full test run - some of the tests were failing so I've updated them to fix them. In one instance I've needed to modify the code-base as I believe the test was highlighting a bug (Test-PackageRestore-CheckForMissingPackages attempts to verify that missing packages are named in the error message, but they're currently not).

Anyway, I've committed these changes, so if anyway can think of or see a way around the functional test issue that'd be great.

**Comment by yishaigalatzer** [comment]
@rrelyea can you assign someone to merge this?

**Comment by emgarten** [comment]
> PackageRestoredEvent is subscribed to, init scripts are run in the order the packages are restored, not sure if that'll be an issue.

The order does matter for some packages. It is possible for A -> B that the init.ps1 script for A requires modules brought in by package B. It is also possible that a package expects the dependencies to be on disk even if they do not have their own init.ps1.

I would expect the script execution here to only happen once all packages have been restored, and to use the same code in the powershell host that orders everything correctly.

**Comment by DavidVivash** [comment]
As order is important the code in this fix wont work. I think a new event on PackageRestoreManager would be necessary (PackagesRestoredEvent, or something), which can fire once package restore is complete for all packages (as suggested above). 

Not sure about using the same code from powershell host to ensure order is correct - the code for this fix already orders everything (it's exactly the same code that runs the init scripts when a solution is opened). So I think the issue is just that we need to wait until package restore has finished before trying to call the init scripts.

**Comment by emgarten** [comment]
> I think a new event on PackageRestoreManager would be necessary (PackagesRestoredEvent, or something)

That sounds like the correct approach to me, maybe a begin and end event for the batch restore process.

**Comment by yishaigalatzer** [comment]
We can't add events to the existing interface, we will have to create a new one

Get Outlook for Androidhttps://aka.ms/ghei36

On Tue, Jun 21, 2016 at 2:30 PM -0700, "Justin Emgarten" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think a new event on PackageRestoreManager would be necessary (PackagesRestoredEvent, or something)

That sounds like the correct approach to me, maybe a begin and end event for the batch restore process.

##

**Comment by emgarten** [comment]
//cc @harikmenon who is investigating adding init.ps1 for restore

**Pull request closed without merging**
