### PR TITLE
Added NuGet.exe validation scenarios

### PR DESCRIPTION
**Pull request by alpaix**
Automated nuget.exe validation scenarios using Pester unit-test framework.
Pester tools package added to a solution level packages folder.
Test cases for 'nuget config' command organized in a single .Tests.ps1
file.
Pester runner invokation is wrapped into validate.ps1 script. It restore
packages, import Pester module, invokes pester with a scenario file.

### CODE REVIEW

**Comment by alpaix** [comment]
Usage example:

> .\validate.ps1 X:\temp\nuget-test\nuget.exe

Sample output:
image

**Comment by alpaix** [comment]
//cc @rrelyea @emgarten @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Can we have a chat about the approach? Writing PS tests and debugging them is another required skill set to do stuff that can be done in C#. I want to have a chat to see if that is where we should take commandline tests.

**Comment by emgarten** [comment]
This is nice. I do agree @yishaigalatzer comments on PS vs C# skills here. I know from writing the VS functional tests in powershell that it takes me a long time to write the helper methods I need to validate the project files and outputs in PS.

**Comment by alpaix** [comment]
@yishaigalatzer Powershell is prevailing scripting language on Windows platform and is widely used in NuGet ecosystem for building, publishing, testing flows. At the same time NuGet client offers full set of PS cmdlets so I'd say PS skills are mandatory for a developer.

**Comment by alpaix** [comment]
The motivation behind this approach was to provide a script capable to run the same set of validation scenarios against any given nuget.exe. No need to build or debug.

**Comment by yishaigalatzer** [comment]
Please set up a meeting to discuss. PR is not the place for it

**Comment by alpaix** [comment]
Revoking the PR...

**Pull request closed without merging**
