### PR TITLE
Removing XPlat restore

### LINKED ISSUE #3903: Remove XProj restore
The legacy xproj ``dotnet nuget restore`` should be removed along with all resolver code that could potentially cause issues if it were used and projects were resolved through sibling directories or global.json.

XPlat entry point:
https://github.com/NuGet/NuGet.Client/blob/6f3ae2d59140f5ea97eb7573535de1c286d6d336/src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs#L78

### PR DESCRIPTION
**Pull request by emgarten**
XPlat restore for project.json/xproj is no longer valid. This change removes that code and fixes tests that were relying on xproj behaviors. The goal of this PR is to remove everything that will not ship in RTM and fix up failing tests. All other work such as adding new tests should be addressed outside of this PR.

Removed:

* XProj support
* Resolving projects through directories support
* Global.json support
* XPlat restore entry point
* Project.json tool support

Fixes https://github.com/NuGet/Home/issues/3903

//cc @mishra14 @joelverhagen @drewgil @alpaix @jainaashish

### CODE REVIEW

**Comment by mishra14** [comment]
@emgarten , this branch is [failing](http://nugetci/viewType.html?buildTypeId=NuGetClient_NuGetCiBuildConfigurations_PrivateDev_BuildForWindows&tab=buildTypeChains&branch_NuGetClient_PrivateDev=dev-emgarten-removeXProj) a bunch of tests on mac, linux and windows. Please fix those.

⌚️

**Comment by emgarten** [comment]
@mishra14 thanks, tests are passing again now

**Comment by drewgillies** [comment]
> ```
>                 null,
> ```

Suggestion: for readability, name these parameters.

---

Refers to: test/NuGet.Core.Tests/NuGet.PackageManagement.Test/InstallationCompatibilityTests.cs:450 in dfd4b59. [](commit_id = dfd4b59e50a7f8b6be2ef38f3ec6fa845ba2f205, deletion_comment = True)

**Comment by drewgillies** [comment]
:shipit:

**Pull request merged**
