### PR TITLE
CPM dotnet add package feature

### LINKED ISSUE #9022: [Feature]: Add support for central package management to dotnet add package
Implement changes for dotnet add

### PR DESCRIPTION
**Pull request by martinrrm**
## Bug

Fixes: https://github.com/NuGet/Home/issues/9022

Regression? Last working version:

## Description

This PR merges dotnet add functionality to dev branch

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Review by nkolev92 — DISMISSED** [review]

**Comment by nkolev92** [comment]
As a feature, this should wait on merging until dev switches to 6.5.

**Comment by erdembayar** [comment]
@martinrrm 
Could you add latest rendered spec link into the description?

**Comment by erdembayar** [comment]
> As a feature, this should wait on merging until dev switches to 6.5.

Should this merge now since we're on 6.5?

**Comment by martinrrm** [comment]
Yess, I've been trying to get a green build so I can finally merge

**Comment by martinrrm** [comment]
Ready to merge, tests were failing because I did a mistake while rebasing

**Review by nkolev92 — APPROVED** [review]

**Pull request merged**
