### PR TITLE
Use out parameters instead of System.Tuple to reduce allocations

### LINKED ISSUE #11732: Unnecessary Allocations in SemanticVersion.ParseSections()
SemanticVersion.ParseSections() allocates a System.Tuple to return the parsed elements to the caller. Switching to using out parameters will save about 7MB of allocated memory when opening OrchardCore.

### PR DESCRIPTION
**Pull request by Erarndt**
ValueTuple would have been a better drop-in replacement, but they didn't exist in net45

## Bug

Fixes: https://github.com/NuGet/Home/issues/11732

Regression? Last working version:

## Description
This saves ~7MB of allocations while doing SemVer parsing for OrchardCore.

image

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception - plenty of unit tests for these classes
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
LGTM. 

Can you please fill out the checklist and create an issue?

**Comment by Erarndt** [comment]
@nkolev92 I can. It doesn't look like there's a performance improvement category for issues. What type of issue do you want me to file?

**Comment by nkolev92** [comment]
Feel free to create a bug type or an empty issue.

We have a `Tenet:Performance` label to mark perf issues.

**Comment by Erarndt** [comment]
@nkolev92 Sorry for not updating this sooner. Did I miss anything?

**Comment by nkolev92** [comment]
@Erarndt 

Nope, nothing missing, I just didn't know it was done, I hadn't looked it again.

I've kicked off the CI and if it's green, I'll merge. 

Thanks for making the change!

**Comment by Erarndt** [comment]
@nkolev92 Oh, I had just gotten around to finishing it up, so it wasn't waiting on you. :)

**Comment by jeffkl** [comment]
@Erarndt your CI build is hitting some flaky test failures that we've since disabled or fixed.  Can you rebase and force push or let me know if you want me to do it.

**Review by jeffkl — APPROVED** [review]

**Pull request merged**
