### PR TITLE
Fixed update package list refresh issue

### PR DESCRIPTION
**Pull request by alpaix**
Fixes https://github.com/NuGet/Home/issues/2339.
- Needed more aggressive control over update package cache in the
  PackageManagerControl.
- Introduced a boolean parameter to force new search without using a
  cache.
- Disable cache on all system events like install/uninstall packages, etc.

### CODE REVIEW

**Comment by alpaix** [comment]
//cc @yishaigalatzer @emgarten @johnataylor

**Comment by yishaigalatzer** [comment]
@johnataylor 

overall LGTM, but my confidence about where to put true/false is low

**Comment by emgarten** [comment]
:shipit:

Is there any caching of the aggregate state, for example if 1 of 3 sources failed does it load cached results and look as if all 3 succeeded?

**Comment by alpaix** [comment]
@yishaigalatzer We should prioritize correctness over performance of course. In most of the cases useCache is to be false. Only when flipping tabs we can use the cache actually.

@emgarten Cache is populated for packages with updates only. I think we should consider expiring cache after certain time.

**Comment by johnataylor** [comment]
:shipit:

**Comment by rrelyea** [comment]
:shipit: 
Reviewed the true/false choices and discussed with alex.
3 trues are because we are doing a search.
1 true is because we switched tabs.
the falses all seem to make sense.

**Comment by alpaix** [comment]
Changed as agreed offline. 
Re-based and tested.

**Pull request merged**
