### PR TITLE
Update System.Text.Json and add docs about updating packages

### LINKED ISSUE #13857: System.Text.Json 8.0.4 has security vulnerability
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, NuGet SDK

### Product Version

latest

### Worked before?

_No response_

### Impact

None

### Repro Steps & Context

NuGet.Client references System.Text.Json 8.0.4: 
 https://github.com/NuGet/NuGet.Client/blob/fd6880078a435aa63fb1290e9bc58fb8dea6a4fd/Directory.Packages.props#L8

This version has a security vulnerability:  https://github.com/advisories/GHSA-8g4q-xg66-9fp4

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by zivkan**
# Bug

Fixes: https://github.com/NuGet/Home/issues/13857

## Description

* Update System.Text.Json to 8.0.5
* Add docs to explain why we can't always immediately update to the latest versions of certain packages
* Add comments to the two most impacted packages in Directory.Packages.props instructing the developer to read the docs before upgrading those two package versions.

## PR Checklist

- [x] Meaningful title, helpful description and a linked NuGet/Home issue
- [x] ~Added tests~ N/A
- [x] ~Link to an issue or pull request to update docs if this PR changes settings, environment variables, new feature, etc.~ N/A

### CODE REVIEW

**Review by jgonz120 — APPROVED** [review]

**Review by jeffkl — APPROVED** [review]
🥇

**Review by nkolev92 — APPROVED** [review]

**Comment by ericstj** [comment]
Which Version of VS and MSBuild do you require for this change?  Can you make sure you mention that and confirm it when making these changes in the future?

This mentions 17.10.4 -- but that's still using older System.Text.Json https://www.nuget.org/packages/Microsoft.Build/17.10.4#dependencies-body-tab

@ViktorHofer  @rainersigwald

**Comment by zivkan** [comment]
@ericstj at the time this PR was merged into the dev branch, NuGet was going into VS/MSBuild 17.13, and the 9.0.2xx .NET SDK. NuGet's insertion into both products, and their respective CI builds, were successful, which would have not been the case if those products were still using older versions of STJ. In fact, dnceng was late to make VS 17.13 previews available on Helix, and the .NET SDK team had to use a different Helix agent pool/image for tests to pass.

I hope that answers your question, because it's less than NuGet "depends" on MSBuild, but rather NuGet inserts into other products that also ship MSBuild.

**Comment by ericstj** [comment]
Yeah, I was just looking for some statement in the PR or in the changes that says "This change requires VS version XXX" - it can be helpful when seeing codeflow failures if things are running with older versions.  It can help identify which thing needs to change -- in this case we needed to get consuming repositories to update their version of VS used to build.

**Comment by nkolev92** [comment]
In a large number of cases, we end up tagging the commit with the first build number  that gets inserted. 

image

This tells us it's 6.13, matchig 17.13 (major is VS - 11, minor is always the same)

**Pull request merged**
