### PR TITLE
Address unhandled cast exception

### PR DESCRIPTION
**Pull request by awesley**
PackagesConfigNugetProject's ctor retrieves a value and attempts to cast it to type NugetFramework.  Values stored in the underlying dict<str, obj> are sometimes string, sometimes NugetFramework.  The dict is populated in an obtuse manner (as a property of a dynamic instantiated through Activator.CreateInstance) therefore it seemed safer to handle at retrieval.

## Bug
Fixes a part of https://github.com/NuGet/Home/issues/4491
Regression: Unknown
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: 
Handle casting from multiple types for multiple use cases meriting them.

## Testing/Validation
Tests Added: No
Reason for not adding tests:  Covered in existing unit tests
Validation done:  Checked out code, built, tested, made changes, built, tested, saw no regressions.  Manually verified through use case (packing a project with project-level references and verifying that they're included in resulting package) described in 4491 against netstandard2.0 .csproj and later netcoreapp2.0

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@awesley does this change allow you to pack netcore projects though? NuGet.exe is still not equipped to read PackageReferences though.

**Comment by awesley** [comment]
@rohit21agrawal I created a .Net Core Console app, added a .Net Core class library, used the build of NuGet.exe to pack the console app's csproj with -IncludeReferencedProjects, and the resulting package is what I expect.

My original tests were against netstandard2.0 rather than netcoreapp2.0, so that works too.  

To be 100% clear, here was my pack command: ```nuget pack ..\ConsoleApp2.csproj -IncludeReferencedProjects```

And the .csproj for ConsoleApp2:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>
</Project>

```

@rohit21agrawal  @rrelyea I see Apex Tests were canceled and 9648 failed.  I can't seem to access that.  Is there any way I can help with that?  I don't want to pollute this issue with process questions, so if there's some way I can help, please let me know.

**Comment by rohit21agrawal** [comment]
Project references will work fine, but if you have a package reference in csproj, that will be broken

**Comment by awesley** [comment]
I see, it forwards the referenced projects but NOT the referenced packages.  Misunderstood your earlier reply and thought it was still about project references.

**Comment by awesley** [comment]
In terms of addressing the package references (for some other pull request of course) .. We can look at how the JSON project format is handled in `ProjectJsonNuGetProject`, I think.  We can extend `BuildIntegratedNugetProject` to some new class, `ProbablyNetCoreNuGetProject` (please suggest a class name), override `GetInstalledPackagesAsync`.  Rather than `ProjectJsonNugetProject`'s 

```
public override async Task<IEnumerable<PackageReference>> GetInstalledPackagesAsync(CancellationToken token)
{
    var packages = new List<PackageReference>();

    //  Find all dependencies and convert them into packages.config style references
    foreach (var dependency in JsonConfigUtility.GetDependencies(await GetJsonAsync()))
    {
        // Use the minimum version of the range for the identity
        var identity = new PackageIdentity(dependency.Id, dependency.VersionRange.MinVersion);

        // Pass the actual version range as the allowed range
        packages.Add(new PackageReference(identity,
            targetFramework: null,
            userInstalled: true,
            developmentDependency: false,
            requireReinstallation: false,
            allowedVersions: dependency.VersionRange));
    }
```

We can do something like

```
public override async Task<IEnumerable<PackageReference>> GetInstalledPackagesAsync(CancellationToken token)
{
    var packages = new List<PackageReference>();

    //  Find all dependencies and convert them into packages.config style references
    foreach (var dependency in BuildIntegratedProjectUtility.GetDependencies(await GetProjectXml()))
    {
        // Use the minimum version of the range for the identity
        var identity = new PackageIdentity(dependency.Id, dependency.VersionRange.MinVersion);

        // Pass the actual version range as the allowed range
        packages.Add(new PackageReference(identity,
            targetFramework: null,
            userInstalled: true,
            developmentDependency: false,
            requireReinstallation: false,
            allowedVersions: dependency.VersionRange));
    }
```

Upstream, in `ProjectFactory.AddDependencies` we check if packages.config exists - instead let us abstract that out (perhaps based on the `TargetFramework.Identifier` - can you comment on a good way to make this decision) and then either call the existing logic (encapsulated in a new method, `AddDependenciesUsingPackagesConfig`) or the new logic (encapsulated in new method `AddDependenciesUsingBuildIntegratedProject`).

That leaves us with two tasks:
* `GetProjectXml()`
* Building some sort of `BuildIntegratedProjectReader` class which can actually build the `IEnumerable<PackageDependency>` from the Xml provided by `GetProjectXml()`

Are there existing implementations for anything like the two above?

**Comment by rohit21agrawal** [comment]
@awesley let's leave that part out for now, as there are a lot more things that need to be taken care of which I haven't investigated completely either.

**Comment by rohit21agrawal** [comment]
merging the partial fix here.

**Pull request merged**
