### PR TITLE
Use single package feed release-5.11.x

### PR DESCRIPTION
**Pull request by jeffkl**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/1990

Regression? Last working version:

## Description

* Cherry-pick of https://github.com/NuGet/NuGet.Client/commit/ea921bf1871b2799d9c130aad860db33e6577975
* Had to update the package version of Microsoft.Test.Apex.VisualStudio 

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — CHANGES_REQUESTED** [review]
I thought we want to do https://github.com/NuGet/NuGet.Client/pull/4923/files

**Comment by erdembayar** [comment]
> I thought we want to do https://github.com/NuGet/NuGet.Client/pull/4923/files

**Comment by erdembayar** [comment]
> > I thought we want to do https://github.com/NuGet/NuGet.Client/pull/4923/files

Sorry pressed "Close" by mistake. 
Does v5.11 support  `packageSourceMapping`? It looks we started from 6.0.0 https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping

**Comment by nkolev92** [comment]
> > > I thought we want to do https://github.com/NuGet/NuGet.Client/pull/4923/files
> 
> Sorry pressed "Close" by mistake. Does v5.11 support `packageSourceMapping`? It looks we started from 6.0.0 https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping

You're mixing the tooling version and the version of NuGet we're building.

**Comment by zivkan** [comment]
[We build nuget 5.11.x on VS2019 VMs](https://github.com/NuGet/NuGet.Client/blob/2378f64241e4e64d1f69754b16c1576acb56a467/eng/pipelines/templates/pipeline.yml#L87), so if package source mapping is only supported from NuGet 6 (dev17), it's still a relevant point.

**Comment by nkolev92** [comment]
Ah, I see. good point. I thought they had us move all of our builds to the newer versions.

**Review by zivkan — APPROVED** [review]
Unless we start building release-5.11.x on VS2022 machines, I don't have any better ideas than this PR.  While it would be nice to dogfood NuGet features (package source mapping), we're already doing it on the dev branch, so the release branch is probably fine to use a separate service to solve the problem 🤷

**Pull request closed without merging**
