### PR TITLE
Ignore guid retrieval failures when checking NuGet compatibility in VS. Assume incompatible with NuGet

### LINKED ISSUE #12009: VS2022 17.3.0 Preview 5 - NUGET Dialog / Package Manager not working for vdproj
Issue filled originally, https://developercommunity.visualstudio.com/t/VS2022-1730-Preview-5---NUGET-Dialog-/10107880. 

Internal feedback ticket [1584789](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1584789)

tldr; when you have vdproj, NuGet fails to load the projects so no restore can be run properly.

Dup of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1583229. 

Another feedback ticket is https://developercommunity.visualstudio.com/t/Operation-failed-No-projects-supported/10106471

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/12009

Regression? Last working version:

## Description

In https://github.com/NuGet/NuGet.Client/commit/a12891e5901e55985f023731eb87f705f2df73eb and https://github.com/NuGet/NuGet.Client/commit/e0db7dcd14807fd1f8874df18e9a7c7d9cd871f6, I rewrote the initialization to be done via IVsHierarchy instead of DTE.Project.

We used to discover the project guid via `Project.Kind`.
The equivalent for that in IVsHierarchy is `hierarchy.GetGuidProperty(VSConstants.VSITEMID_ROOT, (int)__VSHPROPID.VSHPROPID_TypeGuid, out Guid pguid);`

Unfortunately some project types, don't return that property, https://developercommunity.visualstudio.com/t/VS2022-1730-Preview-5---NUGET-Dialog-/10107880?viewtype=all, making NuGet unable to determine whether the project is compatible with NuGet. The project type in particular is vdproj, which isn't NuGet compatible anyways.

Currently we throw (expectation was that the property is always available). This changes assumes that projects that don't return that property are simply incompatible with NuGet. 
The project in question we found to be causing an issue is vdproj, so we're ok with the assume incompatible approach, but that doesn't mean it'd be good in every other case. 

~An alternative would be to convert the hierarchy to project check the Kind again. That is likely to be a more backwards compatible approach, but more of a maintenance annoyance.~

After consulting with some VS folks, this change is better  as we can't special case all special behaviors in project-systems.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception - This project system is only installed via an extension and does not come bundled with VS.
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by martinrrm — DISMISSED** [review]

**Review by dominoFire — DISMISSED** [review]
Signing-off. Is this validated manually or with existing unit tests with a sample .vdproj?

**Comment by nkolev92** [comment]
@dominoFire Only manually. I had to install the extension linked in the issue, https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects.

**Comment by nkolev92** [comment]
@dominoFire @martinrrm I'd appreciate another approval. I had to rebase, because I had conflicts with @martinrrm's change :D

**Review by dominoFire — APPROVED** [review]

**Comment by gywerd** [comment]
Apparently, this doesn't fix the problem. :'(

It creates a remove extension, reboot, reinstall extension, reboot, work fine, reboot, broken again cycle, as pointed out yeaterday by [Jason Baginski](https://developercommunity.visualstudio.com/user/2224/profile) in https://developercommunity.visualstudio.com/t/Operation-failed-No-projects-supported-/10106471
He suggests adding an environment value of NUGET_SOLUTION_CACHE_INITIALIZATION as 0 is the only workaround to keep it working post reboot.

**Comment by nkolev92** [comment]
@gywerd 

This change isn't available in a public release just yet. 
We'll provide updates in the tracking issue itself.

**Pull request merged**
