### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by AndreyAkinshin**

### CODE REVIEW

**Comment by nkolev92** [comment]
Thanks for creating this PR Andrey. Apologies for the overdue reply. 

Not confident how I feel yet about no-op changesets that touch 90 different files. 
Personally I think it messes with the history a bit too much, but would like to get thoughts from the rest of the team.

PS. There's some merge conflicts that need resolved.

**Comment by AndreyAkinshin** [comment]
@nkolev92 the conflicts are resolved.

**Comment by zivkan** [comment]
My thoughts: GitHub makes it easy to see a blame for a file, go the commit that last changed a particular line of code and if you decide it's unrelated to the bug you're investigating, look at the blame from the commit prior to the one that made that change. However, this slows down the process. But I personally rarely need to dig into the commit history to fix a bug, so the cost perhaps isn't that high.

My biggest concern with this PR is that it changes some of the parameter names on public methods of public classes and therefore is a breaking change to anyone who uses named parameters when calling methods (or certain uses of reflection, although this is not a significant concern to me). Does anyone know if this is considered a binary break? I imagine the .NET runtime cares only about types, not the name a parameter had when it was compiled vs the name in the loaded assembly, but it would be awful if we created a runtime failure just because we fixed a typo.

@AndreyAkinshin I find it hard to imagine that you manually found all these typos, so what tool did you use?  I typo more often than I care to admit, but I've only found tools to spell check strings and comments, but not camel cased or pascal cased variable names. It's been a while since I looked though.

**Comment by AndreyAkinshin** [comment]
@zivkan I use [JetBrains Rider](https://www.jetbrains.com/rider/). It highlights all the typos on the fly and it allows getting the full list of typos for a given scope.

**Pull request closed without merging**
