### PR TITLE
Remove CA1814 supressions

### PR DESCRIPTION
**Pull request by heng-liu**
## Bug

Fixes:https://github.com/nuget/client.engineering/issues/1183

Regression? Last working version:

## Description

According to [comment](https://github.com/nuget/client.engineering/issues/1183#issuecomment-932500476), the code has been changed after the baseline has been generated. So this is just removing entries from the GlobalSuppressions.cs file.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
Would you mind ground through all the GlobalSuppressions files and cleaning off the ones that do not apply anymore?

Keep in mind, that some are framework specific? 

I'm ok if you don't do that and prefer to keep the small PR. My comment is largely because it's not really a functional change.

**Comment by heng-liu** [comment]
I guess going through all the GlobalSuppressions files and cleaning off the ones means we need to run another baseline, right? As I don't think this could be done manually. Hi @kartheekp-ms , do you have any suggestions? Thanks!

**Comment by nkolev92** [comment]
> I guess going through all the GlobalSuppressions files and cleaning off the ones means we need to run another baseline, right? As I don't think this could be done manually.

I don't think you need to rerun a new baseline. You're not *adding* new warnings that need to be baselined.

You can just remove the ones that don't apply. 
If you are in VS, they'll be greyed out because they're not necessary.

**Comment by nkolev92** [comment]
example

See example.

The greyed out can be removed. You'd need to make sure you check the framework (as some are framework specific) when you remove them.

**Comment by heng-liu** [comment]
Thanks @nkolev92! I'll clean all the others in this PR then.

**Pull request closed without merging**
