### PR TITLE
Remove special version check from nuget pack

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/NuGet/Home/issues/2735

### CODE REVIEW

**Comment by emgarten** [comment]
Yes please :smile:  Does the gallery actually support long release labels?

**Comment by pranavkm** [comment]
They seem to have a max length of 64 chars:
- https://github.com/NuGet/NuGetGallery/blob/ed5cfaf950e3de9e282203f92a68661044518946/src/NuGetGallery.Core/Entities/Package.cs#L130, 
- https://github.com/NuGet/NuGetGallery/blob/ed5cfaf950e3de9e282203f92a68661044518946/src/NuGetGallery.Core/Entities/Package.cs#L137

**Comment by pranavkm** [comment]
cc @xavierdecoster for gallery impact. That said, it's never a good idea to rely on nuget.exe to enforce any behavior.

**Comment by xavierdecoster** [comment]
cc @yishaigalatzer 

If I remember correctly, the version length limitation was there mostly because of the impact on the file system client-side when extracting the packages? 

On the other hand, we do need _some_ max length on this field to be able to keep the unique, non-clustered index on the version column of the Packages table in the gallery database.
Currently, that column is of type `nvarchar(64)`, which has a storage length of `128 bytes`. This index combines the version column with the `PackageRegistrationKey` column of type `int`, so the storage length of the index is 128 + 4 = `132 bytes in total`.

The total storage length of this index should remain below 900 bytes to ensure no INSERT or UPDATE statements against the Packages table fail. (see https://technet.microsoft.com/en-us/library/ms191241(v=sql.105).aspx). Which means only 896 bytes can be used for storing the version field; or _maximum 448 unicode characters_.

Not sure if there are other indices that could be impacted by this change, but before diving deeper, what would be the desired max version length?

**Comment by pranavkm** [comment]
@xavierdecoster - the `Version` field on the gallery has a `StringLength(64)`. It's perfectly fine for the server to have this limitation, just not have the client impose a length restriction.

**Comment by yishaigalatzer** [comment]
Please block this fix and do not merge it. We need to triage and make a decision first. Without windows fixing path length this will quickly get out of hand

**Comment by yishaigalatzer** [comment]
No need to close, just need to triage and discuss

**Comment by pranavkm** [comment]
Ahh, ok

**Comment by emgarten** [comment]
NuGet/NuGet.Client@219b3e2356a64ffb9f4422f07472a48aa6e6a619

**Pull request closed without merging**
