### PR TITLE
Make the pack test PackCommand_PackProject_AddsProjectRefsAsPackageRefs, target framework independent

### LINKED ISSUE #9892: PackCommand_PackProject_AddsProjectRefsAsPackageRefs is failing on latest dev
See https://github.com/NuGet/NuGet.Client/commit/1756c520d5bdd9d540b1b9accf6c88a2339759cf#commitcomment-41350318

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/9892
Regression: Yes/No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: This test is framework dependent, so it will look for an exact template.
We want our tests to remain offline so changing the assets to make it framework independent. 

## Testing/Validation

Tests Added: No, fixing a test  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Review by rrelyea — APPROVED** [review]

**Comment by heng-liu** [comment]
May I know what change makes it start to fail? Thanks.

**Comment by nkolev92** [comment]
@rrelyea thinks it's https://github.com/NuGet/NuGet.Client/commit/1756c520d5bdd9d540b1b9accf6c88a2339759cf#commitcomment-41350318 and I think it makes sense. 

It's likely because the template is not disk when we stop installing the 3.1 SDK.

**Review by zivkan — APPROVED** [review]

**Comment by rrelyea** [comment]
This doesn't fail 100%. I've had 1 successful build of that same branch. And another failure...  So more than 50% failures.

**Comment by rrelyea** [comment]
@nkolev92 - hope you don't mind me merging this. want my dev build to pass in a few hours.

**Pull request merged**
