### PR TITLE
Introduce a --exclude-project option to list command

### LINKED ISSUE #12585: dotnet list package --format json --include-transitive includes project references as transitive packages.
### NuGet Product Used

dotnet.exe

### Product Version

7.0.203

### Worked before?

no

### Impact

It's more difficult to complete my work

### Repro Steps & Context

If I have a project that references another project, then the beforementioned command states that referenced project is a transitive package dependency for referencing project.

I'm not sure if this is really bug, perhaps it's just a need of some differentiation between project and package in output, for example, additional "type" property in "transitivePackages" node item, saying if it's a "Project" reference or a "Package".

Steps to reproduce:
1. Download the archive from attachment and unpack it somewhere
2. Run dotnet restore in unpacked folder
3. Run dotnet list package --format json --include-transitive

The output says that "DotnetListJsonTransitivesIssue" project has "ReferencedProject" in its transitive packages (or at least doesn't provide an information if this is really a package from some nuget source or just a project). 

Also, if it should include projects in output, in this very case the "ReferencedProject" should be within the "topLevelPackages" node

[DotnetListJsonTransitivesIssue.zip](https://github.com/NuGet/Home/files/11465827/DotnetListJsonTransitivesIssue.zip)

### Verbose Logs

```shell
{
  "version": 1,
  "parameters": "--include-transitive",
  "projects": [
    {
      "path": "C:/Users/User/source/repos/exp/DotnetListJsonTransitivesIssue/DotnetListJsonTransitivesIssue/DotnetListJsonTransitivesIssue.csproj",
      "frameworks": [
        {
          "framework": "net7.0",
          "transitivePackages": [
            {
              "id": "ReferencedProject",
              "resolvedVersion": "1.0.0"
            }
          ]
        }
      ]
    },
    {
      "path": "C:/Users/User/source/repos/exp/DotnetListJsonTransitivesIssue/ReferencedProject/ReferencedProject.csproj",
      "frameworks": [
        {
          "framework": "net7.0"
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by Greybird**
## Bug

Fixes: https://github.com/NuGet/Home/issues/12585

Regression? Last working version:

## Description
`list` command behaves differently depending on the presence of the `--deprecated`, `--outdated`, or `--vulnerable` flag:
* if any of these flags is present, projects are filtered out of transitive dependencies,
* if not, projects are kept in the transitive dependencies.

As 
* filtering the projects out of the list of transitive dependencies is only dependent on the type of reports requested (see [ListPackageCommandRunner](https://github.com/NuGet/NuGet.Client/blob/d9d5a38c6e0c3ccc36b1b21cb8fa468474690080/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/ListPackageCommandRunner.cs#L118C157-L118C222)),
* the output (console, json, or other) does not display the type of dependency (it is lost during the model construction in [GetResolvedVersion](https://github.com/NuGet/NuGet.Client/blob/d9d5a38c6e0c3ccc36b1b21cb8fa468474690080/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs#L658C49-L658C68), not being included in [FrameworkPackages](https://github.com/NuGet/NuGet.Client/blob/d9d5a38c6e0c3ccc36b1b21cb8fa468474690080/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/FrameworkPackages.cs#L13-L45)/[InstalledPackageReference](https://github.com/NuGet/NuGet.Client/blob/d9d5a38c6e0c3ccc36b1b21cb8fa468474690080/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/InstalledPackageReference.cs#L17-L33))
there is in practice no way to request a complete list of _actual_ nuget packages.

I have no context on why the `list` command reports projects as transitive dependencies, but it is a fairly common need to only list nuget packages, to automate some process related to them. I tend to think that this is also a very common expectation for the command. The inability to filter projects adds noise to the output in these cases.

This PR adds a `--exclude-project` flag, allowing to override the behavior of the command when no `--deprecated`, `--outdated`, or `--vulnerable` flag is passed (a warning is reported if any of these flags is passed with `--exclude-project`), to actually alter the default project filtering behavior.

I don't think manual documentation is needed as I did not find documentation for `--include-transitive`. Should I be wrong, please tell me.
I'm unsure about the need for a design proposal. If needed, I'll be happy to fill one.

## PR Checklist

- [X] PR has a meaningful title
- [X] PR has a linked issue.
- [X] Described changes

- **Tests**
  - [X] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [X] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
Hey @Greybird, given that this is a feature, do you mind writing up a quick spec about this? 
https://github.com/NuGet/Home/blob/dev/meta/README.md

It doesn't have to be extremely detailed, but for additions like this, we do need a buy-off first.

**Comment by erdembayar** [comment]
> Hey @Greybird, given that this is a feature, do you mind writing up a quick spec about this? https://github.com/NuGet/Home/blob/dev/meta/README.md
> 
> It doesn't have to be extremely detailed, but for additions like this, we do need a buy-off first.

You can find many examples here: https://github.com/NuGet/Home/tree/dev/proposed
For example https://github.com/NuGet/Home/blob/dev/proposed/2022/DotnetListPackageMachineReadableJsonOutput.md is very close to what you're doing.

**Comment by Greybird** [comment]
@nkolev92 , @erdembayar , thanks, and sure, I'll give it a try!

**Comment by Greybird** [comment]
Hi @nkolev92 , @erdembayar , you can take a look at my proposal here: https://github.com/NuGet/Home/pull/12735.
Feel free to ask for any change or other actions.
Thanks for your time!

**Review by nkolev92 — CHANGES_REQUESTED** [review]
Please refer to my review in https://github.com/NuGet/Home/pull/12735. 

This is likely unnecessary, https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs#L781-L783. 

@NuGet/nuget-client If I got it wrong, feel free to dismiss my review.

**Comment by aortiz-msft** [comment]
@martinrrm  - Would you please take a look?

**Comment by ghost** [comment]
This PR has been automatically marked as stale because it has no activity for **7 days**. It will be closed if no further activity occurs **within another 90 days** of this comment. If it is closed, you may reopen it anytime when you're ready again, as long as you don't delete the branch.

**Comment by martinrrm** [comment]
Closing this PR, we decided that this is an actual bug in the code, @Greybird created a new PR for that fix in https://github.com/NuGet/NuGet.Client/pull/5335

**Pull request closed without merging**
