### PR TITLE
remove check for nugetrecommendpkgs 17.2

### PR DESCRIPTION
**Pull request by birgithi**
## Bug
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1591511
https://github.com/NuGet/Home/issues/12026

Fixes:
We will end the nugetrecommendpkgs flight after 17.4 GA, so we need to remove the code that checks for this flight.

Regression? Last working version:
Currently working as expected, but will stop working without this fix after we end the nugetrecommendpkgs flight.

## Description
Remove code that checks for nugetrecommendpkgs flight

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by erdembayar** [comment]
It looks you're missing 1 change you made from https://github.com/NuGet/NuGet.Client/pull/4728, not sure if it's intentional. 
Do we need below change too?

https://github.com/NuGet/NuGet.Client/blob/6be36bba3580a7ff195490e8f10c89fcf4538217/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/NuGetPackageSearchService.cs#L474-L489

**Comment by birgithi** [comment]
I only included the changes required to no longer check for the nugetrecommendpkgs flight. 
I can include this fix as well if that is preferred.

**Comment by nkolev92** [comment]
Maybe @aortiz-msft can help us make that call. 

I don't think it'd be the worst idea to include that part as well, but it isn't necessary for our overall goal here.

**Comment by heng-liu** [comment]
Hi @birgithi , may I know if customer is going to encounter any issues without the fix(the try catch) @erdembayar mentioned above? E.g. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1527078 or https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1547720 
BTW, could help rebase your branch to the latest release branches accordingly? (release-6.2.x for this PR) 
Or, you may enable the setting on this PR by following the steps here: [allowing-changes-to-a-pull-request-branch-created-from-a-fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). So that we will have the permission to rebase.
Thank you!

**Comment by birgithi** [comment]
Hi @heng-liu, the try-catch fixes an issue where the user gets an error message in the Package Manager. This only affects users who manually disabled the NuGet Recommender through the Extension Manager.
All of the pull requests have the 'Allow edits by maintainers' box checked.

**Review by zivkan — APPROVED** [review]

**Pull request merged**
