### PR TITLE
Allow client to specify which tab they'd like selected when they open package manager with a search query.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @joelverhagen  
Joel, here's the approach i was thinking of taking.  It's pretty simple and easy to do, and would enable our scenario if you guys aren't able to provide an actual API to do this in Update2.

**Comment by yishaigalatzer** [comment]
This thing needs spec-ing and some thought. Right now I don't want to spend ANY time on this, we got lots of stuff to finish for RTM that is truly blocking our end users, this one is not. Parking it for 3.5, and we are going to ignore it for now.

**Comment by yishaigalatzer** [comment]
Closing because we decided we are not taking for this release, and we will probably do a proper top level API in the next release

**Pull request closed without merging**
