### PR TITLE
Fixed german translation typo in help command

### PR DESCRIPTION
**Pull request by dbeuchler**
Just fixed a typo in the german translation of the help command

### CODE REVIEW

**Comment by emgarten** [comment]
@mishra14 are these strings still being updated by an external process?

**Comment by mishra14** [comment]
@emgarten not the nuget.exe commandline ones. These are fixed resources.

**Comment by nkolev92** [comment]
@dbeuchler Can you please edit this in VS and commit add the respective Designer file.

**Review by emgarten — APPROVED** [review]

**Comment by emgarten** [comment]
Thanks for the fix @dbeuchler! 🚀

**Pull request merged**
