### PR TITLE
Clarify that "PowerShell" is "Developer PowerShell" in readme

### LINKED ISSUE #11151: [Bug]: Indicate Developer PowerShell for Visual Studio in contributing documentation
### NuGet Product Used

NuGet.exe

### Product Version

documentation

### Worked before?

_No response_

### Impact

Other

### Repro Steps & Context

https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md indicates using PowerShell, and would do better to indicate using Developer PowerShell for Visual Studio.

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by drewgillies**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11151

Regression? Last working version:

## Description
Documentation says to use PowerShell and should indicate Developer PowerShell for Visual Studio is required.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by zivkan** [comment]
It doesn't need to be Developer PowerShell. If msbuild can't be found on the path it uses vswhere to locate it: https://github.com/NuGet/NuGet.Client/blob/cb290a427545a9214f22d9d6196c9e3c81380611/build/common.ps1#L309

**Comment by drewgillies** [comment]
> It doesn't need to be Developer PowerShell. If msbuild can't be found on the path it uses vswhere to locate it

@zivkan Thanks. It would be helpful to have some troubleshooting steps in the readme, perhaps, for when it's not found.

**Comment by zivkan** [comment]
@drewgillies It's a good idea to have troubleshooting guide for when it doesn't work, except I'm not sure why it wouldn't work. 

vswhere should always be at that location, even if VS2022 is the only VS installed (VS2022 being 64-bit gets installed to "Program Files", not "Program Files (x86)", but VSInstaller still gets installed to "Program Files (x86)", meaning the location should be static.

I'm not sure why vswhere would fail, and the script is using [the recommended arguments by vswhere itself](https://github.com/microsoft/vswhere/wiki/Find-MSBuild#powershell).

Do you have any idea why it was failing for you? If we understand that, we can either add troubleshooting guide, or improve the script.

**Comment by drewgillies** [comment]
@zivkan This is the error:
```
C:\Work\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.OnlineEnvironment.Client\NuGet.VisualStudio.OnlineEnvironment.Client.csproj(101,11): error MSB4226: The imported project "C:\VisualStudio\master\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Mic
rosoft.VsSDK.targets" was not found. Also, tried to find "VSSDK\Microsoft.VsSDK.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths are defined in "C:\Visual
Studio\master\MSBuild\Current\bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
```

I saw another dev in the client Teams channel had the same error (look at 5/6/2020) and the suggested fix there was to use Developer Powershell. It was indeed the fix, as it was for me. :)

**Pull request closed without merging**
