### PR TITLE
issue

### PR DESCRIPTION
**Pull request by dslzuha**
## Bug

Fixes: Link_to_issue  
Regression: Yes/No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Details_about_the_fix  

## Testing/Validation

Tests Added: Yes/No  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Review by dslzuha — COMMENTED** [review]
Thanks

**Comment by nkolev92** [comment]
@dslzuha 

Please create an issue for every PR you submit. 

Can you elaborate what you are trying to do here? 

NuGet already has a yaml for our azure builds. 
https://github.com/NuGet/NuGet.Client/blob/dev/build/vsts_build.yaml

**Comment by rrelyea** [comment]
You seem to be opening a number of PRs in our repo without significant changes. Perhaps you are learning to use GitHub and did not intend to send them to us. Please be aware that other people may be working in repos you do not own, so if you are testing, we suggest you create your own repo and follow steps similar to this: https://guides.github.com/activities/hello-world/

If you are hoping to contribute to nuget.client repro, please make sure to read https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md guidelines and start with step 1 (open an issue), not step 5 (open a PR).

**Comment by dslzuha** [comment]
> 
> 
> @dslzuha
> 
> Please create an issue for every PR you submit.
> 
> Can you elaborate what you are trying to do here?
> 
> NuGet already has a yaml for our azure builds.
> https://github.com/NuGet/NuGet.Client/blob/dev/build/vsts_build.yaml

@nkolev92  and @rrelyea Thanks

**Pull request closed without merging**
