### PR TITLE
allow empty sb intermediate

### PR DESCRIPTION
**Pull request by oleksandr-didyk**
## Bug

Fixes: https://github.com/dotnet/arcade/pull/13126

Regression? Last working version:

## Description

Resolves an issue with NuGet source-build intermediate originally found by https://github.com/dotnet/arcade/pull/13067. This is achieved by introducing and empty intermediate check in source-build infra and allowing this repository to produce an empty intermediate until https://github.com/NuGet/Home/issues/11059 is resolved.
.
## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by jeffkl — APPROVED** [review]

**Comment by nkolev92** [comment]
@oleksandr-didyk 

Can you please follow the PR template. Thanks!

**Comment by martinrrm** [comment]
@oleksandr-didyk Can you do a rebase to the latest commit of dev? Sorry, we had a problem in our CI that is fixed now. Thanks!

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk Can you do a rebase to the latest commit of dev? Sorry, we had a problem in our CI that is fixed now. Thanks!

No problem, rebased

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk
> 
> Can you please follow the PR template. Thanks!

My bad, should be fixed now

**Review by nkolev92 — APPROVED** [review]

**Pull request merged**
