### PR TITLE
Extend default plugin timeouts per #11793

### LINKED ISSUE #11793: [DCR]: Plugin timeout defaults should be increased
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe, NuGet SDK

### Current Behavior

Currently the handshake and response timeouts for plugins default to 5 seconds. While this should theoretically be long enough, in practice we've had to give our customers instructions to increase those timeouts with environment variables a fairly large number of times. I believe our plugin is starting quickly, but it's possible that NuGet is not observing the response in time.

### Desired Behavior

We've been giving 20-30 seconds in our guidance, and that seems to be sufficient.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by johnterickson**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11793

Regression? No

## Description
Plugin timeout defaults are increased from 5 seconds to 30 seconds based on discussion in issue https://github.com/NuGet/Home/issues/11793 and https://github.com/NuGet/Home/issues/8528#issuecomment-532885684

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by johnterickson** [comment]
If this looks good, we should also apply to servicing branches.

**Review by nkolev92 — DISMISSED** [review]

**Comment by nkolev92** [comment]
Thanks for creating this PR @johnterickson 

It'd be great if you can reach out to Arturo for servicing considerations.
cc @aortiz-msft

**Comment by johnterickson** [comment]
@nkolev92 Could you reapprove now that I fixed the test regex?

**Review by nkolev92 — APPROVED** [review]

**Comment by johnterickson** [comment]
@nkolev92 Looks ready to merge. Anything else?

**Pull request merged**
