### PR TITLE
Fixes CI test failure

### PR DESCRIPTION
**Pull request by deepakaravindr**
@yishaigalatzer @emgarten @zhili1208

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
The change looks good, but what triggered it?

**Comment by emgarten** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
@yishaigalatzer https://github.com/NuGet/NuGet.Client/commit/cab0a550e89006290290ed74ecba422282455381

**Comment by yishaigalatzer** [comment]
:shipit:

**Comment by xavierdecoster** [comment]
:shipit:
Shouldn't I receive an alert from the CI that my change broke something?
Thanks for the fix!

**Comment by deepakaravindr** [comment]
@xavierdecoster, Good point! I thought Teamcity was configured. I have filed an issue in the Engineering repo to track it

Merged and closed with https://github.com/NuGet/NuGet.Client/commit/de3c20e50c0de2fd89640cd40e51cf050e65e0ae

**Pull request closed without merging**
