### PR TITLE
Set IsPackable to false by default for test projects

### PR DESCRIPTION
**Pull request by natemcmaster**
Companion PR to https://github.com/Microsoft/vstest/pull/440

Goal: make it easier to call "dotnet pack" on a solution file.

cc @rohit21agrawal

### CODE REVIEW

**Review by rohit21agrawal — APPROVED** [review]

**Comment by rohit21agrawal** [comment]
@natemcmaster why can't you do this your test templates?

**Comment by natemcmaster** [comment]
We could, but it seems like a smarter default to assume that if a user reference Microsoft.NET.Sdk.Test that they aren't producing nuget packages from that project.

**Comment by rohit21agrawal** [comment]
I would lean towards not putting any project specific properties in Pack.Targets

**Comment by natemcmaster** [comment]
Can you clarify what you mean by "project specific properties"? Isn't every property project-specific?

**Comment by natemcmaster** [comment]
🔔  is this something we can get in for RTW? cref https://github.com/Microsoft/vstest/pull/440

**Comment by rohit21agrawal** [comment]
@rrelyea can take that call

**Comment by rrelyea** [comment]
@natemcmaster -
This PR doesn't try to give any justification.
Would need to justify why 4.0.0 fix is critical?

**Comment by natemcmaster** [comment]
The goal is to make it easier to call "dotnet pack" on a solution file. This makes the default smarter about test projects. I've never seen a test project (defined as one that references Microsoft.NET.Test.Sdk) that was intended for distribution as a nupkg.

**Comment by emgarten** [comment]
:bell: @rohit21agrawal can you merge this if it is still needed?

**Comment by natemcmaster** [comment]
Ping @rohit21agrawal

**Comment by natemcmaster** [comment]
Thanks :)

**Comment by dasMulli** [comment]
~Actually.. can we undo that and instead define that project models shall decide whether or not a project is packable?~

NuGet integration seems integral to the "core" build logic.
.NET <> NuGet < Project&Application models (console, lib, ASP.NET Core, UWP, Tests, …).

In that thinking, the decision whether it is a good idea to pack projects using that model should be left to the build logic of said model and not NuGet hard-coding knowledge about all possible models..

**Comment by dasMulli** [comment]
cc @onovotny @bradwilson

**Comment by bradwilson** [comment]
The decision to pack unit test projects or not by default is obviously correct as-is. Non-packing is the 99.999999999999999% case.

**Comment by dasMulli** [comment]
yeah, probably not worth any effort.

**Pull request merged**
