### PR TITLE
IVsSolutionRestoreService4 extends IVsSolutionRestoreService3

### LINKED ISSUE #11098: IVsSolutionRestoreService4 should extend IVsSolutionRestoreService3
@davkean requested that `IVsSolutionRestoreService4` should extend, or re-implement all the methods from `IVsSolutionRestoreService3`. This avoids needing to MEF import two interfaces.

While `IVsSolutionRestoreService3` and `IVsSolutionRestoreService2` do not extend the lower numbered interfaces, they are used independently. Anyone using `IVsSolutionRestoreService3` will not be using `IVsSolutionRestoreService`. However, anyone using `IVsSolutionRestoreService4` must also use `IVsSolutionRestoreService3`, it cannot be used independently. Technically, a caller using `IVsSolutionRestoreService4` could use `IVsSolutionRestoreService`, but `IVsSolutionRestoreService3` is a superset to support additional properties, so the older interface should probably be deprecated (but is out of scope for this issue).

Using MEF is different to using VS services (`GetService<T1, T2>()`), where you get the implementation of the service and then cast it to the interface, so VS's COM interfaces that do not (always) extend older interfaces is a different scenario, so should not be taken as precedent.

/cc @nkolev92 @ocallesp

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11098

Regression? Last working version:

## Description

This change allows the consumers to use only 1 MEF import instead of 2. 

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception - Not really something that can be tested.
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A - https://github.com/NuGet/docs.microsoft.com-nuget/issues/2435 already created.

### CODE REVIEW

**Comment by nkolev92** [comment]
cc @davkean @ocallesp

**Comment by nkolev92** [comment]
Given that only NuGet implements this API, there shouldn't be any runtime issues with this change.

**Review by erdembayar — APPROVED** [review]

**Comment by kartheekp-ms** [comment]
I have couple of questions on this PR.

1. Does `VsSolutionRestoreService` need to implement `IVsSolutionRestoreService3` and `IVsSolutionRestoreService4` interfaces?
https://github.com/NuGet/NuGet.Client/blob/77baa1563bb5aa8726bcf0f54d913ebe71e657ee/src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs#L31-L41

2. Do we need to export `IVsSolutionRestoreService3` as MEF component?

**Review by zivkan — APPROVED** [review]

**Comment by nkolev92** [comment]
@kartheekp-ms 
> I have couple of questions on this PR.
> 
> 1. Does `VsSolutionRestoreService` need to implement `IVsSolutionRestoreService3` and `IVsSolutionRestoreService4` interfaces?
>    https://github.com/NuGet/NuGet.Client/blob/77baa1563bb5aa8726bcf0f54d913ebe71e657ee/src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs#L31-L41
> 2. Do we need to export `IVsSolutionRestoreService3` as MEF component?

1. Yes. Both have shipped and both should be supported. They are largely equivalent anyways.
2. Yes. See above.

**Comment by nkolev92** [comment]
@ocallesp Merged, but not yet inserted.

**Pull request merged**
