### PR TITLE
Update NuGet.CommandLine.nuspec to add repo url

### PR DESCRIPTION
**Pull request by anangaur**
## Bug
Fixes: Link_to_issue  
Regression: Yes/No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: Details_about the_fix  

## Testing/Validation
Tests Added: Yes/No  
Reason for not adding tests:  
Validation done:

### CODE REVIEW

**Review by rohit21agrawal — APPROVED** [review]

**Review by jainaashish — APPROVED** [review]

**Comment by jainaashish** [comment]
btw should this repo url be set for all nuget.* packages as well?

**Comment by anangaur** [comment]
Yes, for better discoverability of code.

**Comment by nkolev92** [comment]
@jainaashish 
That's already happening through pdbgit.

**Comment by rohit21agrawal** [comment]
@anangaur please squash and merge in the future

**Pull request merged**
