### PR TITLE
Replaced custom locking mechanism with framework implementation

### PR DESCRIPTION
**Pull request by kartheekp-ms**
## Bug

Fixes: /NuGet/Home#8740
Regression: No  

## Fix

Details: object is always locked even-though `PackageSourceProvider` instance is already initialized in the current implementation.Learnt from this [doc](https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/mscorlib/system/threading/LazyInitializer.cs#L197) that there is a .NET framework implementation to accomplish the same logic. Hence replaced custom locking mechanism code with framework API.

## Testing/Validation

Tests Added: No  
Reason for not adding tests: Tests are not added because of the nature of the fix. 
Validation: Telemetry data has to be analyzed to test the accuracy of this fix once the code ships in the upcoming preview release.

### CODE REVIEW

**Review by zivkan — APPROVED** [review]

**Review by nkolev92 — COMMENTED** [review]
How does this change address https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959481?

**Comment by kartheekp-ms** [comment]
> How does this change address https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959481?

I was about to create a separate issue for [this](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959481) bug because it requires working with ASP.NET team.

**Review by nkolev92 — COMMENTED** [review]
While this is a good change, I don't believe it will fully fix the delay. 

If you look at the stack you see the following: 


nuget.packagemanagement.visualstudio.dll!NuGet.PackageManagement.VisualStudio.ExtensibleSourceRepositoryProvider.EnsureInitialized | 79.957%
-- | --
mscorlib.dll!System.Lazy`[System.__Canon].get_Value | 67.241%
clr.dll!ThePreStub

The majority of the time is the lazy, which is probably the settings initialization.

**edit**: 

My suggestion, create a separate issue to fix the lock and consider that issue addressed by this change. 
Create a tracking issue to fix this pattern in other places (I think there are some other initializations which rely on a similar pattern).

**Comment by kartheekp-ms** [comment]
> Create a tracking issue to fix this pattern in other places (I think there are some other initializations which rely on a similar pattern).

Created /NuGet/Home#8738 to track other initializations which rely on a similar pattern by locking the object even-though the target type is initialized.

**Comment by kartheekp-ms** [comment]
> My suggestion, create a separate issue to fix the lock and consider that issue addressed by this change.

Linked this PR to /NuGet/home#8740 issue.

**Review by nkolev92 — APPROVED** [review]

**Pull request merged**
