### PR TITLE
added Null check in IsSolutionFullyLoaded

### PR DESCRIPTION
**Pull request by zhili1208**
NuGet/Home#4485

### CODE REVIEW

**Review by alpaix — APPROVED** [review]
LGTM

**Review by jainaashish — APPROVED** [review]

**Comment by mishra14** [comment]
@zhili1208 why is this not merged in?

**Comment by zhili1208** [comment]
@mishra14 not approve yet

**Comment by emgarten** [comment]
@zhili1208 please re-open if this active. Given that it is almost a year old I am going to close this out.

**Pull request closed without merging**
