### PR TITLE
Add Xamarin.Mac.NET (xamarinmacnet)

### PR DESCRIPTION
**Pull request by joelverhagen**
Address NuGet/Home#2662
- Add `xamarinmacnet` TFM.
- `xamarinmacnet` supports `net45`, `xamarinmac`, `dotnet5.6`, and `netstandard1.6`.
- `xamarinmacnet` prefers `xamarinmac` over `net45` when both are available.

@emgarten @rrelyea @yishaigalatzer @chamons @mteper @ericstj

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by joelverhagen** [comment]
Hey @ghuntley, before making this change, I'd like to understand the scenario a little more. I have some additional questions on the issue:
https://github.com/NuGet/Home/issues/2662

**Comment by emgarten** [comment]
🔔 Does this still need to go in or should it be closed?

**Comment by ghuntley** [comment]
Still blocked by https://github.com/NuGet/Home/issues/2662

**Comment by ghuntley** [comment]
Paging @mhutch as per her comments at https://github.com/NuGet/Home/issues/2662#issuecomment-218925157

**Comment by emgarten** [comment]
@joelverhagen any updates on this?

//cc @mishra14

**Comment by joelverhagen** [comment]
@rrelyea is going to working with someone on client team to push this through. See https://github.com/NuGet/Home/issues/2662#issuecomment-284064145.

**Comment by mishra14** [comment]
Closing this PR as there has been no traction from the Xamarin folks. This can be reopened, if needed.

**Comment by chamons** [comment]
@rrelyea @joelverhagen @mishra14 What work on the Xamarin side needs to be done? To our knowledge, it got handed off via:

```@rrelyea is going to working with someone on client team to push this through. See NuGet/Home#2662 (comment).```

**Comment by chamons** [comment]
Please consider reopening, this is not fixed or forgotten.

**Comment by emgarten** [comment]
@chamons will you open a new PR and bring this up to date?

I'm still unclear on the hold up here, but the codebased has changed in 1.5 years and this change likely needs some work to sync it up.

**Comment by mrward** [comment]
I am planning to resurrect this fix and rebase it on the latest code, just not had chance to look at it yet.

**Comment by joelverhagen** [comment]
Hey @mrward, is this visible to you?
https://github.com/NuGet/NuGet.Client/pull/562/files

**Comment by mrward** [comment]
@joelverhagen - Yeah I can see the files from the pull request. I saw the branch was deleted so I thought the changes were gone but they are still available 👍

**Comment by joelverhagen** [comment]
I've restored the branch -- hope it helps.

**Comment by mattleibow** [comment]
Reopened this with https://github.com/NuGet/NuGet.Client/pull/2572

**Pull request closed without merging**
