### PR TITLE
Move uap and netcore50 down to netstandard1.4

### PR DESCRIPTION
**Pull request by joelverhagen**
https://github.com/NuGet/Home/issues/2273

@ericstj @emgarten @yishaigalatzer

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by ericstj** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM Do we think this is going to make it into the Nuget 3.4 release?

**Comment by yishaigalatzer** [comment]
Yes

**Pull request merged**
