### PR TITLE
1) Moved Test.Utility folder under the src folder to the test folder …

### PR DESCRIPTION
**Pull request by deepakaravindr**
…tree.

2) Enabled all the tests in NuGet.Core.Tests that were disabled because of signing reason.

@MeniZalzman @yishaigalatzer @emgarten @feiling @zhili1208

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by zhili1208** [comment]
:shipit:

**Comment by MeniZalzman** [comment]
:watch: @deepakaravindr As discuss please wait with this merge until we validate that the commandline test is passing

**Comment by deepakaravindr** [comment]
@MeniZalzman. Yes, I will not merge yet. I will verify and update this PR shortly

**Comment by deepakaravindr** [comment]
@yishaigalatzer  @MeniZalzman @emgarten 

Still, I have issues running a delay signed build locally. However, I ran a full (unsigned) build locally which runs all the tests and that passed.

I will check-in to dev branch and monitor the dev branch build closely.
If there is a build break, I will immediately revert the top commit alone from this PR to make the build pass. Top commit is where the disabled tests from NuGet.CommandLine have been enabled.

**Pull request merged**
