### PR TITLE
Add a documentation validator tool

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/196

Regression? Last working version:

## Description

An example output is: 

```
 dotnet run .\DocumentationValidator.csproj
Checking 172 log codes for documentation.
Checked 20 of 172
Checked 40 of 172
Checked 60 of 172
Checked 80 of 172
Checked 100 of 172
Checked 120 of 172
Checked 140 of 172
Checked 160 of 172
Completed checking log codes for documentation.
Undocumented Log Codes Count 27
NU1004
NU1005
NU1006
NU1007
NU1008
NU1009
NU1010
NU1011
NU1012
NU1109
NU1204
NU1211
NU1212
NU1213
NU1402
NU1403
NU1410
NU1702
NU3039
NU3041
NU5042
NU5045
NU5049
NU5050
NU5126
NU5132
NU5501
```

In the future we could make this tool create issues directly, but it'd be quite some work to avoid duplicates, so I decided to skip for now. 

The need for this tool was on the forefront to me because of https://github.com/nuget/client.engineering/issues/1028, so it's one thing at a time type of improvement :) 

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by zivkan** [comment]
What's the goal/design for how this will work?

It doesn't make sense to me to run as part of our regular build/CI, because we'd then be obligated to create and publicly publish docs before we can get a green build to merge the product change.

I feel like this utility is better off in Entropy. I get that it's much easier here, since you can easily have a project reference to NuGet.Common, whereas you'd need to find another solution if it's in a different repo. But automatically getting the latest version of NuGet.Common from our nuget-build feed will effectively do the same, and would be less effort than whatever I guess the automatic run for this tool will be.

**Comment by nkolev92** [comment]
> What's the goal/design for how this will work?

It's a tool that runs one off/as needed, not automatically.

> It doesn't make sense to me to run as part of our regular build/CI, because we'd then be obligated to create and publicly publish docs before we can get a green build to merge the product change.

It's not being run automatically.

> I feel like this utility is better off in Entropy. I get that it's much easier here, since you can easily have a project reference to NuGet.Common, whereas you'd need to find another solution if it's in a different repo. But automatically getting the latest version of NuGet.Common from our nuget-build feed will effectively do the same, and would be less effort than whatever I guess the automatic run for this tool will be.

It's not run automatically. 
I can move it there I guess, it'll largely be out of sight, out of mind to folks, as already apparent by the 27 undocumented codes.

**Comment by nkolev92** [comment]
Note that the biggest advantage of having in repo is that it would've been easy to validate the current build.

**Comment by zivkan** [comment]
> Note that the biggest advantage of having in repo is that it would've been easy to validate the current build.

If there's a way it can work well that I'm not thinking of, then that's a great reason to keep it in this repo.  I'm trying to figure out how it would work.

Say I create a PR to add a new code NU9876. The docs page doesn't yet exist. Should my PR be red, blocking me from merging the PR?  If not, what does it mean to "validate the current build"?

**Comment by nkolev92** [comment]
It was more about, go to the tip of the branch and run the tool. 

Now you'd have to specify the version, which is also ok. I created https://github.com/NuGet/Entropy/pull/57

The difference is marginal, leaving it Entropy until we come up with a better flow is probably best.

**Comment by nkolev92** [comment]
In an ideal world, here's what I'd have the tool do: 

* Run during build. 
And then one of the 2:
* If there are *any* undocumented log codes, don't fail, but warn instead and file an issue in the docs repo. 
* If there are *any* undocumented log codes, and you can't find an issue in the docs repo (rely on the title for example), fail the build. This would basically prompt an action for creating an issue. 

Finally, in another check, that's run at release time. 

A tool would find the undocumented codes/match the issues and help priortize them. 
We'd need a responsible person for that though (even if the work is running a few scripts).

**Comment by zivkan** [comment]
You know what, now I feel like this could work well here in this repo, running automatically as part of the build. Although only once the "check if issue already exists" is implemented. This PR https://github.com/NuGet/NuGet.Client/pull/4290 added a new stage for validations, which this tool would be perfect for. And it allows us to fail the build without preventing tests for running. Given how many warnings our build generates, and how big the logs are, I don't think a warning will be very effective.

**Pull request closed without merging**
