### PR TITLE
Generate the 2nd N.B.T.P package

### PR DESCRIPTION
**Pull request by heng-liu**
Generate the 2nd N.B.T.P package if we decide to insert into two versions of SDKs

### CODE REVIEW

**Comment by zivkan** [comment]
Pack doesn't do anything signing/crypto related, so there shouldn't be any need for a second package.

@heng-liu do you agree? If so, let's close this PR.

**Comment by heng-liu** [comment]
Hi @zivkan I'm afraid I can't agree.  As most of the signing/crypto changes are in NuGet.Packaging, which is used in PackTask.
@nkolev92 , what do you think?

**Comment by nkolev92** [comment]
What @zivkan is articulating is an outcome of a discussion me & him had a while back. 

The pack assembly is ilmerged. Specifically, it depends on NuGet.Packaging but it caries its own, and doesn't use the same as the one restore does. 

Now in /t:pack, there are no scenarios where signing is relevant. So I believe it might be safe for the pack sdk to only carry a netstandard version of it's assembly. 
At least until we know 100% the only place we are inserting into is 5.0 and we can stop building for 3 TFMs.

**Comment by heng-liu** [comment]
Thanks @nkolev92 !
FYI @zkat @kartheekp-ms

**Pull request closed without merging**
