### PR TITLE
Dev scoban updatebranch

### PR DESCRIPTION
**Pull request by sbanni**
## Fix

Details: Merging dev branch

### CODE REVIEW

**Comment by nkolev92** [comment]
We usually rebase our feature branches. 

We are using a trunk based model, so it might easier to do that instead. 

cc @zkat and @heng-liu who have been managing the signing feature

**Comment by zkat** [comment]
Yeah, we occasionally rebase the feature branch on top of dev. And obvs rebase our branches onto that feature branch. It's a bit of a pain sometimes, but it works.

**Review by rrelyea — APPROVED** [review]
ok. not sure how useful that was to review. but did a quick look. and it all makes sense.

**Comment by sbanni** [comment]
Following zkat's suggestion instead of this.

**Pull request closed without merging**
