### PR TITLE
Avoid conflicts with reference type dependencies

### PR DESCRIPTION
**Pull request by emgarten**
References types from the graph can cause collisions when creating a dictionary of libraries by id/version. 

This fix filters out reference type libraries for both the full library list, and for target graphs:

 `else if (library.Type == LibraryTypes.Package)`

This is a small change, github shows it as larger due to the spacing change.

https://github.com/NuGet/Home/issues/1959

//cc @joelverhagen @zhili1208 @yishaigalatzer @anurse

### CODE REVIEW

**Comment by joelverhagen** [comment]
Opened the diff offline which made it a lot clearer. Product code looks good, just concerned that we are only removing test cases. Are we potentially missing a regression here?

**Comment by analogrelay** [comment]
Looks like this is an added test case: https://github.com/NuGet/NuGet.Client/pull/241/files#diff-d07676aab31eda417a4b32f5935402c0R23

**Comment by joelverhagen** [comment]
> Looks like this is an added test case: https://github.com/NuGet/NuGet.Client/pull/241/files#diff-d07676aab31eda417a4b32f5935402c0R23

Yup, totally. I may or may not have had my local diff reversed on accident...

:shipit:

**Comment by analogrelay** [comment]
Heh, I wondered if that might be the case :). Git diffs be confusing.

:shipit:

**Pull request closed without merging**
