### PR TITLE
Revert "Removing RID infer"

### PR DESCRIPTION
**Pull request by analogrelay**
This reverts commit 3bb16d3467f5680eefa61365fa5acc401e70ab6c.

RID inference is bad! Buuuuuuut... turns out a lot of things in dotnet-cli and ASP.NET Core still depend on it right now (because we don't have the Portable App publishing model we're using instead).

This is a self-contained, easy to unrevert (vert? devert? divert?), change to restore RID inference and CompileOnly TFMs. After this is in, I'll re-open the bug that was originally closed and we'll update that when we're finally ready to remove RID inference.

Turns out RID inference was probably the last change we should make in this process, who knew? Oh well, live and learn :stuck_out_tongue_closed_eyes: 

/cc @yishaigalatzer @emgarten @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by emgarten** [comment]
We should not bring this back. It was very painful that VS and nuget.exe were strict on this while xplat did extra magic to infer RIDs. There have also been some changes in nuget also that make this more than just a revert at this point.

**Comment by analogrelay** [comment]
Ok, well we're going to need something to restore RID inference for non-netstandard TFMs in the short term. None of the other parts of the ecosystem have been updated to handle the change so we basically can't take any new NuGet builds until we either revert this temporarily or get the rest of the changes done.

Since we need to take the project.lock.json changes to add `runtimeTargets` this gets even more tricky...

**Comment by emgarten** [comment]
> or get the rest of the changes done.

What changes are left? I think it would better to focus on that, the longer the RID hack stays in the more likely is that it will get shipped and then we'll never be able to remove it.

**Comment by analogrelay** [comment]
Well, someone has to merge a hack :). Either we hack dotnet-cli and all the ASP.NET Core repos to add `runtimes` sections temporarily, or we restore RID inference while we finish the pre-requisite work. It's not that we don't want the change, it was just not staged properly (we didn't fully think through the dependent things that would break).

> the longer the RID hack stays in the more likely is that it will get shipped and then we'll never be able to remove it.

If that happens, it'll only be because we failed to ship portable apps, and I think we'll have bigger problems ;)

**Comment by analogrelay** [comment]
@emgarten and I chatted. We'll take this. Nobody is happy turning RID inference back on but it's the easiest way to smooth the transition :).

**Pull request closed without merging**
