### PR TITLE
Pin DartLab templates to previous commit

### PR DESCRIPTION
**Pull request by jeffkl**
## Bug

Fixes:

Regression? Last working version:

## Description

A change in dartlab templates broke our CI so I'm pinning temporarily to 96360c2392108b03deaed36e88c68319dfb45491 to workaround the issue.

```
/eng/pipelines/templates/End_To_End_Tests_On_Windows.yml (Line: 60, Col: 5): Unexpected parameter 'deployAndRunTestsStepList'
```

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]

**Review by dominoFire — APPROVED** [review]
Signing off. Should we merge this or should we apply commit below? Or should be apply both changes?

https://github.com/NuGet/NuGet.Client/commit/95ed0ed4c0dffc1e20d4dc890e047d1b3f907619

**Comment by jeffkl** [comment]
Pinning to an older version might be best at this point since we can't seem to get the new templates to work with our build.  Feel free to merge if the team agrees

**Comment by nkolev92** [comment]
Team review; ETA for the fixes by the infra folks is EOD. We'll hold off on merging this for now. We can merge it if the fix is not in by EOD.

**Comment by nkolev92** [comment]
Merged https://github.com/NuGet/NuGet.Client/pull/4614 instead.

**Pull request closed without merging**
