### PR TITLE
Latest version is selected after installing a package in Browse Tab

### LINKED ISSUE #11461: [Bug]: The “version” drop-down box shows the installed version instead of latest version in Browse tab before refreshing
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.1.0.83

### Worked before?

No

### Impact

It bothers me. A fix would be nice

#### Details about Problem
VS Version: Main\32016.83
NuGet Version: Dev\6.1.0.83
OS Version: Windows-11-Enterprise-21H2
#### Repro steps
1. Create a C# Console App (.NET 6.0) project.
2. Open the PM UI for the project and go to Browse tab.
3. Install a package – not the latest version (e.g. Newtonsoft.Json) from Browse tab.
4. Observe the “version” drop-down box on the right panel after installing.
#### Expected
The “version” drop-down box should show the latest version of this package in Browse tab.
#### Actual
The “version” drop-down box shows the installed version instead of latest version in Browse tab as below.
image
#### Notes
1. The “version” drop-down box will show the latest version of this package correctly after refreshing/reopening the PM UI/switching the tab back as below.
image
2. It is not a regression issue since it reproes on D16.10 31025.218.

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by martinrrm**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11461

Regression? Last working version:

## Description

When installing a package in the Browse the `SelectedVersion` will be updated to the installed version and will need a refresh to show the latest version, the behavior in this tab is that we always show the latest version available even if it is installed. 

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — CHANGES_REQUESTED** [review]
There's a comment in the code that explicitly says the currently installed version should be selected.

That suggests to me that this is not a bug.

**Comment by martinrrm** [comment]
@nkolev92 you're right, @donnie-msft you think this is not a bug?

**Comment by donnie-msft** [comment]
@martinrrm I think this behavior is acceptable:

1. Install a package on the Browse tab
2. Browse tab details shows the version just installed.
3. Move to any other tab
4. Return to Browse tab and you now see the Latest Version

Is that what you were seeing without your change?

**Comment by martinrrm** [comment]
@donnie-msft yes, that's the behavior without my change. So is better to close this pr right?

**Comment by donnie-msft** [comment]
Yes... I apologize for triaging that bug. I must have read it wrong the first time. 

Hopefully it wasn't too much to dig into it and maybe you learned something new about the code :)

**Comment by martinrrm** [comment]
Closing pr because it was not a bug, it is working as expected

**Pull request closed without merging**
