### PR TITLE
Disabled inconsistent test

### PR DESCRIPTION
**Pull request by jainaashish**

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
you should actually disable it instead of just writing a comment about it 😉

**Comment by jainaashish** [comment]
😄 pay attention and you'll see it's actually disabled along with comment.

**Comment by rohit21agrawal** [comment]
noo! don't do that..comment out the whole test.

**Comment by jainaashish** [comment]
how would that make a difference? keeping it around just in case we need to refer in future otherwise I would have deleted it altogether.

**Comment by emgarten** [comment]
Delete the entire thing, that's what source control is for. We have a bunch of test with the `Test-` removed and it is really confusing.

**Comment by rohit21agrawal** [comment]
@emgarten Thank You!

**Comment by jainaashish** [comment]
source control doesn't solve all the purpose. When you need to refer something and you aren't sure which release you removed it or changed it, it's really hard to find out through git. 

But if the consensus is to delete all such code, so be it...

**Review by emgarten — APPROVED** [review]
🔪 🚀 

I get your point on making it easier to find later. But I've found that is rarely needed, and the e2e tests especially are already littered with disabled tests that haven't been looked at again, and likely never will be.

**Comment by jainaashish** [comment]
Merged with https://github.com/NuGet/NuGet.Client/commit/317e230af46684fab91e4c8987a01399f537daf7

**Pull request closed without merging**
