### PR TITLE
Skip Apex test CreateNetCoreProject_AddProjectReference

### PR DESCRIPTION
**Pull request by zivkan**

### CODE REVIEW

**Review by dominoFire — APPROVED** [review]

**Comment by zivkan** [comment]
@dominoFire I've undone your edit to the PR comment. This PR does not fix the flaky test, so the issue should not be closed when this PR is merged.

**Comment by donnie-msft** [comment]
I'm still not convinced this is a flaky test, as I said offline. All the failures were on 002, and all the successes were on a different machine.

**Comment by zivkan** [comment]
even if it only fails on one machine, it's passing on other machines and hence it's not "deterministic" and therefore flaky. If the machine W002 had serious problems, we'd expect many tests to be failing, not just this one, and I've seen at least two builds where this was the only test that failed.

You're welcome to investigate and fix the root cause if you can find it, but I believe we have other tests that test the same scenario (project references), so I'd prefer to focus on other issues at this time.

**Comment by donnie-msft** [comment]
Be sure to run this build against 002 to prove it actually succeeds there before merging. Your current build is on 003, so not actually testing that it fixes the original problem.

**Review by donnie-msft — APPROVED** [review]
Please write an Issue to track this flaky test and to undo this PR. (edit: or is that what you intend https://github.com/NuGet/Home/issues/9410 which isn't linked to this PR?)

Approving since a build did pass on 002 with this change (although it's still possible that this test wasn't at fault)

**Comment by zivkan** [comment]
9410 isn't linked to this PR because GitHub closes linked issues when the PR is merged. This PR does not fix the flakiness, it only skips the test to reduce the number of times our builds fail for reasons unrelated to the PR, which prevent us from merging those PRs. And yes, 9410 is the issue to track fixing the flaky test, which is why the URL to that issue is provided as the reason (`Skip = "URL"`) to why the test is being skipped.

**Pull request merged**
