### PR TITLE
Updating NuGet logos in VS

### PR DESCRIPTION
**Pull request by mishra14**
Updating NuGet logo and default package icon in VS to reflect the new design.

Fixes: https://github.com/NuGet/Home/issues/5420

Blue Theme - 

blue

Dark Theme -

dark

Light Theme - 

light

### CODE REVIEW

**Comment by alpaix** [comment]
What are the contrast ratio for all themes?

**Comment by mishra14** [comment]
🔔  updated with screenshots

Issue for larger UI improvement: https://github.com/NuGet/Home/issues/5518

**Comment by mishra14** [comment]
Discussed with @anangaur  and @alpaix the icon may not meet the contrast requirements. This might get punted to 15.4.

**Comment by rohit21agrawal** [comment]
As per accessibility requirements, minimum contrast ratio should be 4.5 and can be verified with a tool like Colour Contrast Analyzer (download link : https://www.paciellogroup.com/resources/contrastanalyser/)

Under high contrast, the requirement is 14:1 AFAIK.

**Comment by anangaur** [comment]
Agree at this point we can punt it for 15.3 and take it up in 15.4

**Comment by mishra14** [comment]
Update: Me and Alex looked at MAS documents and found that there is no requirement for icons. But we can take this in the next wave of changes.

**Comment by anangaur** [comment]
Is there a blocker then to take the current icons in? Or have we missed the bus for 4.3?

**Comment by mishra14** [comment]
@anangaur will need to talk to @rrelyea on wednesday.

**Comment by mishra14** [comment]
@alpaix were you able to get any info from the accessibility folks to see if this is fine?

**Comment by nkolev92** [comment]
@mishra14 Can we merge this now/

**Comment by PatoBeltran** [comment]
@mishra14 by using the Image service added in https://github.com/NuGet/NuGet.Client/pull/1623 we could let VS invert the colors for the logo and have it meet the contrast requirements on each theme.

**Pull request closed without merging**
