### PR TITLE
Skip UninstallFromPMCForPC_SucceedAsync Apex test

### PR DESCRIPTION
**Pull request by zivkan**
issue to track flaky test: https://github.com/NuGet/Home/issues/9476

### CODE REVIEW

**Comment by zkat** [comment]
What's our usual strategy for re-enabling tests in the future? What would it be in this case?

**Review by heng-liu — APPROVED** [review]

**Comment by zivkan** [comment]
We need to make code changes, either to test code or product code, to prevent the flakiness. Maybe it's quality week tasks, maybe it's CI initiative tasks, maybe we need something new. However, in the time that I've been in the team, I've seen many tests skipped due to flakiness, but I don't remember any PRs re-enabling tests :(

**Comment by zkat** [comment]
my hunch here is that we should unlink this PR from https://github.com/NuGet/Home/issues/9476, and leave that other issue open until we actually fix the issue. I'm fine with temporarily disabling the test, but I'm uncomfortable doing so into a void :\

**Review by donnie-msft — APPROVED** [review]
We should remove the link to your tracking issue so that the Issue documenting this Flaky behavior remains open.

This follows the pattern used by dtivel: https://github.com/NuGet/Home/issues/8486 which was not resolved by his PR to Skip the test https://github.com/NuGet/NuGet.Client/pull/3021

Edit: I edited your description to remove the GH link.

**Comment by zivkan** [comment]
lol, I wanted to avoid using "Fixes: issue", but I accidentally did it anyway :(

**Pull request merged**
