### PR TITLE
Installing custom versions in PMUI

### LINKED ISSUE #9829: Allow to user to input custom (floating) versions through the PM UI
Change version input to a Combo Box displaying available version depending on the user input. This will allow users to select a floating version to install.

### PR DESCRIPTION
**Pull request by martinrrm**
## Bug

Fixes: [Allow to user to input custom (floating) versions through the PM UI](https://github.com/NuGet/Home/issues/9829)
Regression: Yes/No  
* Last working version:   
* How are we preventing it in future:   

## Testing/Validation

Tests Added: No  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Comment by kartheekp-ms** [comment]
@donnie-msft - Can we close this draft PR?

**Comment by nkolev92** [comment]
The overall issue is assigned to me. 

Closing this now, we'll reopen later.

**Comment by donnie-msft** [comment]
@kartheekp-ms it needs to be shepherded. @nkolev92 the issue is assigned to Martin, not you. Let me know if you need me. I haven't taken a look, yet.

**Comment by nkolev92** [comment]
@donnie-msft The overall work needs finished here. 

The epic that the issue linked is part of is assigned to me.

It's not on my immediate TODO list, so if you'd like to take it over the finish line let me know.

**Pull request closed without merging**
