### PR TITLE
Update public API docs for 5.11.x

### PR DESCRIPTION
**Pull request by erdembayar**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/1097

Regression? Last working version:
Fix 5.11 api changes. I  already pushed to 5.11 release branch: https://github.com/NuGet/NuGet.Client/commit/b6e69c6f4b44b58b88adfe639bf52a26c3e58a82
## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
How did you arrive to the delta that's here? 

If you follow: https://github.com/NuGet/NuGet.Client/blob/dev/docs/nuget-sdk.md#shipping-nuget, it suggests that the commit should first happen on the release branch.

**Comment by nkolev92** [comment]
Note that I think your delta is correct, I just think we need 2 PRs!

**Comment by erdembayar** [comment]
> Note that I think your delta is correct, I just think we need 2 PRs!

~~Could you please give me example? For 5.10 I only see 1 [PR](https://github.com/NuGet/NuGet.Client/pull/4114).~~
For 5.11 branch can I just push this commit directly? Because I don't see actual PR for https://github.com/NuGet/NuGet.Client/commit/8b3be1734d595aa591557ab710cad5c4ce661810 with 5.10

**Comment by nkolev92** [comment]
Please refer to the description in https://github.com/NuGet/NuGet.Client/blob/dev/docs/nuget-sdk.md#shipping-nuget. 

It was changed. It used to be, commit in dev port to release, but in reality it should be make the change in release and port to dev. 

The 5.10 had no PR, because you could just cherry-pick, but you can't cherry pick to dev.

**Comment by erdembayar** [comment]
> Please refer to the description in https://github.com/NuGet/NuGet.Client/blob/dev/docs/nuget-sdk.md#shipping-nuget.
> 
> It was changed. It used to be, commit in dev port to release, but in reality it should be make the change in release and port to dev.
> 
> The 5.10 had no PR, because you could just cherry-pick, but you can't cherry pick to dev.

Directly pushed to 5.11 https://github.com/NuGet/NuGet.Client/commit/b6e69c6f4b44b58b88adfe639bf52a26c3e58a82

**Comment by nkolev92** [comment]
> > Please refer to the description in https://github.com/NuGet/NuGet.Client/blob/dev/docs/nuget-sdk.md#shipping-nuget.
> > It was changed. It used to be, commit in dev port to release, but in reality it should be make the change in release and port to dev.
> > The 5.10 had no PR, because you could just cherry-pick, but you can't cherry pick to dev.
> 
> Directly pushed to 5.11 [b6e69c6](https://github.com/NuGet/NuGet.Client/commit/b6e69c6f4b44b58b88adfe639bf52a26c3e58a82)

No, that's not the process.

As I said, the process is PR to release first, then port to dev.

**Comment by nkolev92** [comment]
You shouldn't really commit code without a code review in at least one branch.

**Comment by nkolev92** [comment]
I understand that this PR is good as is, but please follow the instructions next time.

**Review by nkolev92 — APPROVED** [review]

**Comment by erdembayar** [comment]
@NuGet/nuget-client 
Please review. I'll merge today evening or tomorrow morning.

**Review by zivkan — APPROVED** [review]

**Pull request merged**
