### PR TITLE
Rename netcoreapp1.2 to netcoreapp2.0

### PR DESCRIPTION
**Pull request by ericstj**
/cc @joelverhagen @zhili1208 @weshaggard @alexperovich

### CODE REVIEW

**Comment by davidfowl** [comment]
👏

**Review by joelverhagen — APPROVED** [review]
:shipit:

**Comment by joelverhagen** [comment]
I'll run this through the CI.

**Comment by ericstj** [comment]
Thanks Joel.

**Review by weshaggard — APPROVED** [review]

**Comment by joelverhagen** [comment]
CI Passed. :shipit:

**Pull request merged**
