### PR TITLE
Merge NuGet.SolutionRestoreManager.Introp into NuGet.VisualStudio

### LINKED ISSUE #10957: Merge NuGet.SolutionRestoreManager.Interop into NuGet.VisualStudio
Visual Studio 2022 (dev17)'s SDK has stopped using `EmbedInteropTypes`. [NuGet also made the same change](https://github.com/NuGet/NuGet.Client/pull/4072) in NuGet 6.0 (which targets dev17).

All the APIs in NuGet.SolutionRestoreManager.Interop will also be moved into the NuGet.VisualStudio package, and the namespace for all the APIs will be moved from `NuGet.SolutionRestoreManager` to `NuGet.VisualStudio`.

This avoids a new assembly (NuGet.SolutionRestoreManager.Interop.dll) being loaded by Visual Studio, which has a very minor performance benefit (memory reduction).

### PR DESCRIPTION
**Pull request by zivkan**
## Bug

Fixes: https://github.com/NuGet/Home/issues/10957

Regression? No

## Description

* Move all interfaces from `NuGet.SolutionRestoreManager.Interop` to `NuGet.VisualStudio`.
* Change affected interfaces namespaces from `NuGet.SolutionRestoreManager` to `NuGet.VisualStudio`.

## PR Checklist

- [X] PR has a meaningful title
- [X] PR has a linked issue.
- [X] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [X] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [X] N/A

### CODE REVIEW

**Review by nkolev92 — COMMENTED** [review]
Wouldn't the namespace changes break the component using NSRM, given that the interfaces are resolved through MEF.

**Comment by zivkan** [comment]
According to [this document](https://docs.microsoft.com/en-us/dotnet/framework/interop/type-equivalence-and-embedded-interop-types?redirectedfrom=MSDN#type-identity), the GUID is used instead of the namespace. We'll see with the CI tests if the VS tests pass or not.

**Comment by zivkan** [comment]
Changing the namespace didn't work, but changing the namespace back, while keeping the code in the new assembly does appear to work. Just a flaky apex test, and the build should be green.

**Comment by nkolev92** [comment]
@zivkan 

It might be a good idea to do a manual test where you create a VSIX project with this build on top of latest dev17, since I don't think we have any VSIX projec tests.

**Comment by zivkan** [comment]
"works on my machine" 😄 

image

**Review by nkolev92 — APPROVED** [review]
Can you run the RPS test prior to merging?

**Comment by zivkan** [comment]
RPS passed: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/332956

**Pull request merged**
