### PR TITLE
Merge dotnet search command into 17.9

### PR DESCRIPTION
**Pull request by martinrrm**
## Bug

Fixes:

Regression? Last working version:

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by donnie-msft** [comment]
Should this be for dev or `release-6.9.x`?

**Comment by martinrrm** [comment]
@donnie-msft Good question, we are not sure how the process for merging for two versions is, but this feature is needed in 17.9 that's why we decided to merge it here first and have a testable build for vendors.

**Comment by donnie-msft** [comment]
> ded in 17.9 that's why we decided to merge it here first and have a testable build for vendors.

Ok, this PR is not merging to dev, it is merging to 17.9, but it is titled "into dev".

**Comment by nkolev92** [comment]
We usually merge to dev first, then cherry pick to release.

**Review by Nigusu-Allehu — APPROVED** [review]

**Comment by martinrrm** [comment]
Closing in favor of https://github.com/NuGet/NuGet.Client/pull/5580

**Pull request closed without merging**
