### PR TITLE
take options from packOptions instead of root of project.json

### PR DESCRIPTION
**Pull request by rohit21agrawal**
fixes issue : https://github.com/NuGet/Home/issues/3161

take options like :
summary
tags
owners
releaseNotes
iconUrl
projectUrl
licenseUrl
requireLicenseAcceptance

from packOptions instead of the root of the project.json file.

//CC : @emgarten @joelverhagen @alpaix @drewgil @jainaashish @rrelyea

### CODE REVIEW

**Comment by jainaashish** [comment]
LGTM :shipit:

**Comment by alpaix** [comment]
:shipit:

**Comment by patricknolan** [comment]
Hi, has this issue been resolved?

When it is resolved what will I need to update so that these packOptions are picked up from my project.json file when I build my project?

**Comment by rohit21agrawal** [comment]
@patricknolan you can download nuget.exe version 3.5.0-rc from here to try this out  : https://dist.nuget.org/win-x86-commandline/v3.5.0-rc1/NuGet.exe

**Pull request merged**
