### PR TITLE
Disable Install/Update button in Project level when using VersionOverride

### LINKED ISSUE #12230: [Bug]: Disable the option to update version when using VersionOverride in CPM
If you use the PM UI to update a version of a package that is using VersionOverride it will succeed. VersionOverride wont change, only the version in Directory.Packages.props

### PR DESCRIPTION
**Pull request by martinrrm**
## Bug 

Fixes: https://github.com/NuGet/Home/issues/12230

Regression? Last working version:

## Description

Disable the Install/Update button in Project level PM UI when the Package Version is set by a VersionOverride.
image

image

image

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [x] Test exception - Tested manually in PM UI
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by jeffkl — DISMISSED** [review]
Is there anyway to give the user a tooltip so they know why the button is disabled?

**Comment by martinrrm** [comment]
@jeffkl I think we can add a tooltip in the button when they hover over, I'll try that, do you have another idea?

**Comment by jeffkl** [comment]
> @jeffkl I think we can add a tooltip in the button when they hover over, I'll try that, do you have another idea?

That would be fine, I just hate it when something is disabled and I have no idea why, any tooltip we can provide would be great!

**Comment by martinrrm** [comment]
@jeffkl I added a tooltip when hovering the button, you think the wording is good?

**Review by jeffkl — APPROVED** [review]

**Pull request merged**
