### PR TITLE
Added AppVeyor configuration file

### PR DESCRIPTION
**Pull request by alpaix**
Enabling AppVeyor CI

### CODE REVIEW

**Comment by drewgillies** [comment]
Great! :shipit:

**Comment by joelverhagen** [comment]
It seems like there's more to this than adding an appveyor config file. Can you provide details and motivation about the other changes (e.g. looks like `dotnet-test-xunit` is getting a version bump)?

**Comment by alpaix** [comment]
@joelverhagen This is an experimental PR for tweaking project settings to make decent AppVeyor builds with tests. It's not to be merged. For the final changes I'm going to submit another one.

**Comment by alpaix** [comment]
Closing this PR in favor of upcoming polished one...

**Pull request closed without merging**
