### PR TITLE
fix xplat verification branch after rebase

### PR DESCRIPTION
**Pull request by zkat**
## Bug

Fixes: https://github.com/NuGet/Home/issues/9012
Regression: Yes 
* Last working version:   just a mess-up in the feature branch

## Fix

Details: I made a mistake while rebasing the xplat branch onto dev. This takes care of the issues that caused.

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
When you merge back to the dev branch, is the plan to rebase and merge? Or you plan on squashing some commits?

**Comment by zkat** [comment]
@nkolev92 I don't really know, tbh. I think it makes sense to squash at least some of them, but I also don't necessarily see much value in the commits that are already there, as discrete commits, you know? @heng-liu how do you feel about it?

**Comment by heng-liu** [comment]
@zkat Yes, I agree with squashing some of them. It would make the rebase easier. Especially for the first three commits :
Signing:  add net standard2.1 for packaging (#2835)
Remove 2nd N.B.T.P package (#2984)
remove WorkaroundNetStandard target, change SDK for build from 3.0 preview to 3.1 stable (#3161)
Those three commits together will make targeting to netcore3.0 work.

**Comment by heng-liu** [comment]
Looks like there're extra broken the tests in Dotnet.Integration.Test.

**Review by heng-liu — APPROVED** [review]

**Pull request merged**
