### PR TITLE
Unwrapped LINQ Where to be a conditional check inside for each loop

### LINKED ISSUE #10920: Overallocations of WhereListIterator in DependencyWalker.CreateGraphNode
The DependencyWalker uses a LINQ Where in the CreateGraphNode method on a hot code path and the result is a large amount of WhereListIterators being allocated.

```
 Name                                                                                                                                 	Inc %	          Inc
 Type WhereListIterator`1[NuGet.LibraryModel.LibraryDependency]                                                                      	  0.6	   58,290,408
+ clr!?                                                                                                                              	  0.6	   58,290,408
 + system.core.ni!?                                                                                                                  	  0.6	   58,290,408
  + nuget.dependencyresolver.core!NuGet.DependencyResolver.RemoteDependencyWalker+<CreateGraphNode>d__3.MoveNext()                   	  0.6	   52,176,240
  |+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start[System.__Canon](System.__Canon ByRef)	  0.6	   52,176,240
  | + nuget.dependencyresolver.core!RemoteDependencyWalker.CreateGraphNode                                                           	  0.6	   52,176,240
```

### PR DESCRIPTION
**Pull request by jebriede**
## Bug

Fixes: https://github.com/NuGet/Home/issues/10920

Regression? Last working version: N/A

## Description
Unwrapped the LINQ where to be a conditional check inside the for each loop so it does not allocate extra objects on a hot code path in the DependencyWalker.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  Existing tests already cover the functionality
  - [x] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by jebriede** [comment]
Using OrchardCore as the solution, this fix eliminates the following allocations:

```
 Name                                                                                                                                 	Inc %	          Inc
 Type WhereListIterator`1[NuGet.LibraryModel.LibraryDependency]                                                                      	  0.6	   58,290,408
+ clr!?                                                                                                                              	  0.6	   58,290,408
 + system.core.ni!?                                                                                                                  	  0.6	   58,290,408
  + nuget.dependencyresolver.core!NuGet.DependencyResolver.RemoteDependencyWalker+<CreateGraphNode>d__3.MoveNext()                   	  0.6	   52,176,240
  |+ mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start[System.__Canon](System.__Canon ByRef)	  0.6	   52,176,240
  | + nuget.dependencyresolver.core!RemoteDependencyWalker.CreateGraphNode                                                           	  0.6	   52,176,240
```

**Review by nkolev92 — APPROVED** [review]

**Review by erdembayar — APPROVED** [review]
🚀

**Review by aortiz-msft — APPROVED** [review]
:shipit:

**Comment by aortiz-msft** [comment]
Could you please summarize the allocation impact of this fix for Solution Load in OrchardCore?

**Pull request merged**
