### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by urbas**
Adds instructions on how to clone, build, and submit pull requests to this repository.

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
@csharpfritz can you review and add your portion before we merge

**Comment by csharpfritz** [comment]
We need to add some information to this doc about three requirements that we have in order to accept pull-requests:
1. An issue must be opened first and feedback from the NuGet team must be received
2. Unit tests are highly recommended and none should be broken for any code change that introduces new features or modifies business logic
3. A contributor license agreement may be required by the .NET Foundation prior to a successful merge.  This can be completed online and will be requested by the [.NET Foundation Bot](https://github.com/dnfclas) if needed.

**Comment by urbas** [comment]
@csharpfritz Where should the issue be opened? It looks like the `NuGet.Client` repo doesn't have issues enabled.

**Comment by yishaigalatzer** [comment]
Home repo

**Comment by urbas** [comment]
@csharpfritz @yishaigalatzer Updated with your feedback. Please take another look.

**Comment by csharpfritz** [comment]
Looks good to me...  Thank you for your contribution!

**Pull request merged**
