### PR TITLE
Add binlogs to all build phases and upload them on failure

### PR DESCRIPTION
**Pull request by jeffkl**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/849

Regression? Last working version:

## Description

Add `/bl` argument to invocations of MSBuild in our pipelines and upload them if the job fails.

I also added a bunch of our files to the solution so we can search for stuff in Visual Studio.

## Checklist
- [x] Has a meaningful title
- [x] Has a linked issue
- [x] Described changes

## Tests
- [ ] Automated tests added
- **OR**
  
- [ ] Test exception
- **OR**
- [x] N/A 

## Documentation
  
- [ ] Documentation PR or issue filled
- **OR**
- [x] N/A

### CODE REVIEW

**Comment by jeffkl** [comment]
Once CI passes, I'll push another commit that fails each phase so I can see how the logs look

**Comment by jeffkl** [comment]
Actually, I decided to push to a different branch and started a build with all of the publish binlogs set to `always()`:

https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=6059058&view=results

Commit with `always()` set: https://github.com/NuGet/NuGet.Client/commit/0cfccdefb0bc78f7f6665aacf80042991d8d3399

**Comment by jeffkl** [comment]
🎉 
image

**Comment by nkolev92** [comment]
> 🎉 image

You can't put party on your own PR @jeffkl :P 
What are we here for? :D

**Review by nkolev92 — APPROVED** [review]

**Review by dominoFire — APPROVED** [review]

**Comment by jeffkl** [comment]
> You can't put party on your own PR @jeffkl :P

Its my party and I'll party if I want to! 😀 

... Aaaaaaaand CI is broken, my party is over

**Pull request merged**
