### PR TITLE
Refactored package metadata resources.

### PR DESCRIPTION
**Pull request by alpaix**
Preliminary refactoring toward all-sources feature.
Various metadata classes eliminated in favor of the only IPackageSearchMetadata.
Renames and moves for clearer source code organization.

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by yugangw-msft** [comment]
@yishaigalatzer, @alpaix, this change will cause conflict with #267 as it is moving away the file which my PR will update.
Please coordinate with me.

**Comment by emgarten** [comment]
These changes conflict with everyone's work, which is why this was done as a subset of the original PR. I'm blocked until this goes in.

**Comment by alpaix** [comment]
@yugangw-msft I'm not seeing what particular file causing conflict. Could you please specify its path?

**Comment by yugangw-msft** [comment]
@alpaix  one of the files are PushCommandResourceV3Provider.cs, which my PR renamed and your PR  is moving the location. That will cause conflicts, right?

**Comment by alpaix** [comment]
`git rebase` should handle this just right. I don't think it's blocking.

**Comment by yugangw-msft** [comment]
Sure. If it blocks other people, go ahead and merge regardless then.

**Pull request merged**
