### PR TITLE
Clarifies nuspec parsing exceptions

### PR DESCRIPTION
**Pull request by TechnikEmpire**
## Bug
Fixes: https://github.com/NuGet/Home/issues/2714
Regression: No
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details:
Adds a new exception string.
Wraps exceptions thrown while parsing nuspec properties and then throws parent exceptions that specify exactly what property caused the fatal issue.
The exception strings offers a helpful hint to the number one reason why this problem occurs, by reminding users to target the project file when using replacement tokens.

## Testing/Validation
Tests Added: No  
Reason for not adding tests:  Not needed.
Validation done:  Manually tested against https://github.com/NuGet/Home/files/249649/repro2714-badErrorInPackWhenVersionIsParameterized.zip

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@TechnikEmpire do you mind if i take this PR, fix the test cases and merge it?

**Comment by TechnikEmpire** [comment]
@rohit21agrawal I'm not sure what all you're referring to. Does my name come off it or something? Did I break tests?

**Comment by rohit21agrawal** [comment]
image

**Comment by rohit21agrawal** [comment]
the apex tests are not your fault, but can yo try running unit tests locally ?

**Comment by TechnikEmpire** [comment]
Oh, yeah that's a problem lol. Whatever it takes to fix the bug. I don't have the resources to commit to resolving those so I appreciate you doing it. Thanks.

**Comment by TechnikEmpire** [comment]
@rohit21agrawal I didn't run any tests because the change is so insignificant that if it causes a test to fail, then the test is simply invalid.

Sorry but I've destroyed my local copy of this and moved on. I've got a million other things to do. If that's going to block merging though let me know.

**Comment by rohit21agrawal** [comment]
closing in favor of : https://github.com/NuGet/NuGet.Client/pull/2386

**Pull request closed without merging**
