### PR TITLE
make the compat check a warning on xplat cli

### PR DESCRIPTION
**Pull request by analogrelay**
It's just causing too many restores to fail despite the app still running fine.

/cc @emgarten @yishaigalatzer @ericstj @davidfowl

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
Lets vet with Eric and co

@ericstj

Sent from my Windows Phone

**Comment by davidfowl** [comment]
We shouldn't make this change.

**Comment by analogrelay** [comment]
Alright, we'll soldier on with fixing the runtime.json files :). But I'm keeping this branch :P

**Comment by ericstj** [comment]
FWIW we do know that we need a replacement for gaurdrails.  It's just that we probably need to get that replacement ready before we turn it off in NuGet.  This is catching real runtime issues.

**Pull request closed without merging**
