### PR TITLE
2018-06-19: GS - Update localized string for 'Package Source' for add…

### PR DESCRIPTION
**Pull request by PNI-GS**
…ing packages to 'Package source' to reflect the same other 3 actions.

## Bug
Fixes: No Bug created
Regression: No  
If Regression then when did it last work:   N/A
If Regression then how are we preventing it in future:   N/A

## Fix
Details: Update localized string for 'Package Source' for adding packages to 'Package source' to reflect the same other 3 actions.

## Testing/Validation
Tests Added: No  
Reason for not adding tests:  String display update.
Validation done:  N/A

### CODE REVIEW

**Review by mishra14 — APPROVED** [review]

**Comment by mishra14** [comment]
@PNI-GS Thanks for the contribution. I have marked the PR approved for CI and once it is clean on our CI, we can merge it.

**Comment by nkolev92** [comment]
@PNI-GS can you  rebase so we can rerun the tests?

**Comment by PNI-GS** [comment]
@nkolev92 Yes, I can do that.. but I have not done a successful rebase before.  What procedure do you recommend?

**Comment by nkolev92** [comment]
@PNI-GS 

I think the following should work (Note I haven't test, it's merely a guidance)
```
# Go to your copy of dev
git checkout dev
# Add NuGet's remote
git remote add NuGet https://github.com/NuGet/NuGet.Client.git
# Update NuGet's remote
git fetch NuGet
# Rewrite your dev with NuGet's dev
git rebase NuGet/dev
# Force push to rewrite the history of your dev
git push -f
# Change to the target branch
git checkout dev-gsch-stringupdate
# rebase from dev
git rebase dev
# push to rewrite history with your changes on top.
git push -f
```

**Comment by PNI-GS** [comment]
@nkolev92 

Thank you very much.

Done

**Comment by nkolev92** [comment]
Sweet, I've kicked off the build, will merge once the tests pass (there's the occasional test asserting an error message, though I doubt this one is that).

**Pull request merged**
