### PR TITLE
Install tab hang

### PR DESCRIPTION
**Pull request by johnataylor**
Can you take a quick look. (This also includes some simple cosmetics - like some missing copyrights) 

@emgarten @yishaigalatzer @deepakaravindr @alpaix 

Note this code still goes to the network for old style asp 5 projects.

### CODE REVIEW

**Comment by deepakaravindr** [comment]
Looks good to me!

**Comment by alpaix** [comment]
:shipit:

**Comment by emgarten** [comment]
The global folder can be null in a scenario where the solution hasn't been saved, and the machine wide nuget.config contains a relative path? Are there any others? It really seems like should never be null.

**Comment by yishaigalatzer** [comment]
That's the only scenario in aware of. It can also be missing or innaccessible

**Pull request closed without merging**
