### PR TITLE
Fix original target framework inference in Visual Studio restore when only the TargetFramework is not set

### LINKED ISSUE #11795: [Bug]: Visual Studio restore sometimes sets originalTargetFrameworks incorrectly in project.assets.json
### NuGet Product Used

Other/NA

### Product Version

VS 2019 16.11.7, VS 2022 17.1.6

### Worked before?

_No response_

### Impact

It's more difficult to complete my work

### Repro Steps & Context

The issue is seen in `project.assets.json` at `project/restore/originalTargetFrameworks`. The issue is present only for some values of `$(TargetFramework)`. I see the issue when `$(TargetFramework)` is `net6.0-windows`, but not when using, for example, `net6.0`. Examples below are when `$(TargetFramework)` is `net6.0-windows`:

Relevant portion of `project.assets.json` after MSBuild command line restore:
```json
      "originalTargetFrameworks": [
        "net6.0-windows"
      ],
      "frameworks": {
        "net6.0-windows7.0": {
          "targetAlias": "net6.0-windows",
          "projectReferences": {}
        }
      },
```

Relevant portion of `project.assets.json` after Visual Studio restore:
```json
      "originalTargetFrameworks": [
        "net6.0-windows7.0"
      ],
      "frameworks": {
        "net6.0-windows7.0": {
          "targetAlias": "net6.0-windows",
          "projectReferences": {}
        }
      },
```

The documentation for `NuGet.ProjectModel.ProjectRestoreMetadata.OriginalTargetFrameworks` states:
```
Original target frameworks strings. These are used to match msbuild conditionals to $(TargetFramework)
```
Therefore I would suggest that MSBuild command line is behaving correctly, and Visual Studio is behaving incorrectly. This difference in behaviour has broken one of our build customizations. It will also create churn when mixing VS and command line builds, causing unnecessary rebuilds.

Repro project/solution: [ClassLibrary1.zip](https://github.com/NuGet/Home/files/8639413/ClassLibrary1.zip)

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11795

Regression? Last working version:

## Description

Here's the commandline equivalent: https://github.com/NuGet/NuGet.Client/blob/b77d76415ce0a716398fc6d6cf62313e5d2c34b5/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs#L232-L236

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by zivkan** [comment]
Probably out of scope (too much effort required) for this PR, but is there some way we can de-duplicate the business logic, so these types of inconsistencies are less likely to happen?  For example, some kind of interface that has methods "GetProperty", "GetPackageReference", etc, and the VS implementation of this interface knows how to read values from a nomination, whereas the CLI implementation gets the data from MSBuild, but the business logic of creating a PackageSpec is no longer duplicated?

Do you think this idea might be small enough to fit into this PR, or should we consider it for future improvements?

**Comment by nkolev92** [comment]
Let me take a look. 
The trick is that it'd require shared public APIs, which I imagine you're ok with. 

I need to check how much similarity there is between the implementations and try to gauge how much work the refactoring would be.

**Comment by nkolev92** [comment]
Actually this is different PR :D I thought you were commenting on the package download one. 

There's probably some shared code here, but probably minimal. 

Either way. I'll try to take a stab at refactoring the VS vs commandline paths. 
Right now we have 3-ish implementations. 
Last time, Jeff attempted some refactoring but it was going to be a lot of work. Maybe a fresh look gives us some new ideas.

**Review by zivkan — APPROVED** [review]

**Comment by nkolev92** [comment]
So looking at this, as you mentioned, the changes would be out of scope for this PR, but even overall the changes seem challenging. 

It's gonna require some creative coding. The biggest different between the 2 is that for commandline, we're processing information by type...example, dependency, frameworkinfo etc and then decide on the framework, but in VS it's based on a framework pivot.

Both of those already have some shared code though. Maybe we can expand on that. 
It'd be a big win if we could align things, but it's probably takes longer than a day :)

**Pull request merged**
