### PR TITLE
fix nuget quick search in Visual Studio

### LINKED ISSUE #2719: Typing "nuget <packagename>" in vs quicklaunch search box keeps "nuget " prefix
1. type in nuget somepackageName in VS quicksearch box (I was using VS 2015 update 2)
2. press enter
3. nuget package manager launches to browse tab and puts "nuget somepackageName" in the search box.

Expected: "somepackageName" is put into the search box.

Note: I had 3.4.0 of the vsix installed when testing.

### PR DESCRIPTION
**Pull request by rohit21agrawal**
fixes : https://github.com/NuGet/Home/issues/2719

@joelverhagen @emgarten @alpaix

### CODE REVIEW

**Comment by emgarten** [comment]
LGTM, is any additional whitespace trimming needed on the search query?

:shipit:

**Comment by joelverhagen** [comment]
:shipit:

**Comment by rohit21agrawal** [comment]
search query is being trimmed of whitespaces. If i type : "nuget      newtonsoft" , Package Manager will get the query "newtonsoft" .

---

In reply to: [226000468](https://github.com/NuGet/NuGet.Client/pull/679#issuecomment-226000468) [](ancestors = 226000468)

**Comment by rohit21agrawal** [comment]
Merged : https://github.com/NuGet/NuGet.Client/commit/ceca2044585829b1bc1ece43f72065c4d0a6978f

**Pull request closed without merging**
