### PR TITLE
Remove build warning (and dev1x filenames)

### PR DESCRIPTION
**Pull request by drewgillies**
5 files weren't being found by the vsix ignore file in the VS15 build. Also took the opportunity to remove Dev14 and Dev15 from filenames.
@alpaix @emgarten @joelverhagen

### CODE REVIEW

**Comment by joelverhagen** [comment]
Why did these disappear?

**Comment by drewgillies** [comment]
No idea. Not as a result of changes I made. @alpaix?

**Comment by alpaix** [comment]
Looks good :shipit:

**Comment by drewgillies** [comment]
@alpaix  - do you know why the files disappeared? Did it relate to this work at all? https://github.com/NuGet/NuGet.Client/commit/204d7fafd10025216c558f96ff83a1ea95172d33

**Comment by alpaix** [comment]
@drewgil I don't have an answer to your question. I can't see how https://github.com/NuGet/NuGet.Client/commit/204d7fafd10025216c558f96ff83a1ea95172d33 is related to this issue.

**Comment by drewgillies** [comment]
@joelverhagen I'd like your thoughts before pushing this.

**Comment by joelverhagen** [comment]
:shipit:

**Pull request merged**
