### PR TITLE
Extended the checkbox in the Options page to two lines so it has room to wrap text

### LINKED ISSUE #10779: Tools -> Options -> NuGet Package Manager string is truncated
Related to: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1151266

Affected Branch:
Affected Build: Version 16.7.0 Preview 4.0 [30301.268.master]
Affected Product Language:

Steps to reproduce:

1. open tools->options->NuGet Package Manager
2. observe the string in the label for "Automatically check for missing packages during build in Visual

**Expected**
the string should either end with "in Visual Basic" or with "during build."

**Observed**
the string appears trunctated, and has extraneous information ("in Visual"). I also question how this string will appear after localization.

### PR DESCRIPTION
**Pull request by jebriede**
## Bug

Fixes: https://github.com/NuGet/Home/issues/10779

Regression? Last working version: N/A

## Description
Extended the checkbox titled "Automatically check for missing packages during build in Visual" in the Options page to two lines so it has room to wrap text

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
Change is visual. Tested manually.
  - [x] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A
  
  Screenshots of change in 200% scaling with 3240 x 2160 resolution and 100% scaling with 2560 x 1440, respectively:
  
image

image

### CODE REVIEW

**Review by dominoFire — APPROVED** [review]

**Comment by dominoFire** [comment]
Can you test it on Russian language? The overflow appears in that language.

image

**Review by zivkan — APPROVED** [review]

**Review by donnie-msft — CHANGES_REQUESTED** [review]
Would like to have a clear repro so I can understand this scenario and solution. (https://github.com/NuGet/Home/issues/10779#issuecomment-822864368)

**Comment by jebriede** [comment]
@donnie-msft I added a comment to the GitHub issue with the specs on where this repros and where it does not and updated the bug description to be specific about the scaling and resolution combo for each screenshot. I think that was the only question you had. Please let me know if you have any other questions and unblock the PR when ready. Thanks!

**Review by donnie-msft — APPROVED** [review]
Talked offline. The repro is finicky, but the PR seems to address it. I don't like that the PR causes "Studio" to be on a new line when it wasn't before, but it does fix this one scenario. 

WinForms is a bit dramatic with this refactoring, but what can ya do?!
Hopefully we can rewrite this dialog soon.

**Pull request merged**
