### PR TITLE
change dev branding to 6.3 preview.1

### PR DESCRIPTION
**Pull request by heng-liu**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/1529

Regression? Last working version:

## Description

Change the branding of dev branch to 6.3 preview.1

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
@heng-liu There's a branching and versioning template that should be followed for this work, not the insertion one: 

https://github.com/NuGet/Client.Engineering/issues/new?assignees=&labels=&template=branch_template.md

**Review by nkolev92 — APPROVED** [review]
Change here looks good. 

There's some other stuff that needs done when we shift the branch.

**Comment by heng-liu** [comment]
Thanks @nkolev92 ! LOL, I didn't noticed that has been changed. Will change to use the other template.

**Comment by nkolev92** [comment]
@heng-liu 
I see a test that I have a PR to disable, NuGet.CommandLine.Test.NuGetPushCommandTest.PushCommand_PushToServer_WhenPluginReturnsNoCredentials_FallBackToConsoleProvider is failign. 

I'd be happy to override the merge for this PR if you'd want me to.

**Review by erdembayar — APPROVED** [review]

**Pull request merged**
