### PR TITLE
Instead of hardcode mac paths, relative mono paths

### PR DESCRIPTION
**Pull request by jbtule**

### CODE REVIEW

**Comment by emgarten** [comment]
Thanks for the PR @jbtule!

What scenario does this fix? When is the hardcoded path incorrect?

//cc @zhili1208

**Comment by jbtule** [comment]
@emgarten The hardcoded path is incorrect on linux (always) or anytime mono is built from source (Mac included).

**Comment by zhili1208** [comment]
@jbtule thanks, that's a great fix, the hardcode path is not used on Linux since there was no msbuild on Linux when I added the hardcode path. And it won't work if you build from source.

I think this is a good fix, added mono guys here @mrward

**Comment by mrward** [comment]
Looks good to me.

MonoDevelop does something very similar to find the [Mono path](https://github.com/mono/monodevelop/blob/c8b2dec50cf63fa292e7ecbbdc57ed44b5fa97e4/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoRuntimeInfo.cs#L210). This path is then used to find [MSBuild when using Mono](https://github.com/mono/monodevelop/blob/c8b2dec50cf63fa292e7ecbbdc57ed44b5fa97e4/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs#L182).

**Comment by rohit21agrawal** [comment]
@zhili1208 can you run this change through CI and merge if everything is green?

**Comment by zhili1208** [comment]
sure

**Comment by mishra14** [comment]
@zhili1208 any updates on this?

**Comment by zhili1208** [comment]
failed to build on CI, will rebase and run it through CI again

**Comment by emgarten** [comment]
It failed when I tried to build it also

**Comment by jbtule** [comment]
Honestly I can't get it to build mac/win/linux with the build script just on dev. However I can use dotnet build in that project and probably fixed this issue you were running into. 

I removed code where it was searching for msbuild.exe in the hardcoded paths I removed. Maybe this code worked in older versions of mono (not current) if an unusual case of msbuild not in the path env. But the current mono doesn't even have an msbuild.exe in those hardcoded paths. I think for all versions of mono, it's probably sufficient to look in the path env. 

But you decide.

I refactored the utility method for the tests to test for mono inside the utility method, but I don't know if this runs on linux, but it'll be easier to make sure it does with the refactor.

So there you go. Sorry it's not as simple as it looked.

**Comment by emgarten** [comment]
@zhili1208 can you run tests on this?

If everything is passing we should take this fix.

**Comment by rohit21agrawal** [comment]
@jbtule can you rebase your branch? we have made some changes in our CI, and we can't test this until you rebase it.

**Comment by jbtule** [comment]
I migrated away from the nuget client awhile ago, if you want to use this PR, feel free to rebase it, if you don’t, feel free to close this PR or use what you want from it. Thanks!

**Comment by emgarten** [comment]
Sorry to hear that @jbtule, we do appreciate the work! 🍰

**Comment by emgarten** [comment]
This is replaced by https://github.com/NuGet/NuGet.Client/pull/1946

It is the same change, there were no conflicts in this area. I'll let it run through the CI and see how tests run, I believe the original hold up on this was issues with our mono CI that have since been fixed.

**Pull request closed without merging**
