### PR TITLE
Enable help option on pack/push/delete

### PR DESCRIPTION
**Pull request by drewgillies**
Also renaming the app to give more correct usage text (nuget rather than nuget3).
@joelverhagen @alpaix @emgarten

### CODE REVIEW

**Comment by alpaix** [comment]
:shipit:

**Comment by emgarten** [comment]
:shipit:

**Comment by joelverhagen** [comment]
:shipit:

**Comment by drewgillies** [comment]
Part of this work: https://github.com/NuGet/Home/issues/3341

**Pull request merged**
