### PR TITLE
.NET code style settings for .editorconfig

### PR DESCRIPTION
**Pull request by alpaix**
Contributes to NuGet/Home#4722.

Enforce team code style settings (with IDE warnings):
- use `var`
- avoid `this.`
- use language keywords

### CODE REVIEW

**Comment by alpaix** [comment]
More details on [.NET Code Style Settings for .editorconfig](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference).

**Comment by emgarten** [comment]
This is awesome, I didn't know editorconfig could do all this! 

How many warnings does this cause in the code today? I would expect them all to be fixed as part of adding this :smile:

**Comment by alpaix** [comment]
This'd generate IDE-only warnings. Build passes just fine so this change is not intrusive. It'd rather assist you with identifying code styling issue early.

**Review by emgarten — APPROVED** [review]
✨

**Pull request merged**
