### PR TITLE
Use concurrent dictionary in related extensions calculation

### PR DESCRIPTION
**Pull request by nkolev92**
# Bug

Related: https://github.com/NuGet/Home/issues/12728 

## Description

It's failing the insertion: https://github.com/dotnet/sdk/pull/42458. 

## PR Checklist

- [x] Meaningful title, helpful description and a linked NuGet/Home issue
- [ ] ~Added tests~ Functional tests exist. The SDK side that caught this test out graph build scenarios, which are more challenging to replicate. Since this is blocking an insertion, I have created a follow issue. https://github.com/NuGet/Home/issues/13678
- [x] Link to an issue or pull request to update docs if this PR changes settings, environment variables, new feature, etc.

### CODE REVIEW

**Review by dtivel — APPROVED** [review]

**Review by donnie-msft — APPROVED** [review]
Should we try to incorporate the check that failed in the SDK, or perhaps trigger the SDK tests for certain changes in our repo? That might help us catch these before insertion time.

**Comment by zivkan** [comment]
> - [ ] ~Added tests~ Tests already exist

The existing tests didn't catch the bug, so from the point of view of the checklist, I don't think the existing tests count.

**Comment by nkolev92** [comment]
The tests there are a bit involved and involve static graph builds, not regular builds (unrelated from static graph restore).
I'm not sure how to replicate those tests in our repo.

I can create an issue as a follow-up since this is blocking an insertion, but I'm not sure the effort is worth given that it was caught in the SDK repo.

**Comment by nkolev92** [comment]
Created an issue: https://github.com/NuGet/Home/issues/13678

**Review by zivkan — APPROVED** [review]

**Review by jeffkl — APPROVED** [review]

**Comment by nkolev92** [comment]
Interesting thing; https://dev.azure.com/dnceng-public/public/_build/results?buildId=766638&view=ms.vss-test-web.build-test-results-tab&runId=19539484&resultId=100859&paneView=debug. 

That PR had a failure due to the concurrent dictionary. 

I'll look into it, maybe there's hope for an easier test.

**Pull request merged**
