### PR TITLE
Improve grammar in error string.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/8707

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@yishaigalatzer What's the right process for getting this reviewed?  Thanks!

**Comment by CyrusNajmabadi** [comment]
also, is there a right way to test this locally?  Thanks!

**Comment by yishaigalatzer** [comment]
LGTM, @deepakaravindr can you merge?

@CyrusNajmabadi testing locally - build.ps1, you get a vsix and a nuget.exe, run your scenario and verify it. Since this is just a string change, I'm not too concerned

**Comment by CyrusNajmabadi** [comment]
Ok.  things look good on my end.  Merge whenever is good for you.

**Comment by emgarten** [comment]
Merged with NuGet/NuGet.Client@d91d4b95696d25c90f4b3810cfecf007ebaedf95

Thanks for the fix @CyrusNajmabadi

**Pull request closed without merging**
