### PR TITLE
Improve the product packing, remove NoPackageAnalysis, use targets to pack the commandline package, change buid.ps1 to not create the e2e package by default

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: 
Regression: No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details:
The motivation behind this was the frequent issues between our nupkg's metadata. 
I recently added the license expression metadata in all targets pack packages, but didn't change that in the nuspec. This change eliminates that.
Improve the product packing, remove NoPackageAnalysis, use targets to pack the commandline package, change buid.ps1 to create the e2e package by default.
I have also added an explicit switch to build the E2E package. 
In the 99.99% case we don't need it locally and nowadays we use the yaml script to build on the CI. 

## Testing/Validation

Tests Added: No  
Reason for not adding tests:  Infrastructure changes
Validation:

### CODE REVIEW

**Comment by nkolev92** [comment]
🔔 @NuGet/nuget-client

**Comment by nkolev92** [comment]
🔔 @NuGet/nuget-client

**Review by zivkan — APPROVED** [review]
👍 

at some point we should change the target names to something other than VS15. It would be good if it's not version specific, but VS16 is better than VS15 since we're now targeting it.

**Comment by nkolev92** [comment]
@zivkan 
Good point. 
That's quite an involved change though that involves lots of yaml script changes so the sole reason I haven't bothered with is because the turnaround is much slower :)

**Pull request merged**
