### PR TITLE
Cleanup restore message 

### LINKED ISSUE #8977: Don't bother logging small millisecond times in restore messages
In the log of the build for dotnet/runtime we have many lines like
```
  Restore completed in 545.01 ms for C:\Users\danmose\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19617.1\tools\Tools.proj.
  Restore completed in 41.68 ms for C:\git\runtime\src\installer\pkg\packaging\pack-managed.proj.
  Restore completed in 41.68 ms for C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetAppHost\Microsoft.NETCore.DotNetAppHost.pkgproj.
  Restore completed in 56.98 ms for C:\git\runtime\src\installer\pkg\packaging\vs-insertion-packages.proj.
  Restore completed in 1.77 ms for C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetHostPolicy\Microsoft.NETCore.DotNetHostPolicy.pkgproj.
  Restore completed in 59 ms for C:\git\runtime\src\installer\corehost\build.proj.
  Restore completed in 63.74 ms for C:\git\runtime\src\installer\managed\Microsoft.DotNet.PlatformAbstractions\Microsoft.DotNet.PlatformAbstractions.csproj.
  Restore completed in 58.09 ms for C:\git\runtime\src\installer\managed\Microsoft.Extensions.DependencyModel\Microsoft.Extensions.DependencyModel.csproj.
  Restore completed in 59.85 ms for C:\git\runtime\src\installer\managed\Microsoft.NET.HostModel\Microsoft.NET.HostModel.csproj.
  Restore completed in 1.58 ms for C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Host.pkgproj.
  Restore completed in 2.01 ms for C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\legacy\Microsoft.NETCore.App.pkgproj.
  Restore completed in 1.73 ms for C:\git\runtime\src\installer\pkg\projects\netcoreapp\sfx\Microsoft.NETCore.App.Bundle.bundleproj.
  Restore completed in 1.56 ms for C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetHostResolver\Microsoft.NETCore.DotNetHostResolver.pkgproj.
  Restore completed in 1.51 ms for C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetHost\Microsoft.NETCore.DotNetHost.pkgproj.
  Restore completed in 1.59 ms for C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj.
  Restore completed in 20.41 ms for C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Runtime.pkgproj.
...
```
I suspect there aren't any circumstances where anyone wants to know it took 1510 microseconds to restore Microsoft.NETCore.DotNetHost.pkgproj: it's just visual noise. How about just logging:
```
  Restored C:\Users\danmose\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19617.1\tools\Tools.proj.
```
Or, if it's important to log the time when it's "slow", we could log it if it's over, say, 500ms, eg:
```
  Restored C:\Users\danmose\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19617.1\tools\Tools.proj (took 545ms)
  Restored C:\git\runtime\src\installer\pkg\packaging\pack-managed.proj.
  Restored C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetAppHost\Microsoft.NETCore.DotNetAppHost.pkgproj.
  Restored C:\git\runtime\src\installer\pkg\packaging\vs-insertion-packages.proj.
  Restored C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetHostPolicy\Microsoft.NETCore.DotNetHostPolicy.pkgproj.
  Restored C:\git\runtime\src\installer\corehost\build.proj.
  Restored C:\git\runtime\src\installer\managed\Microsoft.DotNet.PlatformAbstractions\Microsoft.DotNet.PlatformAbstractions.csproj.
  Restored C:\git\runtime\src\installer\managed\Microsoft.Extensions.DependencyModel\Microsoft.Extensions.DependencyModel.csproj.
  Restored C:\git\runtime\src\installer\managed\Microsoft.NET.HostModel\Microsoft.NET.HostModel.csproj.
  Restored C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Host.pkgproj.
  Restored C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\legacy\Microsoft.NETCore.App.pkgproj.
  Restored C:\git\runtime\src\installer\pkg\projects\netcoreapp\sfx\Microsoft.NETCore.App.Bundle.bundleproj.
  Restored C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetHostResolver\Microsoft.NETCore.DotNetHostResolver.pkgproj.
  Restored C:\git\runtime\src\installer\pkg\projects\Microsoft.NETCore.DotNetHost\Microsoft.NETCore.DotNetHost.pkgproj.
  Restored C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj.
  Restored C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Runtime.pkgproj.
```
I'd be happy to offer a change.

### PR DESCRIPTION
**Pull request by danmoseley**
## Bug

Fixes: https://github.com/NuGet/Home/issues/8977
Regression: No  

## Fix

Remove timestamp except for "DotnetToolReference" (I can remove for that too if you like)

## Testing/Validation

Tests Added: No  
Reason for not adding tests:  Didn't see tests for these messages
Validation:   Forced each path in debugger.

### CODE REVIEW

**Comment by danmoseley** [comment]
I didn't modify `DotnetToolReference` because I couldn't figure out how to create one other than setting `<RestoreProjectStyle>DotnetToolReference</RestoreProjectStyle>`

Perhaps its message should be `<value>Restored tool</value>`

**Comment by danmoseley** [comment]
@nkolev92 does this look OK?

**Comment by nkolev92** [comment]
I think we should keep the timing, just at the end, but that's just my preference. 

@NuGet/nuget-client , @aortiz-msft @rrelyea @karann-msft @anangaur Thoughts?

**Comment by anangaur** [comment]
I cannot make out what’s being discussed 😀. Can somebody put the details as to how the old vs. new messaging looks?

**Comment by nkolev92** [comment]
When restore completes the current message is: 

`Restore completed in {0} for {1}.`

```
Restore completed in 1.59 ms for C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj.
Restore completed in 20.41 ms for C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Runtime.pkgproj.
```

The proposal is to change it to: 

```
Restored C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj.
Restored C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Runtime.pkgproj.
```

I am favoring: 

```
Restored C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj. (took 1.59ms)
Restored C:\git\runtime\src\installer\pkg\projects\netcoreapp\pkg\Microsoft.NETCore.App.Runtime.pkgproj. (took 20.41ms)
```

**Comment by danmoseley** [comment]
The way I think of MSBuild logging verbosities is:

* Quiet -- this is when you only want Errors/Warnings. The VS Error list kind of scenario.
* Minimal -- this is to see coarse grained progress, probably in the console output. A typical C# project will emit one line here, and another if you restore it. (This should have been the default for msbuild.exe, and it's common for scripts that wrap the build to dial down console output to Minimal). The VS Output window scenario also.
* Normal -- this is for a developer working on the code to figure out what the build did at a coarse level -- for example, to verify what defines go to the compiler. (We should not have made it the msbuild.exe default: that was a mistake)
* Detailed -- this is for figuring out _exactly what_ the build did, probably because there's a bug with the build or you're maintaining it.
* Diagnostic -- this is for figuring out to the nth degree _why_ the build did what it did. shows timings and properties

It's obviously your call what the message is 😄 my main motivation here was that this displays in Minimal, where I simply want to know where the build has gotten to and whether it's failed. Not that the restore step took 1.59 milliseconds.

**Comment by danmoseley** [comment]
I'd be happy to update the PR to match whatever you wish :)

**Comment by nkolev92** [comment]
I discussed this with @anangaur and we'd like to keep the time taken. 

We've actually had some feedback on that in the past, and it's especially useful when the restore takes a while.

**Comment by danmoseley** [comment]
Sure - I'll update the PR to match your examples above.

Is it OK if I round to whole milliseconds?

**Comment by anangaur** [comment]
> Is it OK if I round to whole milliseconds?

I think that makes sense. Leave <0 ones as is, if such cases arise.

**Comment by aortiz-msft** [comment]
NIT: What about:

`Restored C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj in 1ms`

It is shorter than:

`Restored C:\git\runtime\src\installer\pkg\projects\netstandard\pkg\NETStandard.Library.Ref.pkgproj. (took 1ms)`

**Comment by danmoseley** [comment]
My 2c: I find the parenthesized version easier to read, since i never care about the timings.

**Comment by danmoseley** [comment]
Updated. I ended up with "in" instead of "took" because it formed a sentence "restored foo in bar":
```
  Restored C:\proj\test\test.csproj (in 32 ms)
  Restored C:\proj\test2\test.csproj (in 159 ms)
  Failed to restore C:\proj\test3\test.csproj (in 3.08 sec)
```

**Comment by danmoseley** [comment]
Rebased to fix some tests.

**Comment by danmoseley** [comment]
@nkolev92 do you have to do something to make CI work? can you give me the power :)

**Comment by danmoseley** [comment]
@dtivel how do I make CI work?

**Comment by nkolev92** [comment]
@danmosemsft When working from a fork, we trigger the CI by applying a label. 

I saw a few failures in the run I triggered yesterday, but it doesn't look like they should've been affected by your change. 

I kicked the tests off again, as the 2 tests that failure have not shown any signs of flakiness.

**Comment by danmoseley** [comment]
I see. Some of the failures I saw were because a baseline had "2019" in it, which I saw was subsequently fixed. I did not understand the other failures.

**Comment by danmoseley** [comment]
Ah, of the ones today I see 3 look like they need a baseline update from me. 

`DotnetRestore_ProjectMovedDoesNotRunRestore` does not seem obviously releated:
```
E:\A\_work\258\s\.test\work\d86c7066\76c0c8f3\sdk\3.1.200-preview-014882\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'E:\A\_work\258\s\.test\work\98fcedf0\dff8c350\globalPackages\x\1.0.0\lib\net472\x.dll' could not be opened -- PE image doesn't contain managed metadata. [E:\A\_work\258\s\.test\work\98fcedf0\dff8c350\solution\ClassLibrary1\ClassLibrary1.csproj]
```

**Comment by nkolev92** [comment]
DotnetRestore_ProjectMovedDoesNotRunRestore is actually a legit failure. 

It's asserting for a message, and it can't find "Restore completed" anymore because we are switching the ordering from Restore completed for...to Restored..

DotnetToolTests_BasicDotnetToolRestore_SucceedsAsync is not report the error correctly, I'd suggest trying to run the test and see where exactly it's failing. Looking at the asserts it's not obvious to me, why this change could affect it, since the tool restore message is not changed at all.

**Comment by zivkan** [comment]
@nkolev92 Is this PR still relevant since we merged #3111 ?

**Comment by nkolev92** [comment]
@zivkan 
Yeah because #3111 does not combine the messages in VS, so improving the message is still important.

**Comment by danmoseley** [comment]
@zivkan @nkolev92 I care about this PR but I have not had time yet to figure out the issues I had getting a clean build and test run. If you guys are interested in picking it up feel free 😸 otherwise it may still be a little while yet.

**Comment by nkolev92** [comment]
I'll take a stab at it.

**Comment by danmoseley** [comment]
@nkolev92 awesome! thank you

**Comment by nkolev92** [comment]
Fixed the failing tests and made the punctuation consistent (not caused by this change, but I messed it up during the rebase I think :)) . 

Kicked off the tests again, will merge if green.

**Review by nkolev92 — APPROVED** [review]

**Comment by danmoseley** [comment]
It's green 👍

**Comment by danmoseley** [comment]
Thank you @nkolev92

**Pull request merged**
