### PR TITLE
Add extra slash for property from GeneratePathProperty

### LINKED ISSUE #11737: The trailing slash in GeneratePathProperty causes ROBOCOPY failures
See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1496902. 

Orioginal issue is [1522444](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1522444)

### PR DESCRIPTION
**Pull request by Forgind**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11737

Regression? Yes Last working version: VS 2022 release

## Description

See https://github.com/NuGet/Home/issues/8871#issuecomment-1092273688

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
cc @jeffkl Can you help review this? 
If this change is good, it might be something that we'd need to consider patching.

**Comment by jeffkl** [comment]
@nkolev92 I'm leaning towards reverting the original change instead.  We have three options:

1. Leave the code as-is and offer a workaround for people affected
2. Take this change to add a second slash and hopefully that will work but seems a little hacky
3. Revert the change and get rid of the trailing slash since MSBuild now has a built-in mechanism for detecting runaway wildcards which was the motivation for the change originally.

I'd love to get more opinions so please weigh in @NuGet/nuget-client

**Comment by Forgind** [comment]
Small extra note:
If I remember correctly, the MSBuild change to detect drive enumerations is a warning/opt-in error. People who don't care about warnings probably wouldn't notice.

**Comment by nkolev92** [comment]
I'm comfortable with that.  

I can see the argument for either direction, but reverting might be the pragmatic solution

**Comment by jeffkl** [comment]
@Forgind thank you for the contribution but we've decided to revert the change instead for now.

**Pull request closed without merging**
