### PR TITLE
add review comment to sb files

### PR DESCRIPTION
**Pull request by oleksandr-didyk**
## Bug

Fixes:

Regression? Last working version:

## Description

Contributes to https://github.com/dotnet/source-build/issues/3435

Adds comments to source-build files asking for the inclusion of the source-build team in PRs that alter `SourceBuild*` files. Non-reviewed changes could potentially cause issues down the line, be it in the downstream repos or the product build (as has happened in the past, see https://github.com/dotnet/source-build/issues/3435#issuecomment-1570650046)

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Review by jeffkl — DISMISSED** [review]

**Comment by nkolev92** [comment]
You can really @ that team from the nuget org. 

@dotnet/source-build-internal doesn't do anything.

**Review by nkolev92 — CHANGES_REQUESTED** [review]
@dotnet/source-build-internal cannot be referenced from the nuget org.

**Comment by oleksandr-didyk** [comment]
> @dotnet/source-build-internal cannot be referenced from the nuget org.

Thanks for noticing, will think of some better way to handle this

**Comment by ghost** [comment]
This PR has been automatically marked as stale because it has no activity for **7 days**. It will be closed if no further activity occurs **within another 90 days** of this comment. If it is closed, you may reopen it anytime when you're ready again, as long as you don't delete the branch.

**Comment by oleksandr-didyk** [comment]
@nkolev92 apologies for taking longer to resolve the issue mentioned. We opted to simply including particular contributors in the review request instead of the team alias that is not available in the org

**Review by nkolev92 — APPROVED** [review]

**Comment by oleksandr-didyk** [comment]
@nkolev92 thanks for the review, unfortunately I don't have the write access to merge the PR. Could you please merge it? Thank you!

**Review by jeffkl — APPROVED** [review]

**Pull request merged**
