### PR TITLE
Stop running OptProf pipeline for release-6.2.x branch

### PR DESCRIPTION
**Pull request by kartheekp-ms**
## Bug

Fixes: https://github.com/NuGet/Client.Engineering/issues/2816

Regression? Last working version:

## Description

Stop running OptProf pipeline for 6.2.x release branch.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] N/A 

- **Documentation**
  - [x] N/A

### CODE REVIEW

**Review by donnie-msft — APPROVED** [review]

**Review by zivkan — APPROVED** [review]
We need to find a better long term solution, because in a few more releases, there will be more branches excluded than included.

**Comment by jeffkl** [comment]
> We need to find a better long term solution, because in a few more releases, there will be more branches excluded than included.

My vote is to rename the out-of-support branches

**Comment by nkolev92** [comment]
> > We need to find a better long term solution, because in a few more releases, there will be more branches excluded than included.
> 
> My vote is to rename the out-of-support branches

My suggestion would be to add a final tag and delete the unsupported branches.

**Comment by kartheekp-ms** [comment]
> We need to find a better long-term solution, because in a few more releases, there will be more branches excluded than included.

Created https://github.com/NuGet/Client.Engineering/issues/2821 to address the feedback.

**Pull request merged**
