### PR TITLE
remove project json restore request provider

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug
Fixes: https://github.com/NuGet/Home/issues/5252
Regression: No  
If Regression then when did it last work:   
If Regression then how are we preventing it in future:   

## Fix
Details: 

Minor cleanup of unused code.   

## Testing/Validation
Tests Added: Yes/No  
Reason for not adding tests:  
Validation done:

### CODE REVIEW

**Comment by nkolev92** [comment]
/cc @dagood 
I saw https://github.com/NuGet/Home/issues/6131, you're not using it anymore, correct?

**Comment by dagood** [comment]
Thanks for the ping, we still are, unfortunately:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/EncryptedConfigNuGetRestore.cs

A tracking issue on BuildTools to get that off project.json is https://github.com/dotnet/buildtools/issues/1550.
/cc @weshaggard

**Comment by nkolev92** [comment]
hmm...Are you still keeping up with the latest NuGet versions there?
I'd like to merge this, but it's not critical. 
Anything API wise we can provide to help?

**Review by jainaashish — APPROVED** [review]
🔪

**Comment by dagood** [comment]
As of now that lib is on NuGet `4.4.0`, so no, not really up to date looking at the gallery. 😃

The BuildTools move to MSBuild-based restore isn't blocked on anything in NuGet in particular, as far as I know.

**Comment by nkolev92** [comment]
@dagood If you're not ready to move to PR yet, the change in that should be simple, just update to not extending the ProjectJsonRestoreRequestProvider, and add an extra method. 

I'd be happy to do that myself if you want.

**Comment by dagood** [comment]
Ah, good point! I added a description of that way of getting around it to https://github.com/dotnet/buildtools/issues/1885, and I think having that in mind is enough to have very little risk no matter where we end up going.

**Pull request merged**
