### PR TITLE
Fix the typo in the nuget trusted-signers command examples

### LINKED ISSUE #7888: typo in nuget trusted-signers -h examples
image

should be
`nuget(no-hyphen but space)trusted-signners....`

### PR DESCRIPTION
**Pull request by heng-liu**
## Bug

Fixes:  [NuGet/Home#7888](https://github.com/NuGet/Home/issues/7888)  
Regression: No  
* Last working version:   
* How are we preventing it in future:   

## Fix

Details: Correct typo by removing hyphen  

## Testing/Validation

Tests Added: No  
Reason for not adding tests:  
Validation:

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
Change looks good, can you rebase so the tests re-run.

**Review by dtivel — APPROVED** [review]
Also see https://docs.microsoft.com/en-us/nuget/tools/cli-ref-trusted-signers#examples

**Comment by nkolev92** [comment]
@heng-liu 
Can you do some quick work to rebase this so we can get it merged?

I'm trying to cleanup the outstanding PRs.

**Comment by nkolev92** [comment]
I have rebased and pushed so the tests can rerun.

**Comment by nkolev92** [comment]
All tests have passed. Can you please merge?

**Comment by zivkan** [comment]
@heng-liu Can you merge this?

**Pull request merged**
