### PR TITLE
Close vulnerability info bar when the solution closes

### LINKED ISSUE #13055: Vulnerability InfoBar remains visible in the Solution Explorer after closing solution
When closing a solution when the vulnerability infobar was shown, I noticed that the infobar remains visible. When solutions are closed, this infobar should be removed since the context is no longer present in VS.

image

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes: https://github.com/NuGet/Home/issues/13055

Regression? Last working version:

## Description

We just listen to the solution open/close event of the solution manager.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [x] Automated tests added - Performed manual tests as well.
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by donnie-msft — DISMISSED** [review]

**Comment by nkolev92** [comment]
I'll retarget to dev and add tests.

**Comment by nkolev92** [comment]
@donnie-msft, Same PR as before, but now with tests.
I did implement some tests of the previous functionality.

**Review by donnie-msft — APPROVED** [review]
Looks good to me. I assume you tested with the VSIX itself?

**Comment by nkolev92** [comment]
Yeah, I did that even before the automated tests.

**Review by martinrrm — APPROVED** [review]

**Comment by nkolev92** [comment]
No RPS concerns, IVsSolutionManager is loaded in the solution restore job which calls the method.

**Pull request merged**
