### PR TITLE
Changing the dotnet cli version to the preview2 release, and changing…

### PR DESCRIPTION
**Pull request by toddm**
… the .NET references to stable release versions.

@emgarten @rohit21agrawal

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
you missed scripts\funcTests\runFuncTests.sh . it has a dotnet-install script too.

**Comment by toddm** [comment]
It now just calls the method in common.ps1:
Invoke-BuildStep 'Installing dotnet CLI' { Install-DotnetCLI } `
    -ev +BuildErrors

**Comment by toddm** [comment]
Never mind, I was looking at the ps1 script instead of the .sh script.

**Comment by rohit21agrawal** [comment]
LGTM :shipit:

**Comment by emgarten** [comment]
Finally stable! :tada: :balloon: :shipit:  :beers: :tada:

**Pull request merged**
