### PR TITLE
Test:  workaround dotnet-install.sh failing on macOS

### LINKED ISSUE #8362: Test:  .NET Core SDK 1.1.1 is failing to install on macOS
.NET Core SDK 1.1.1 install is failing in our CI pipeline on macOS.  The root problem is [this change](https://github.com/dotnet/cli/commit/7a1afb7e707e44fd3a3c6e0dd81dc92aa9b7f7d9#diff-3385102241bcd3718b9ca13a0c55b9afR615);  `--remove-directory` does not exist on macOS.

Example:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-sdk-1.1.11-osx-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-sdk-1.1.11-osx-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-dev-osx-x64.1.1.11.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-dev-osx-x64.1.1.11.tar.gz
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
/Users/buildagent/agent/_work/33/s/cli/dotnet msbuild build/config.props /v:m /nologo /t:GetCliBranchForTesting
/Users/buildagent/agent/_work/33/s/scripts/funcTests/runFuncTests.sh: line 48: /Users/buildagent/agent/_work/33/s/cli/dotnet: No such file or directory
/Users/buildagent/agent/_work/33/s/scripts/funcTests/runFuncTests.sh: line 49: /Users/buildagent/agent/_work/33/s/cli/dotnet: No such file or directory

cli/dotnet-install.sh: line 846: $1: unbound variable
/Users/buildagent/agent/_work/33/s/scripts/funcTests/runFuncTests.sh: line 55: /Users/buildagent/agent/_work/33/s/cli/dotnet: No such file or directory

```

### PR DESCRIPTION
**Pull request by dtivel**
Fix https://github.com/NuGet/Home/issues/8362 to workaround https://github.com/dotnet/cli/issues/11964.

### CODE REVIEW

**Review by zivkan — APPROVED** [review]
We should have a task to remove our dependency on the 1.x SDKs since they're out of support. I think we only use it for some tests.

Do you think we should also move back to the dotnet-install.sh from the master branch when possible? I changed it to the master branch, instead of a specific commit, a few months ago because it was using a very old version of the script that didn't work for something, though I can't remember what exactly.

**Comment by dtivel** [comment]
https://github.com/NuGet/Home/issues/8365 is for updating .NET Core SDK version in this file.

**Comment by dtivel** [comment]
https://github.com/NuGet/Home/issues/8366 tracks retargeting the `master` branch script dotnet-install.sh when https://github.com/dotnet/cli/issues/11964 is fixed.

**Comment by heng-liu** [comment]
@zivkan the script runFuncTests.sh download dotnet version 1.0 to bootstrap testing version. That is , making it possible to run "dotnet msbuild" command, in order to get the testing version of SDK we specified in config.props.

**Comment by zivkan** [comment]
@heng-liu  `dotnet msbuild` will work with any version of the SDK install, it's not necessary to have 1.x. If that's really the only reason we have 1.x installed, it will be really trivial to remove this from our scripts.

**Pull request merged**
