### PR TITLE
Improved performance and fixed how the PrivateAssets flow to transitively pinned centrally managed dependencies

### LINKED ISSUE #12270: PrivateAssets flow incorrectly to transitively pinned centrally managed dependencies
### NuGet Product Used

dotnet.exe

### Product Version

7.0.100

### Worked before?

no

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

For project:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json.Bson" PrivateAssets="Compile;Runtime" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" PrivateAssets="Compile" />
  </ItemGroup>
</Project>
```
and `Directory.Packages.props`:
``` xml
<Project>
    <ItemGroup>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageVersion Include="Newtonsoft.Json.Bson" Version="1.0.2" />
        <PackageVersion Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
    </ItemGroup>
</Project>
```

The expected content of `centralTransitiveDependencyGroups` is:
``` json
"centralTransitiveDependencyGroups": {
    ".NETStandard,Version=v2.0": {
      "Newtonsoft.Json": {
        "include": "Runtime, Compile, Native, BuildTransitive",
        "version": "[13.0.1, )"
    }
  }
}
```
, but the SDK 7.0.100 produces empty `centralTransitiveDependencyGroups`.

PS:
I'm going to submit a PR with a fix.

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by marcin-krystianc**
## Bug

Fixes: https://github.com/NuGet/Home/issues/12270, https://github.com/NuGet/Home/issues/12269

Follows up the https://github.com/NuGet/NuGet.Client/pull/4669

## Description

..work in progress..

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by erdembayar** [comment]
@marcin-krystianc 
Description states "..work in progress..". Is it ready for review or not? If yes, please update the description.

**Comment by nkolev92** [comment]
Thanks for the contribution @marcin-krystianc 

I also see 2 different issues are being addressed by this PR, one a functional, the other one a perf issue. Any chance those can be split into separate PRs to make reviewing easier?

**Comment by marcin-krystianc** [comment]
> Description states "..work in progress..". Is it ready for review or not? If yes, please update the description.

Yes, sorry I didn't manage to finish the description yesterday. ~~Also, I realized that it is not possible to convert it into a draft PR (for a reason which is unknown to me).~~
I think that @nkolev92 is right, this PR should be split into smaller changes that can be reviewed separately.

**Comment by marcin-krystianc** [comment]
Opening smaller PRs, the first one is https://github.com/NuGet/NuGet.Client/pull/4950

**Pull request closed without merging**
