### PR TITLE
Add NetStandard2.0 and NetCoreApp2.0 (#1043)

### PR DESCRIPTION
**Pull request by ericstj**
Adds NetStandard2.0 TFM and makes it compatible with NetCoreApp2.0,
net461, and all Xamarin TFMs (which always get latest NetStandard).

This is a cherry-pick of 
https://github.com/NuGet/NuGet.Client/commit/42f35734df23fc9a5b1c9ab5f30cf342c8fdd842
https://github.com/NuGet/NuGet.Client/commit/936cf808159315ca62f082450f86f545a6397191

I squashed them since its no longer interesting that we did a rename from netcoreapp1.2 to 2.0.

### CODE REVIEW

**Comment by maartenba** [comment]
Is there a package out there that has these TFM's?

**Comment by ericstj** [comment]
@maartenba do you mean a nuget package that implements support or a packages which make use of that support?

Some of the latest corefx packages use this.  For example https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Collections.Immutable/1.4.0-beta-25027-01

**Comment by maartenba** [comment]
One that implements support :-)

**Comment by ericstj** [comment]
Internal share is here: \\\\nuget\NuGet\Share\Drops\CI\NuGet.Client\release-4.1.0-netstandard2.0\2321
Publicly available one is here: https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Frameworks/4.0.1-beta-2321

**Comment by maartenba** [comment]
Thanks!

**Pull request merged**
