### PR TITLE
Issues: 5893 and 5850 for dotnet.exe

### PR DESCRIPTION
**Pull request by nschwerzler**
## Bug
Fixes: 

Issue 5893: Feature Request: Need the ability for NuGet.exe pack to create a nupkg without the version in the package name

Issue 5850: Feature Request: NuGet.exe pack should drop resolved nuspec to support network share hosted Package Source

Regression: No  

## Fix
Added features for dotnet.exe. These were already added to nuget.exe

## Testing/Validation
Tests Added: Yes
Validation done: Unit tests

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@nschwerzler could you rebase with dev? it won't run on CI until you do.

**Comment by nschwerzler** [comment]
Rebased with dev

**Comment by rohit21agrawal** [comment]
@nschwerzler are you going to be working on this?

**Comment by nschwerzler** [comment]
Yes I plan to complete this, just haven't had a chance yet.

**Review by rohit21agrawal — APPROVED** [review]

**Pull request merged**
