### PR TITLE
Adding xml docs to nuget.core projects

### PR DESCRIPTION
**Pull request by emgarten**
This change adds intellisense xml to the nupkgs produced for nuget.core.sln. I've fixed a few projects which did not have warnings as errors turned on, and also added exceptions for warnings due to XML docs. Where the docs were incorrect and had the wrong parameter names I've made changes, but overall I've tried to avoid updating the comments as part of this PR.

//cc @joelverhagen @zhili1208 @spadapet @alpaix

### CODE REVIEW

**Comment by joelverhagen** [comment]
Cool. Are those `nowarn` values to stay? Or is the goal to eventually get rid of those?

:shipit:

**Comment by emgarten** [comment]
@joelverhagen getting rid of all of them would mean fully commenting every method and parameter. Some of the warnings are from the compiler being unable to resolve `<cref>` parameters, it's unclear if we are really doing something wrong there. Other warnings are from partially commented methods.

**Comment by spadapet** [comment]
:shipit:

**Comment by alpaix** [comment]
@emgarten Can you file a bug then to complete the docs?

**Comment by alpaix** [comment]
otherwise looks :cool:
:shipit:

**Pull request closed without merging**
