### PR TITLE
Fix dotnet install script call - Use -InstallDir instead of -i

### PR DESCRIPTION
**Pull request by nkolev92**
## Bug

Fixes:https://github.com/NuGet/Client.Engineering/issues/963

Regression? Last working version:

## Description

Fix the call to the script - Broken in https://github.com/dotnet/install-scripts/pull/177 due to the addition of the `-Internal` parameter which created ambiguity.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

**Review by heng-liu — APPROVED** [review]

**Comment by nkolev92** [comment]
Related: https://github.com/dotnet/install-scripts/issues/189

**Review by heng-liu — CHANGES_REQUESTED** [review]
Seems Line 260 and 263 needs to be changed as well.

**Comment by kartheekp-ms** [comment]
@heng-liu I pushed another commit modifying lines 260-263 and then I noticed your [comment](https://github.com/NuGet/NuGet.Client/pull/4067#pullrequestreview-663889590). I did that because the issue is blocking all our builds. If CI passes, we should be good.

**Review by heng-liu — APPROVED** [review]

**Comment by dominoFire** [comment]
Should this be cherry-picked to service branches (release-5.11.x, release-5.10.x) ?

**Comment by heng-liu** [comment]
My guess is yes? Hi @zivkan, any advise? Thanks!

**Comment by zivkan** [comment]
Yes, we should keep supported branches building, although at this time only `release-5.11.x` is (I'm making progress on the rest)

**Pull request merged**
