### PR TITLE
Updating NuGet version to v3.4.4

### PR DESCRIPTION
**Pull request by alpaix**
Ran a script to update NuGet version everywhere.
Please review and approve.

//cc @rrelyea @emgarten

### CODE REVIEW

**Comment by emgarten** [comment]
I think @deepakaravindr made a list of all the places this needs to change, but I'm not sure where it is. 

Overall this LGTM :shipit:

**Comment by rrelyea** [comment]
:shipit:  
nice improvement to find the nuget root.

**Comment by rrelyea** [comment]
talking with @emgarten, he now thinks Deepak was making a list...and then decided to put the list into script form.

**Comment by alpaix** [comment]
The list you were talking about is the last 3 files:

```
    "src\NuGet.Clients\VsExtension\source.extension.vsixmanifest",
    "src\NuGet.Clients\VsExtension\NuGetPackage.cs",
    "build\common.props"
```

**Pull request merged**
