### PR TITLE
Linux test run

### PR DESCRIPTION
**Pull request by victorhurdugaci**
- Script to run the Nuget.Core tests on linux.
- Updated NuGet.Config because linux is case sensitive

Please review @MeniZalzman

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
Looks good

**Comment by yishaigalatzer** [comment]
Looks good. Please no merges until we cut the 3.3 branch

**Comment by victorhurdugaci** [comment]
@yishaigalatzer @MeniZalzman did you cut for 3.3?

**Comment by MeniZalzman** [comment]
we are still working on last changes, once we will open DEV branch i will let you know.

**Comment by victorhurdugaci** [comment]
You guys have to merge it anyway because I don't have permissions :)

**Comment by emgarten** [comment]
NuGet/NuGet.Client@b4d83007e46c16002f822e36a77713ac80311207

**Pull request closed without merging**
