### PR TITLE
Daravind/pr from aarnott - Use the $(UserProfile) MSBuild macro where possible

### PR DESCRIPTION
**Pull request by deepakaravindr**
Ported https://github.com/NuGet/NuGet3/pull/100
Issue: https://github.com/NuGet/Home/issues/1095

@yishaigalatzer @AArnott @MeniZalzman @emgarten @zhili1208

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
:shipit: after manually testing it to work

**Comment by deepakaravindr** [comment]
Tested it manually. Check out snapshot below

image

**Comment by deepakaravindr** [comment]
Merged with https://github.com/NuGet/NuGet.Client/commit/746dd342c811080b866c66a3375f11b9eecd23af and https://github.com/NuGet/NuGet.Client/commit/00a92323e4b233fa8719569b3fb47f34505d8fd1

**Pull request closed without merging**
