### PR TITLE
ConcurrencyUtilities: Rethrow PathTooLongException to break out of the loop

### PR DESCRIPTION
**Pull request by lbargaoanu**
Fixes NuGet/Home#7530. The second commit is somewhat beside the point, so if it's problematic I'll just revert it.

### CODE REVIEW

**Comment by jainaashish** [comment]
@lbargaoanu revert the second commit, then it should be good.

**Comment by lbargaoanu** [comment]
Done.

**Review by jainaashish — APPROVED** [review]

**Comment by jainaashish** [comment]
@lbargaoanu Your test has failed in our CI machine with `Expected System.IO.PathTooLongException, but no exception was thrown.` Please fix it n then we can merge this PR.

**Review by nkolev92 — APPROVED** [review]

**Comment by lbargaoanu** [comment]
I've increased the length of the root folder and it seems to fail in the exact same way. If the test needs to be resilient to long paths being allowed, I could do that.

**Pull request merged**
