### PR TITLE
Issue 2335: NuGet.exe not FIPS compliant.

### LINKED ISSUE #2335: NuGet.exe uses a non-FIPS-compliant implementation of SHA256
Using NuGet.exe and the Credential Provider from:
https://{account}.pkgs.visualstudio.com/_apis/public/nuget/client/CredentialProviderBundle.zip
We get the following error when trying to use NuGet.exe on machines where FIPS is enabled:

'This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.'

We need to be able to use NuGet.exe and the credential provider from FIPS enabled systems

### PR DESCRIPTION
**Pull request by TimBarham**
Currently, `SHA512.Create()` will always use the `SHA512Managed` class, which is not FIPS compliant and will throw an exception when FIPS compliance is turned on in Windows.

We have code in `Configuration.CryptoHashProvider` that uses the appropriate class when FIPS compliance is turned on. I've switched `Packaging.PackageExtractor` to use that logic.

I expect that ideally this shared logic should live in a more common location (`NuGet.Common`, I guess?), but we would like to get this change in by EOW, and I'm OOF for the next two days. Either we can take this as is for now, and I can clean it up next week, or someone else could take on that task tomorrow.

This resolves https://github.com/NuGet/Home/issues/2335

### CODE REVIEW

**Comment by emgarten** [comment]
I agree with moving it to Common. Packaging shouldn't take a dependency on configuration just for this.

**Comment by emgarten** [comment]
:watch:

**Comment by TimBarham** [comment]
@emgarten - updated to move `CryptoHashProvider` to `Common`.

**Comment by emgarten** [comment]
LGTM :shipit:

**Pull request merged**
