### PR TITLE
Configuration Fix

### PR DESCRIPTION
**Pull request by zhili1208**
https://github.com/NuGet/Home/issues/2233

this fix is when clear tag is in local config, we don't load cleared config file and also don't modify them.

### CODE REVIEW

**Comment by emgarten** [comment]
The new behavior is that the feed will be added to the global config even though it is blocked by the clear?

**Comment by zhili1208** [comment]
v3 always will be added to global config by default, but user can delete it, we won't add it back, In this bug, the problem is user just put clear in local config, but it will delete v3 from global one, then when user switch to another solution which doesn't contain clear, the source will be empty. we should not modify the global config when user modify local config.

**Comment by emgarten** [comment]
That makes sense

**Comment by emgarten** [comment]
:shipit:

**Comment by emgarten** [comment]
:rocket:

**Pull request closed without merging**
