### PR TITLE
Fix project.json schema change warnings

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by alpaix** [comment]
:shipit: Please push soon!

**Comment by pranavkm** [comment]
Is dev the right branch to push this change?

**Comment by alpaix** [comment]
First of all to dev, then cherry-pick it to release-3.5.0-beta2

**Comment by pranavkm** [comment]
Done.

**Comment by pranavkm** [comment]
Merged in https://github.com/NuGet/NuGet.Client/commit/e13e27153f0ddb563ff2d85f6deb965a237d19a7

**Pull request closed without merging**
