### PR TITLE
skip 2 Apex tests with IPC error

### PR DESCRIPTION
**Pull request by heng-liu**
## Bug

Tracking issue: NuGet/Home#11308

Regression? Last working version:

## Description
Looked at Azure Pipeline's build analytics, found the Apex tests that are failing most regularly, and skip them.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Comment by nkolev92** [comment]
Are we going the right direction here by continously skipping these tests?

To my understanding, these specific tests don't do anything special in comparison to ones that are enabled.

This seems like infra issues to the point that we'd eventually end up disabling most if not all of our tests.

**Comment by erdembayar** [comment]
> Are we going the right direction here by continously skipping these tests?
> 
> To my understanding, these specific tests don't do anything special in comparison to ones that are enabled.
> 
> This seems like infra issues to the point that we'd eventually end up disabling most if not all of our tests.

This concern is valid, but same Apex tests are failing so many times, it dragging down productivity. I believe we have ongoing emailthread about Apex test.

**Comment by nkolev92** [comment]
> > Are we going the right direction here by continously skipping these tests?
> > To my understanding, these specific tests don't do anything special in comparison to ones that are enabled.
> > This seems like infra issues to the point that we'd eventually end up disabling most if not all of our tests.
> 
> This concern is valid, but same Apex tests are failing so many times, it dragging down productivity. I believe we have ongoing emailthread about Apex test.


I'm not saying we don't skip these. 

I'm aware of that thread, but the takeaway there was that if we start seeing more tests we do something different, like maybe disable the suite.

**Comment by heng-liu** [comment]
Thanks for reviewing!
I'm afraid we haven't figured out why this error occurs.
I could see all those tests skipped for "IPC" error have the NuGetWpfTheory attributes. But I'm not sure if that's strong enough evidence to skip all Apex tests with NuGetWpfTheory attributes, as that's just my guess.
So for now, I'd like to just skip the Apex tests which failed very often.

**Review by erdembayar — APPROVED** [review]

**Review by donnie-msft — APPROVED** [review]
I believe we should disable Apex tests until infrastructure issues are resolved. 
One mitigation is to manually run Apex tests locally when commits may affect tested scenarios.

**Comment by erdembayar** [comment]
> I believe we should disable Apex tests until infrastructure issues are resolved. One mitigation is to manually run Apex tests locally when commits may affect tested scenarios.

Are we going to merge this?

**Pull request merged**
