### PR TITLE
Microsoft.Web.XmlTransform.resources.dll path fixed for signing

### PR DESCRIPTION
**Pull request by jainaashish**
We were looking for this dll inside Artifacts directory where as it will be available under solution packages folder so fixed it.

@rrelyea

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
It is localised and copied to the artifacts directory. Refer to loc.proj for more details

**Review by rohit21agrawal — CHANGES_REQUESTED** [review]
No need for this change

**Comment by jainaashish** [comment]
@rohit21agrawal  ahh i see that, but then why are they saying that it's not being signed. Refer internal bug# 442436

**Comment by jainaashish** [comment]
And also i didn't quite clearly get why are we localizing this dll?

**Comment by rohit21agrawal** [comment]
There were a few builds where it wasn't being signed and i fixed it in a recent PR. Can you check the latest builds to open the vsix and see if if it is signed? Last i checked, there weren't any issues with signing

**Comment by rohit21agrawal** [comment]
We can talk about it tomorrow when am back. Typing from my phone is a pain.

**Comment by jainaashish** [comment]
sure, we'll discuss it tomorrow.

**Comment by rohit21agrawal** [comment]
https://github.com/NuGet/NuGet.Client/pull/1385

**Review by emgarten — APPROVED** [review]
LGTM 🚀

**Pull request merged**
