### PR TITLE
Fix target frameworks for Source Build

### LINKED ISSUE #13390: Regression in target frameworks for source build
After https://github.com/NuGet/NuGet.Client/pull/5735 we're seeing a different target framework for the projects when building nuget.client from source.

It is now only building for netstandard2.0 instead of net9.0+netstandard2.0. This breaks the sdk update PR in https://github.com/dotnet/installer/pull/19412

**Before:**
image

**After:**
image

/cc @jeffkl @nkolev92

### PR DESCRIPTION
**Pull request by jeffkl**
## Bug

Fixes: https://github.com/NuGet/Home/issues/13390

Regression? Last working version:

## Description

I messed up the target frameworks when building for Source Build in https://github.com/NuGet/NuGet.Client/pull/5735.  This fixes it so that our libraries target .NET 9.0 and .NET Standard 2.0 like before.

### Without Source Build 
image

### With Source Build
image

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]

**Comment by kasperk81** [comment]
> Source Build — Succeeded 

it was also passing before because lack of coverage, if so, can we add a test in this repo to make it future proof? nuget->sdk->installer is a long way to validate stuff imo. but if it's not a every-other-day-problem, lets leave it to that.

**Comment by jeffkl** [comment]
> > Source Build — Succeeded
> 
> it was also passing before because lack of coverage, if so, can we add a test in this repo to make it future proof? nuget->sdk->installer is a long way to validate stuff imo. but if it's not a every-other-day-problem, lets leave it to that.

We'd love to improve the testing so we don't find out about breakages later.  Do you have any suggestions of how to get more coverage?

**Comment by kasperk81** [comment]
> Do you have any suggestions of how to get more coverage?

e.g. building a test project against oldest and newest framework consuming `SignatureUtility` (which caused the breakage https://github.com/dotnet/installer/pull/19412#issuecomment-2049342305)

**Comment by nkolev92** [comment]
> > Do you have any suggestions of how to get more coverage?
> 
> e.g. building a test project against oldest and newest framework consuming `SignatureUtility` (which caused the breakage [dotnet/installer#19412 (comment)](https://github.com/dotnet/installer/pull/19412#issuecomment-2049342305))

We have tests like this, it's the fact that source-build does things differently that's the real problem.

**Comment by kasperk81** [comment]
@nkolev92 i was also talking about source build leg, the one which run in the ci of this repo. that one can capture such tests, perhaps? btw, it's not a problem with nuget, it's a bigger problem happens every now and then with aspnctcore, runtime and others: some change was made, then sdk build was green and three repos down installer build failed. then we start tracking the change.

guess installer to sdk merge will improve this experience a bit (https://github.com/dotnet/sdk/pull/38804). 🤞

**Pull request merged**
