### PR TITLE
Replaced codeplex issue reference with github issue reference

### LINKED ISSUE #8408: NuGet should not generate binding redirects for binaries that are in the current framework
This is copy of codeplex issue number 3072 as it is referenced inside code. I should do a PR shortly to address this one.

The place where it is referenced is RuntimeHelper.cs:150

---

We're hitting an issue with Microsoft.Bcl package where NuGet is adding a binding redirect for a binary that is considered part of the framework, this causes the application to crash because the binding redirect refers to assembly version that is not available at runtime.

@Repro:

1. Create a new Console Application targeting 4.5
2. Create a new Portable Library targeting .NET Framework 4.5, Silverlight 4, Windows Phone 7.5 and .NET for Windows Store apps
3. Add a reference to the portable library from the Console Application
4. Install the Microsoft.Bcl package (1.0.16-rc) to both projects

@Expected: No binding redirect for System.Runtime in the .NET Framework 4.5 project because a ___later version___ is part of the target framework (see C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\RedistList\FrameworkList.xml)
@Actual: Binding redirect

<dependentAssembly>
<assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-1.5.11.0" newVersion="1.5.11.0" />
</dependentAssembly>

You can use the IVsFrameworkMultiTargeting to determine if a given assembly version is available as part of a given target framework.
Make sure when you fix this, that you only skip the binding redirect if ___a later or same version___ is available in the framework.  
2013-02-22

---

We'll do this in 2.4 release.  
2013-02-26

---

Is IVsFrameworkMultiTargeting.IsReferenceableInTargetFx the method I need to call? What should I pass to pwszAssemblySpec?  
2013-06-08

---

It's the full name of the assembly (mscorlib, Version=[version], PublicKeyToken=[token], Culture=[culture]). It can either contain all the information (key, version, etc), or just the simple name ("mscorlib")  
2013-06-10

---

So look like I can only check for the same version of the target framework. Can't check for a later version using this method, because I don't know what future versions will be.  
2013-06-12

---

That's fine. That's exactly the behavior we want. For example, System.Runtime didn't ship in 4.0, but did in 4.5. We still want a binding redirect generated for it in 4.0, but not for 4.5.  
2013-06-13

---

I followed the exact same steps above, but there's no binding redirect added to the Console Application. It's only added to the __Portable Library project__. Is that the bug?  
2013-06-13

---

The binding redirects added to the Portable Library project seems to come from the Microsoft.Bcl package itself (from the content folder's app.config.transform file). this looks like a non-bug.
2013-06-13

  
I'm chasing up the repro with Eric St. John. He walked through the code and figured out where it was broken.

It's the not the app.config.tranform, notice how the net45 content is empty, and hence no transforms. We also marked our transforms with a special marker that indicates that we added the redirects . The binding redirects we were seeing were not coming from us.  
2013-06-13

---

Are you seeing the binding redirects added to the Console Application or the Portable Library? I don't see binding redirect added to Console Application, only the Portable Library.  
2013-06-13

---

Yes I'm talking about the ConsoleApplication. The binding redirects in the portable library project are expected, and do not affect runtime behavior (as the app.config is ignored and not copied to the app project), and hence can't cause an application to crash.

I've found another repro (NuGet has really weird logic around when it decides to add binding redirects so it was hard to find a repro).

The repro is instead of using the Microsoft.Bcl package, install the Microsoft.Net.Http, 2.2.3-beta package. Make sure you are targeting __4.5__ from the ConsoleApplication and the exact platforms that I called out above for portable.  
2013-06-13

---

Also, the ConsoleApplication must be referencing the portable project before installing the package.  
2013-06-13

---

OK now I can repro  
2013-06-14

---

OK, I've got a fix now. It no longer adds the binding redirect for System.Runtime.dll, but still adds one for System.Net.Http.Primitives. I guess it's expected, right? Please confirm.

```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
<dependentAssembly>
<assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-4.2.3.0" newVersion="4.2.3.0" />
</dependentAssembly>
</assemblyBinding>
```  
2013-06-14

---

Yes that's correct. System.Net.Http.Primitives does not exist in the framework.  
2013-06-14

---

Fixed in changeset b8d515f6341193b970d2a9d837e580e762d2eb71  
2013-06-19

---

i get the same issue with my test project still, runtime being added... if i comment this out the tests run fine... if not i get exceptions thrown from json.net  
2013-08-09

---

(or i can change the version up to 4.0.0.0 or something and it works)  
2013-08-09

### PR DESCRIPTION
**Pull request by shoter**
## Comment change

Fixes: https://github.com/NuGet/Home/issues/8408

Comment will no longer reference codeplex issue. Codeplex might disappear completelly from internet in the future so it's not advised to keep any reference to it.

### CODE REVIEW

**Review by zivkan — APPROVED** [review]

**Review by dominoFire — APPROVED** [review]
Thanks for your contribution, @shoter 

It seems that the original Codeplex issue is resolved.

**Comment by nkolev92** [comment]
I want to make sure I understand the intended change. 

We just created that issue for tracking? 
Because now as is, this PR would close the newly created issue without a resolution to the bug.

**Review by zivkan — CHANGES_REQUESTED** [review]
Oops, I only hovered over the linked issue and saw that the issue title was replace link. I didn't realise the issue had a misleading title. If this PR is only going to update the link to the issue, the title of the existing issue should be changed to something more meaningful, and a new issue to track this comment change should be created.

**Review by 304NotModified — APPROVED** [review]

**Comment by shoter** [comment]
@nkolev92 
I see from the code already implemented the feature but someone might double check that.

@zivkan 
I changed the name of the issue I created. 
Should I really create additional ticket just for the sake of tracking the change comment thingy? If yes then I will create new one.

**Comment by zivkan** [comment]
@shoter Our change log and release notes tools looks for "fixes <link to issue>". A commit without a linked issue requires us to investigate and manually fix up the release notes or change log, so yes, every PR, no matter how trivial, needs a linked issue.

Having said that, if the bug/functionality is already fixed, we should remove the comment that links to an issue. Those comments imply there's work that needs to be done, so if the original comment was just documentation about what issue was being fixed by the code below it, it should be removed.

**Comment by nkolev92** [comment]
I agree with @zivkan 

I think the comment should be removed. 
The scenario fixed, does not sound like a peculiar problem that would warrant comments like that.

**Comment by nkolev92** [comment]
@shoter Can you please address the feedback. 
I think removing the reference to the issue is what @zivkan is suggesting.

**Comment by shoter** [comment]
Sorry for long time without feedback. I also agree that comment should be removed.
I will close this PR and the issue and submit other PR + issue.

**Pull request closed without merging**
