### PR TITLE
Unsuppress and fix analyzer warning for VSTHRD010

### PR DESCRIPTION
**Pull request by donnie-msft**
## Bug

Fixes: https://github.com/nuget/client.engineering/issues/1321

Regression? Last working version:

## Description

It seems that the VSTHRD010 analyzer didn't accept VS's `ThreadHelper` as a means to assert being on the UI thread. Adding that to the configuration resolves the warnings.
With a quick search, at least a few dozen VS repos have the same line in their configuration.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — APPROVED** [review]
Are the analyzers installed in all VS projects?

**Comment by donnie-msft** [comment]
> Are the analyzers installed in all VS projects?

Do you mean NuGet repo's VS-related projects?
I think this means Yes: https://github.com/NuGet/NuGet.Client/blob/dev/build/NuGet.ruleset#L126

Do you mean whether all VS repos use them?
If so, did this not suffice?:

> With a quick search, at least a few dozen VS repos have the same line in their configuration.

**Comment by nkolev92** [comment]
It was about our VS projects in particular. 

The ruleset needs to be accompanied by a package, so as long as that package is there, we're all good :)

**Review by zivkan — APPROVED** [review]

**Comment by jeffkl** [comment]
Looks like you made the build angry:
```
D:\a\_work\1\s\test\TestExtensions\API.Test\VSSolutionHelper.cs(520,37): error VSTHRD010: Accessing "API.Test.VSSolutionHelper.EnumerateLoadedProjects" should only be done on the main thread. Await JoinableTaskFactory.SwitchToMainThreadAsync() first. [D:\a\_work\1\s\test\TestExtensions\API.Test\API.Test.csproj]
```

**Comment by donnie-msft** [comment]
> Looks like you made the build angry:
> 
> ```
> D:\a\_work\1\s\test\TestExtensions\API.Test\VSSolutionHelper.cs(520,37): error VSTHRD010: Accessing "API.Test.VSSolutionHelper.EnumerateLoadedProjects" should only be done on the main thread. Await JoinableTaskFactory.SwitchToMainThreadAsync() first. [D:\a\_work\1\s\test\TestExtensions\API.Test\API.Test.csproj]
> ```

I'm aware. The test projects need the same config change, but at the same time, the build only fails from outside of VS. Kind of odd.

**Pull request merged**
