### PR TITLE
Safely delete file fix

### PR DESCRIPTION
**Pull request by Multysh**
If in one project several packages link to the same content file - update is failed with error that file does not exists

### CODE REVIEW

**Comment by Multysh** [comment]
//cc @yishaigalatzer @emgarten @deepakaravindr

**Comment by emgarten** [comment]
@Multysh how does the scenario occur where several projects link to the same file? Does it require modifying the project file outside of nuget?

**Comment by Multysh** [comment]
@emgarten used package with content file reference. Other packages depend on this package. When run update packages with dependency via command line - error. But if update packages from vs2015 - all ok.

For example: 
1. PackageA have content file some.txt
2. PackageB depend on PackageA
3. PackageC depend on PackageA
4. ProjectD depend on PackageB and PackageC

update ProjectD via command line falied(failed at uninstall PackageC on check changes in some.txt)
update ProjectD via vs2015 - ok

**Comment by Multysh** [comment]
For example: 
1. PackageA have content file some.txt
2. PackageB depend on PackageA
3. PackageC depend on PackageA

4. ProjectD depend on PackageB and PackageC

update ProjectD via command line falied
update ProjectD via vs2015 - ok

**Comment by yishaigalatzer** [comment]
@Multysh this looks like the wrong fix for the scenario you describe. It looks like we uninstall package A twice in this scenario and that is what should be fixed rather than skipping the delete.

**Comment by Multysh** [comment]
@yishaigalatze no. PackageA uninstalling once. PackageB have content file some.txt and PackageC have context file some.txt.

**Comment by yishaigalatzer** [comment]
Yes that makes more sense. Your description above was different, there is still a potential issue with the fix for scenarios where the file is not on disk but is still in the project. Not sure how this works?

Also needs a test to make sure we don't regress this again

**Comment by yishaigalatzer** [comment]
Test?

**Comment by Multysh** [comment]
I will try this week

**Comment by Multysh** [comment]
@yishaigalatzer done

**Comment by yishaigalatzer** [comment]
Coolness! Quick question - Did the test fail before your change?

Note: I'll have someone review this in detail and merge @deepakaravindr can you take a look?

**Comment by Multysh** [comment]
@yishaigalatzer  sorry for long answer. Test fail now without changes

**Comment by yishaigalatzer** [comment]
Thanks

**Comment by yishaigalatzer** [comment]
@emgarten can you please review and merge?

**Comment by emgarten** [comment]
Thanks for the fix @Multysh 
Merged with NuGet/NuGet.Client@4f80a6be8df851e5aaeb99974aaaeb9882526f27

**Comment by Multysh** [comment]
@emgarten. In commit NuGet/NuGet.Client@4f80a6b has no my changes. In which branch changes merged?

**Comment by Multysh** [comment]
@emgarten thanks!

**Pull request closed without merging**
