### PR TITLE
Rebuild httpclient when credentials change

### PR DESCRIPTION
**Pull request by emgarten**
This change brings back fully replacing an httpclient when credentials are updated.

The old httpclient is not disposed of since there is no safe way to do this. Potentially it could start out with the correct credentials and be in the middle of a large download when the password on the server is changed. At that point the original call is out of HttpSource and the caller is just reading the response stream.

Credentials from nuget.config are added on the first creation of the http client and kept once they have worked. The number of times the client will be recreated should be very low.

https://github.com/NuGet/Home/issues/2058

//cc @zhili1208 @yishaigalatzer @joelverhagen @yugangw-msft

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
I don't follow why were need to recreate the client, the handle should have no state if possible and we need to figure out a different way to pass credentials. Consider passing a credential provider through the request property

**Comment by emgarten** [comment]
Take a look at the bug.

**Comment by yishaigalatzer** [comment]
What properties address you changing, this should be a request property, and your should recreate the request not there client

**Comment by emgarten** [comment]
Currently we aren't creating those requests ourselves. We would need to re-implement those parts of the default http message handler to create one that allows updating the credentials on the fly in order to save creating an httpclient in some scenarios.

**Comment by emgarten** [comment]
We can re-visit optimizing this as part of the core clr proxy support. As part of that we should be able to change the base message handler once it is no longer handling proxies for nuget.

**Comment by yishaigalatzer** [comment]
Is this because of the VSO process where credentials change mid restore?
How do we guarantee that this only gets called in this rare case?

Is there another scenario where credentials change?

**Comment by emgarten** [comment]
Prompting the user changes it. If it is set in nuget.config is added to the credential store at the start.

**Comment by emgarten** [comment]
STS can also update it once at the start.

**Comment by yishaigalatzer** [comment]
That could actually happen often enough in visual studio. I would look for a wait to either work around the default handler or find a way to dispose the http client or will end up with handle leaks in vs.

If you think the work is too big to address right now, let's review alternatives with a follow up bug being one of them

**Comment by yishaigalatzer** [comment]
There is a way to track all open streams using a slim semaphore. Wrap all created streams and make an sync dispose blocked an all streams being disposed. I like dealing the handler creds better but I'm not sure how complex it will be

**Pull request closed without merging**
