### PR TITLE
To improve build time, upgraded CleanCache to be able to only clean NuGet.* packages.

### PR DESCRIPTION
**Pull request by deepakaravindr**
Converted the switch CleanCache to be string parameter which takes one of

the following values. Made similar changes to runFuncTests.ps1

"none" - Default
"all" - Same as current CleanCache switch
"webcache" - only deletes the web cache on localappdata
"allpackages" - only deletes the packages
"nugetpackages" - only deletes NuGet.\* packages

@emgarten @alpaix

### CODE REVIEW

**Comment by alpaix** [comment]
:shipit:

**Comment by emgarten** [comment]
It might actually be safer to clear the packages folder completely before each run and just leave the web cache. That way if branches have different feeds (dev and release do) there won't be any cross contamination. 

This should use nuget.exe locals where possible.

For the CI to actually replace a NuGet.\* package such as NuGet.Core fully this needs to remove it from the web cache also, but there is no way to combine those flags here.

**Comment by deepakaravindr** [comment]
Based on our discussion, we decided that except for NuGet.\* packages, there is not much value in restoring packages over and over again on every build, given that a package version is technically immutable.

We can potentially use nuget.exe locals, but especially the change I have added cannot use nuget.exe locals which is to only delete NuGet.\* packages. Given that deviation, let us not use nuget.exe locals.

By branches using different feeds, do you mean the additional "dotnetcore" feed on the dev branch? If that is problem enough, it is illegal to not clean the cache on every build on the CI agents. If that is the case, I will abandon this PR. The main point of this PR is to improve the build time. If we are cleaning the packages folder every time, I don't think that will be helpful.

Let me know if I should merge or abandon the PR.

**Comment by deepakaravindr** [comment]
This PR is NOT merged. We will simply add a build step to the CI, to clear cache as desired.

**Pull request closed without merging**
