### PR TITLE
Adding - DependencyVersion to NuGet Update 

### PR DESCRIPTION
**Pull request by Ja5p3rMcM**
This is an extension of the changes completed by this [PR](https://github.com/NuGet/NuGet.Client/commit/6f8d529312187fa1b6734da8d4ed9dc3442b916c) where DependencyVersion was added to the NuGet Install command. 

There has been much discussion about adding this to NuGet update also but have never been done.  This should fix issue [2746](https://github.com/NuGet/Home/issues/2746) among others.

### CODE REVIEW

**Comment by nkolev92** [comment]
@aortiz-msft @karann-msft 

Are we interested in taking this? 


@anangaur @rrelyea might have some input as well.

**Comment by karann-msft** [comment]
this need to follow the "issue" - "spec" - "spec review" - "pr" - "pr review" flow. 
Looking at the linked issue it was closed with the comment that package reference would eliminate the need for this switch. Based on that, I don't see the point of this PR.

**Comment by nkolev92** [comment]
Yeah, this is a non-scenario in PackageReference. 
Given that, I'm also comfortable with not taking it.

**Comment by nkolev92** [comment]
This PR itself is actually a duplicate of https://github.com/NuGet/NuGet.Client/pull/2800. 

We should discuss the resolution in the old PR. 

Thanks for the effort @Ja5p3rMcM

**Pull request closed without merging**
