### PR TITLE
Add a test case InstallPackageToWebSiteFromUI into "NuGetUITestCase.cs" file

### PR DESCRIPTION
**Pull request by v-luzh**
## Bug

Fixes:

Regression? Last working version:

## Description
Add a test case InstallPackageToWebSiteFromUI: Install particular package to C# ASP Web Site Project from PM UI. 

The test case is added into the end of the ...\NuGet.Tests.Apex\NuGetEndToEndTests\NuGetUITestCase.cs file.

- We create a bulk of C# ASP Web Site Projects with `Theory`.
- Install a particular package with different package version from NuGet PM UI. 
- Go to packages.config file and verify the package is installed successfully.

## PR Checklist

- [ ] PR has a meaningful title
- [ ] PR has a linked issue.
- [ ] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [ ] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [ ] N/A

### CODE REVIEW

**Comment by erdembayar** [comment]
@v-luzh 

Newly added Apex test failed on CI pipeline. It looks like you added new `EmptyWeb46.zip`, `WebApplication46.zip`  . . assets into your test, please make sure they are committed with source control.
Below is log tests.

```
Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the  'EmptyWeb46.zip' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.8'.
---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the  'WebApplication46.zip' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.8'.
---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the  'WebWCFService.zip' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.8'.
---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the  'DynamicDataEntityFrameworkWebSite.cs.zip' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.8'.
---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)Microsoft.Test.Apex.VisualStudio.Solution.TemplateException : Visual Studio (Enterprise - Team_Suite) could not find the  'DynamicDataLinqToSqlWebSite.cs.zip' template for language 'CSharp\Web\WebSite' in framework '.NETFramework,Version=v4.5'.
---- System.IO.FileNotFoundException : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
```

Please let me know if you need any other details.

**Comment by nkolev92** [comment]
It's likely that the config for VS needs to be updated.

@v-luzh 
The delta is really large right now. You probably want to have both branches on the same sha. 

Consider rebasing both on top of latest dev.

**Comment by v-luzh** [comment]
Hi @nkolev92, @erdembayar, I have submitted a commit to change the config file for VS in branch "dev-TestTeam-Automation" 14 days ago, and the file had the workloads we need for this test already as below screenshot. But why the templates still cannot be found?
image

**Comment by v-luzh** [comment]
Is that because the config file for VS in my local branch: v-luzh: dev-TestTeam-Automation didn't have the same change last night? I have submitted another commit to update the "https://github.com/v-luzh/NuGet.Test/blob/dev-TestTeam-Automation/build/tests.dev17.vsconfig". Should I submit another PR or rerun a new build in NuGet.Client-PrivateDev pipeline?

**Comment by zivkan** [comment]
You don't need to create another PR, but since your branch merged the dev branch, it's now almost impossible to find your changes.  You should undo the merge, then rebase onto NuGet/NuGet.Client's latest dev branch, then force push. If you try to push without specifying `--force`, git's output will tell you to merge, but you should ignore it.  Git's advice to merge is correct for "long lived" branches, like "dev" and the "release-*" branches. But for `dev-*` branches where we are working on changes before they're merged, we should never merge, always rebase.

**Comment by zivkan** [comment]
Also, when I look at the last build on CI, it did not contain the `tests.dev17.vsconfig` changes, so I don't believe we've tested yet if the vsconfig changes will bring in the templates.

**Comment by zivkan** [comment]
Actually, that's not correct. yesterday the PR was run on CI, but for some reason it excluded the vsconfig file change. However, 14 days ago the vsconfig file change commit was run, and the tests passed: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6678742&view=results (it was an unrelated test that failed, our tests are not 100% reliable).

**Comment by erdembayar** [comment]
@v-luzh 
I believe you need to rebase your [NuGet:dev-TestTeam-Automation](https://github.com/NuGet/NuGet.Client/tree/dev-TestTeam-Automation) branch with dev too, otherwise it shows many other changes not related to your change, so it inflates number of changed files, it's very hard to reason with too many changes. For example: [NuGet:dev-TestTeam-Automation](https://github.com/NuGet/NuGet.Client/tree/dev-TestTeam-Automation)

**Comment by v-luzh** [comment]
Hi @erdembayar @zivkan, thanks for your instructions. I will close this PR, sync my forked repo with dev (Is "sync fork" same with "rebase branch"?), git clone to local VM, change the code and force push a draft PR again.

**Pull request closed without merging**
